### PR TITLE
Use correct locale names

### PR DESCRIPTION
**Pull request by hangy**
According to Android lint, the locale names need to match the java.util.Locale values.

### CODE REVIEW

**Comment by VaiTon** [comment]
@teolemon can we merge or it gets ovewritten?

**Comment by teolemon** [comment]
for values-he: https://stackoverflow.com/questions/8393771/android-not-using-finding-my-hebrew-localization

**Comment by hangy** [comment]
> for values-he: https://stackoverflow.com/questions/8393771/android-not-using-finding-my-hebrew-localization

Doesn't really help if that translation doesn't get updated. Also, that's apparently only required for an old Galaxy SII? The official language code for Java is `iw`. Realistically, how many users does this affect in practice? The rest will get likely get English as a fallback anyways.

**Comment by teolemon** [comment]
I think we can map the same Crowdin language to 2 files.

**Comment by VaiTon** [comment]
@teolemon is this related to the branch you merged?
```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processOpfDebugResources'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > Android resource linking failed
     /home/runner/work/openfoodfacts-androidapp/openfoodfacts-androidapp/app/src/main/res/layout/activity_continuous_scan.xml:16: AAPT: error: resource mipmap/example_screenshot_scan (aka org.openproductsfacts.scanner:mipmap/example_screenshot_scan) not found.
```

**Comment by teolemon** [comment]
I technically didn't merge it, but yes.

**Comment by teolemon** [comment]
merging. Let's see how it goes 👍

**Pull request merged**
