### PR TITLE
[Closes #273] Added the ability to open product pages by URL

### LINKED ISSUE #273: Handle opening *.openfoodfacts.org urls with the app
https://developer.android.com/training/app-links/index.html

1. In your app manifest, create intent filters for your website URIs.
2. Configure your app to request verification of app links.
3. Publish a Digital Asset Links JSON file on your websites to provide verification.

- [x] Products
- [x] Labels
- [x] Brands
- [x] Categories
- [x] Stores

### PR DESCRIPTION
**Pull request by Karljoones**
## Description
Adds deep linking for:

- Products
- Additives
- Allergens
- Categories
- Search
- Contributors
- Country
- Label
- Manufacturing Place
- Origin
- Packaging
- State
- Store

Closes #273

### CODE REVIEW

**Comment by deniger** [comment]
There is an issue with Travis-CI:
MainActivity.java:398: error: cannot find symbol
            result.updateName(ITEM_OBF, new StringHolder(getString(R.string.open_food_drawer)));

https://travis-ci.org/openfoodfacts/openfoodfacts-androidapp/builds/573136165?utm_source=github_status&utm_medium=notification

Maybe @Karljoones fork is not uptodate ?

**Comment by Karljoones** [comment]
@deniger aye, this is on me. Will sort it this evening, just haven't had a chance :)

**Comment by teolemon** [comment]
@Karljoones did you have a chance to look into it ?

**Comment by Karljoones** [comment]
Sorry @teolemon, been swamped with work and a bit unwell, will get it sorted asap though

**Comment by teolemon** [comment]
small conflicts to solve @Karljoones

**Comment by teolemon** [comment]
While rebasing, it seems I reintroduced some stuff about the wifi upload service, that had been removed. We need to remove those again

**Comment by deniger** [comment]
If I try to open product from Chrome link:
`
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: openfoodfacts.github.scrachx.openfood, PID: 9487
    java.lang.NullPointerException: Attempt to invoke virtual method 'openfoodfacts.github.scrachx.openfood.models.Product openfoodfacts.github.scrachx.openfood.models.State.getProduct()' on a null object reference
        at openfoodfacts.github.scrachx.openfood.views.product.ingredients.IngredientsProductFragment.refreshView(IngredientsProductFragment.java:192)
        at openfoodfacts.github.scrachx.openfood.views.adapters.ProductFragmentPagerAdapter.refresh(ProductFragmentPagerAdapter.java:47)
        at openfoodfacts.github.scrachx.openfood.views.product.ProductActivity.onNewIntent(ProductActivity.java:280)
        at android.app.Activity.performNewIntent(Activity.java:7816)
        at android.app.Instrumentation.callActivityOnNewIntent(Instrumentation.java:1399)
        at android.app.Instrumentation.callActivityOnNewIntent(Instrumentation.java:1412)
`

**Comment by teolemon** [comment]
@Karljoones @deniger 3 files in merge conflict

**Comment by teolemon** [comment]
@Karljoones I'd very much like to include that one in the Christmas release if works well.

**Comment by teolemon** [comment]
@Karljoones @VaiTon would you have some time to rebase, review and merge this one ?

**Comment by Karljoones** [comment]
Thanks for updating that @VaiTon, been struggling to find the time to resolve. :)

**Comment by teolemon** [comment]
New merge conflicts

**Comment by teolemon** [comment]
3 small conflicts to merge

**Pull request merged**
