### PR TITLE
Closes Issue#1491: Added right and left margin to offline card view.

### LINKED ISSUE #1491: Add left and right padding to the offline edit view
image

As a card, it shouldn't be edge to edge. Add a minimal amount of left and right padding so that it looks good.

### PR DESCRIPTION
**Pull request by SaumiaSinghal**
## Description

Describe the changes made and why they were made instead of how they were made.

- Added right and left margin to offline card view.
- Changed "Information" to "How does it work?" in strings.xml.

## Related issues and discussion
#Fixes #1491 
 
 ## Screen-shots, if any

screenshot_1528109165

 ## Checklist
 
Make sure you've done all the following (You can delete the checklist before submitting)
 
 - [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.
 - [x] Code is well documented
 - [x] Include unit tests for new functionality
 - [x] All user-visible strings are made translatable
 - [x] Code passes Travis builds in your branch
 - [x] If you have multiple commits please combine them into one commit by squashing them.
 - [x] Read and understood the contribution guidelines .

### CODE REVIEW

**Comment by teolemon** [comment]
Note: translations propagate automatically, so you only need to edit the source language.

**Comment by SaumiaSinghal** [comment]
I tried changing just the string.xml file but the changes didn't reflect in the UI of the app. So, I went about changing the avlue in all other xml files.

**Comment by teolemon** [comment]
Thank you @SaumiaSinghal :)
Merged. Congratulations on your first contribution to Open Food Facts 👍

**Comment by SaumiaSinghal** [comment]
Thanks @teolemon...:)

**Pull request merged**
