### PR TITLE
Closes #1144 The labels of some languages in hindi are not correct

### LINKED ISSUE #1144: The labels of some languages in hindi are not correct
**Summary:** 

For some languages like English, French etc. These labels in hindi are set to the hindi names of these languages. Whereas it should be "en" for english, "fr" for french etc.

**Expected behavior:** 

Due to this, the label after changing the laguage to english back from hindi is set to अंग्रेज़ी. This causes problems in other parts of the app like the Add Alergens

**ScreenShots**
screenshot_20180307-111932

### PR DESCRIPTION
**Pull request by ManavPoddar**
## Description

Now the labels are correct. Also the allergen alert is working fine now

## Related issues and discussion
#1134 This is fixed Now

### CODE REVIEW

**Comment by Karljoones** [comment]
This was fixed in PR #1135, no? Please make sure to check out the latest code to see if this was resolved.

**Comment by ManavPoddar** [comment]
No @Karljoones , It is not fixed in PR #1135 , I have also checked with the latest code

**Comment by Karljoones** [comment]
Just making sure! Wasn't 100% myself :)

**Comment by teolemon** [comment]
Also for translations, you can correct them directly on Crowdin

**Comment by l-o-b-s-t-e-r** [comment]
@Karljoones 
Yes, it wasn't fixed because I didn't even know that somebody could translate the international standard (country codes). So I just fixed translation of full county names.

**Comment by l-o-b-s-t-e-r** [comment]
@Karljoones 
@teolemon 
This PR is good, but this is not enough. It fixes the only 1 language...but there is no guarantees that somebody won't translate country codes again in the future.

**Comment by teolemon** [comment]
@l-o-b-s-t-e-r indeed. I'm sure we fixed it at some point, and not sure why it reappeared.

**Comment by l-o-b-s-t-e-r** [comment]
@teolemon 
Because the country codes can be translatable. 
They are available for each language: https://crowdin.com/translate/openfoodfacts/83/en-uk, so every one can translate this.

We need to make them untranslatable directly in the android app (something like this: <string-array name="lang_array" translatable="false">)

**Pull request merged**
