### PR TITLE
feat: Added In-App Review Functionality - Fixing Issue #4600 

### PR DESCRIPTION
**Pull request by lailajs**
####  Description
Hello! I added the functionality of the Google In-App Review Functionality, as labeled in issue 4600. Thank you!

### CODE REVIEW

**Review by g123k — CHANGES_REQUESTED** [review]
Thanks for your PR @lailajs, but your implementation is available for all flavors.
As we also publish to Fdroid, this API should only be used with playStore flavor.

Could you make that change please?

**Comment by lailajs** [comment]
> Thanks for your PR @lailajs, but your implementation is available for all flavors. As we also publish to Fdroid, this API should only be used with playStore flavor.
> 
> Could you make that change please?

Hi! I am not exactly sure what that means, could you help me understand it better? Thanks!

**Comment by VaiTon** [comment]
> > Thanks for your PR @lailajs, but your implementation is available for all flavors. As we also publish to Fdroid, this API should only be used with playStore flavor.
> > Could you make that change please?
> 
> Hi! I am not exactly sure what that means, could you help me understand it better? Thanks!

We publish two version of the app with little modifications. The first is for the Google Play Store, the second is for FDroid. For the FDroid users we do not include google libraries only available to those who installed the playstore as it is often used on OS without it.

You can find the definition of the two flavors in the app/build.gradle.kts. You should put the code only in the fdroid source folder and the fdroid flavor.

**Comment by VaiTon** [comment]
Superseded by https://github.com/openfoodfacts/openfoodfacts-androidapp/pull/4860

**Pull request closed without merging**
