### PR TITLE
Update android constraint layout to 1.1.0 .

### PR DESCRIPTION
**Pull request by ross-holloway94**
## Description

Updates 'com.android.support.constraint:constraint-layout'
 to 1.1.0 . 
See https://medium.com/google-developers/introducing-constraint-layout-1-1-d07fc02406bc for a showcase if the new features (of particular interest - percentage heights and widths).

### CODE REVIEW

**Comment by ross-holloway94** [comment]
3 out of 4 jobs have passed. The first one keeps stalling for some reason.

**Comment by Karljoones** [comment]
That is strange, not even any information on what went wrong with the build.

**Comment by ross-holloway94** [comment]
@Karljoones yes, and it just keeps hanging.

**Comment by huzaifaiftikhar** [comment]
@Karljoones This is not our issue, Travis team has changed certain things starting today. Take a look here for the [current status](https://www.traviscistatus.com/). I guess we should just wait before they fix everything.

**Pull request merged**
