### PR TITLE
Fixed layout issue on some attributes with long text

### LINKED ISSUE #3724: Layout issue on some attributes with long text
Layout issue on some attributes with long text
image

### PR DESCRIPTION
**Pull request by varunvjha**
####  Description

I added a bottom margin to the seperator.

#### Related issues
Fixes #3724

### CODE REVIEW

**Comment by VaiTon** [comment]
I'm sorry but you can't fix this by only putting a margin as the height of the element is fixed. Instead you should make the height 0dp and then fix the margins.

**Review by VaiTon — CHANGES_REQUESTED** [review]
See https://github.com/openfoodfacts/openfoodfacts-androidapp/pull/3727#issuecomment-759431356

**Comment by teolemon** [comment]
@VaiTon is it fixed by the other PR ?

**Comment by VaiTon** [comment]
> 
> 
> @VaiTon is it fixed by the other PR ?

Which one?

**Comment by teolemon** [comment]
@VaiTon I dreamt it :-)

**Review by VaiTon — APPROVED** [review]

**Pull request merged**
