### PR TITLE
Closes #117 : Calculate calories for given weight

### LINKED ISSUE #117: Calculate calories for given weight
Given a weight of food, calculate the number of calories for that portion

### PR DESCRIPTION
**Pull request by huzaifaiftikhar**
## Description

- Added option to calculate calories for given weight in the overflow menu. This option in the overflow menu will hide automatically for products that are incomplete and don't have the calories information.

- Moved `getEnergy` method from _NutritionInfoProductFragment.java_ to _Utils.java_ as this method is now used in two different classes.

- Added custom layout background for the spinner as the in the default spinner layout the drop-down arrow was far away from the text and didn't look good. Somewhat like [this](https://stackoverflow.com/questions/34322156/how-to-move-the-android-spinner-drop-down-arrow-closer-to-its-emitting-text/34322887).

## Related issues and discussion
Fixes #117 
 
 ## Screen-shots, if any
videotogif_2018 03 21_01 59 11

 

 ## Checklist
 
Make sure you've done all the following (You can delete the checklist before submitting)
 
 - [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.
 - [x] Code is well documented
 - [x] Include unit tests for new functionality
 - [x] All user-visible strings are made translatable
 - [x] Code passes Travis builds in your branch
 - [x] If you have multiple commits please combine them into one commit by squashing them.
 - [x] Read and understood the contribution guidelines.

### CODE REVIEW

**Comment by huzaifaiftikhar** [comment]
@Karljoones Sure I will try to document the code. I was not sure about the UI and thus opened the PR for discussions. Yes even I feel that this feature would look more appropriate if placed in an overflow menu. Waiting for other people to review before pushing another commit.

**Comment by Karljoones** [comment]
@huzaifaiftikhar Please document this code a bit better too, we are pushing to get the code documented correctly. Please ensure that people understand what the code you wrote does

**Comment by teolemon** [comment]
I feel like this feature could be even more useful with a diet mode: I ate 100g of Nutella, add this to my daily log.

**Comment by huzaifaiftikhar** [comment]
@teolemon I have added this feature the overflow menu as suggested by @Karljoones. I agree that this feature would be more useful with a diet mode which can be implemented by adding a button "Add to diary" to the above dialog. We can have a UI something like the below image. 
diets log

The user would be able to access the daily log/diary via the navigation drawer.
@Karljoones I have documented the code :slightly_smiling_face:

**Comment by Karljoones** [comment]
@teolemon What do you want to do with this? Maybe for now we can move the code into a Utils class for later reference

**Comment by Karljoones** [comment]
Can we have a final screenshot of the finished product i.e. the dialog? Going to merge this as it's been here quite a while.

**Comment by huzaifaiftikhar** [comment]
The gif attached with the PR is the final one. No changes have been made after that.

**Comment by Karljoones** [comment]
@huzaifaiftikhar can you resolve the conflicts here?
@teolemon I am going to merge this, may not be the most ideal place for the feature but we can move it around later if we need to

**Comment by teolemon** [comment]
I solved the conflict. Ok for merging.

**Comment by huzaifaiftikhar** [comment]
@teolemon so what should we do? Add this option to the bottom bar? Do we have a list of options that we need at the bottom bar? I think according to material design guidelines, bottom bar can have a maximum of five buttons only.

**Comment by teolemon** [comment]
Let's keep it in the top button like you did initially. The bottom bar is still a work in progress that needs to be fixed.

**Comment by huzaifaiftikhar** [comment]
@teolemon So I guess this is ready for merging as you already resolved the conflicts :slightly_smiling_face: 
The Travis build fails due to exceeding the time limit.

**Comment by teolemon** [comment]
Can you rebase on latest trunk ? It should fix the build.

**Comment by teolemon** [comment]
was approved, builds. merging.

**Pull request merged**
