### PR TITLE
Added BottomNavigationView to Product_Activity.

### PR DESCRIPTION
**Pull request by abhinavbajpai2012**
Added a bottom bar with the Barcode scanner FAB anchored to it.
screenshot_2018-02-14-16-58-03-889_openfoodfacts github scrachx openbeauty

### CODE REVIEW

**Comment by Karljoones** [comment]
Before any commit can be made, the floating action button would need to be positioned correctly so that it does not override the bottom navigation bar. However, before doing this, you may want to consult @teolemon as to whether or not this design is going to be consistent with the design of the other apps.

**Comment by Shubham2320** [comment]
It's a duplicate of PR #746.

**Comment by Karljoones** [comment]
Hi @abhinavbajpai2012, this pull request seems to be a duplicate of PR #746, to keep the repo neat and tidy, we will close one of these requests. Which one are you currently still working on?

**Comment by abhinavbajpai2012** [comment]
@Karljoones use the PR #746 , I am working on that one.

**Comment by Karljoones** [comment]
Closed duplicate

**Comment by abhinavbajpai2012** [comment]
The floating action button was to be placed over the bottom bar as shown in the screenshot by @teolemon  in the issue #704

**Pull request closed without merging**
