### PR TITLE
Fix: #4546 Fixed sign up and password background buttons

### LINKED ISSUE #4546: [UI] Login: Sign up & Password lost buttons have not visual cues of being pressed/touched
### What
- Sign up & Password buttons should have a background color to let the user understand that they are clickable

Screenshot_20220319_175659

### PR DESCRIPTION
**Pull request by krystelnguyen**
Fixed #4546: https://github.com/openfoodfacts/openfoodfacts-androidapp/issues/4546

### CODE REVIEW

**Review by g123k — APPROVED** [review]
LGTM

**Comment by teolemon** [comment]
Thank you @krystelnguyen  for your contribution to the Open Food Facts project, and congratulations on your 1st merged PR 🎉 👍

**Comment by teolemon** [comment]
small merge conflict @krystelnguyen @g123k

**Comment by g123k** [comment]
@krystelnguyen Could you resync your Git repo and push your commit again?

**Review by g123k — APPROVED** [review]

**Comment by g123k** [comment]
Seems OK now, thanks for your PR @krystelnguyen!

**Pull request merged**
