### PR TITLE
fix #486 #185 share icon size ,colour & share functionality

### LINKED ISSUE #486: Harmonize color and size of the share icon in product page
Small details about sharing. See https://github.com/openfoodfacts/OpenFoodFacts-androidApp/issues/185 for details on how to implement native sharing.

image

### PR DESCRIPTION
**Pull request by SatyamBansal**
## Description

changed the icon colour from grey to black , fixed the size of icon to match edit icon , implemented direct share

## Related issues and discussion
#{486,185}
 
 ## Screen-shots, if any

screenshot_1518841477
screenshot_1518841490

### CODE REVIEW

**Comment by SatyamBansal** [comment]
Hmm just checked files for #768 i think it might  not clash since in #768 only style is changed for toolbar

**Comment by Karljoones** [comment]
@SatyamBansal OK, I see what you mean. I am not going to merge it right now, we are just waiting for some changes on the other PR. Once the other PR is merged, then I will check back on this and ensure that this will merge without a hitch. Thanks for all the work!

**Comment by SatyamBansal** [comment]
👍i appreciate it

**Comment by teolemon** [comment]
@Karljoones @SatyamBansal a bit lost on this one.

**Comment by SatyamBansal** [comment]
Why?

**Comment by teolemon** [comment]
@Karljoones is the PR blocking this one (#768 or other) merged ? Can I proceed with merging ?

**Comment by Karljoones** [comment]
@teolemon I think it should be okay for merging now that the other PR is merged.

**Comment by teolemon** [comment]
Ok, merged :)

**Comment by teolemon** [comment]
Thanks you @SatyamBansal :-)

**Pull request merged**
