### PR TITLE
Fixed #1403 :Convert the product view cards to proper material cards 

### LINKED ISSUE #1403: Convert the product view cards to proper material cards
Convert the product view cards to proper material cards, with drop shadows
image
image

### PR DESCRIPTION
**Pull request by PrajwalM2212**
## Description

Changed the layout 

## Related issues and discussion
#1403 
 
 ## Screen-shots, if any
 
image

### CODE REVIEW

**Comment by Karljoones** [comment]
@PrajwalM2212 can we have a bit of padding between the image and the nutriscore? Also, the boxes around the inner items looks kind of odd since you can just see the outline and there is no inner padding. Maybe it would be best to remove these

**Comment by PrajwalM2212** [comment]
@Karljoones 
screenshot_1523036733

**Comment by PrajwalM2212** [comment]
@teolemon This is approved .

**Comment by teolemon** [comment]
Merged. Thanks @PrajwalM2212

**Pull request merged**
