### PR TITLE
Solved bug appeared in schema in implementation of wikidata

### PR DESCRIPTION
**Pull request by Shubham2320**
## Description

Schema version is changed to 7

## Related issues and discussion
Issue #1327 
modified PR #1332

### CODE REVIEW

**Comment by Shubham2320** [comment]
@teolemon @Karljoones @l-o-b-s-t-e-r  please review it.

**Comment by teolemon** [comment]
poke @l-o-b-s-t-e-r ;-)

**Comment by l-o-b-s-t-e-r** [comment]
Yeah, it works.
One more thing which should be done while upgrading is setting shared property "last_refresh_date" -> 0, to make sure that application will load data again and fill WikiData. Just open the SplashPresenter and look at "isNeedToRefresh()" method to understand how it's used.

To tell the truth after deep investigation of code related to WikiData issue, I have a few suggestions about implementation. Let me know if somebody is interested in my opinion.

**Comment by Shubham2320** [comment]
It gets updated int the splashPresenter itself in the same way in which taxonomies gets updated so there is no need to do that.

**Comment by l-o-b-s-t-e-r** [comment]
If you don't do it, Application will refresh data only after 24hours from the last update date, but we need to update it right after installing the new version.

**Comment by Shubham2320** [comment]
Ohh I see, so instead of adding a new variable, I would like to change the string of `last_refresh_date` in shared preference so.

**Comment by l-o-b-s-t-e-r** [comment]
But you didn't set it = 0 while upgrading :D

**Comment by Shubham2320** [comment]
could you explain why it is required?

**Comment by l-o-b-s-t-e-r** [comment]
Okay, we figured it out. Everything is ok, application will update data immediately after installing the new version :)

**Pull request merged**
