### PR TITLE
fix: not working language selection 

### LINKED ISSUE #3437: You can't switch language from settings anymore
You can't switch language from settings anymore
- [x] Taxonomy (works)
- [x] Robotoff (works)
- [ ] UI (broken)

### LINKED ISSUE #3540: The language preference is ignored unless it's set system-wide
**Describe the bug**
I'm a Catalan language translator and I've found that setting Catalan as language in preferences is not working, unless your Android system dude language is also Catalan.
Same for Spanish.

**To Reproduce**
1. Set system language to Spanish.
2. OFF correctly defaults to Spanish.
3. Go to preferences and select Catalan.
4. UI language is now in English.

Tested also swapped ES/CA system and lang on another device using CA/ES for sys/lang.

**Smartphone:**
 - Device: Moto G5s
 - OS: Android 7.0
 - Browser: Android app
 - Version: 3.4.8 (latest from Google Play)

### PR DESCRIPTION
**Pull request by VaiTon**
Also a general refactor to use kotlin inline for building things.

Closes https://github.com/openfoodfacts/openfoodfacts-androidapp/issues/3540.
Closes #3437.

### Tasks:
- [x] 🐛 Login header  crashing the app
- [x] #4196

### Test APK
https://github.com/openfoodfacts/openfoodfacts-androidapp/suites/3615337385/artifacts/87373606

### CODE REVIEW

**Comment by teolemon** [comment]
@VaiTon just tested the build, it works. Nice touch with the icon 👍

**Comment by teolemon** [comment]
I found this one, just after login: https://sentry.io/organizations/openfoodfacts/issues/2608035872/?project=5276851&query=is%3Aunresolved

**Comment by teolemon** [comment]
Also closes https://github.com/openfoodfacts/openfoodfacts-androidapp/issues/3437

**Comment by teolemon** [comment]
Not sure if the issue was introduced in this PR, but I spotted that. The photo is not uploaded, and no animation 
https://user-images.githubusercontent.com/1689815/131176570-2a029f06-891f-4939-aab2-ea7a6485ff60.mp4

**Comment by VaiTon** [comment]
> 
> 
> Not sure if the issue was introduced in this PR, but I spotted that. The photo is not uploaded, and no animation
> https://user-images.githubusercontent.com/1689815/131176570-2a029f06-891f-4939-aab2-ea7a6485ff60.mp4

Try to re-scan the product

**Comment by VaiTon** [comment]
> 
> 
> I found this one, just after login: https://sentry.io/organizations/openfoodfacts/issues/2608035872/?project=5276851&query=is%3Aunresolved

Idk what's causing this. Investigating right now

**Comment by teolemon** [comment]
It pretends to have uploaded the image, but nothing, not even the first one this time :-/

**Comment by teolemon** [comment]
I found this one in the branch as well. Not sure if related to your changes: https://github.com/openfoodfacts/openfoodfacts-androidapp/issues/4196. Happens on trying to edit a product

**Comment by teolemon** [comment]
New artefact: https://github.com/openfoodfacts/openfoodfacts-androidapp/suites/3623909306/artifacts/87647039

**Comment by teolemon** [comment]
@VaiTon LGTM 👍 ✅

**Review by teolemon — APPROVED** [review]

**Pull request merged**
