### PR TITLE
Add EMB Codes

### LINKED ISSUE #256: Cities where bought is in fact the city associated with the packager code
**ISSUE:**"`Cities where bought:`" displays the city where the product was packaged.`Amiens`
**SOLUTION:** It should display "`Packager code :` " with the Raw value of the packager code (`FR 45.533.33 CE` or `EMB 54365`) and then the city name currently displayed.
**Example:**`FR 45.533.33 CE - Amiens`

"`Country where sold:`" actually contains the city AFAIK ("`City, state and country where purchased`" in the web version)

### PR DESCRIPTION
**Pull request by huzaifaiftikhar**
## Description

Add clickable EMB Codes 

## Related issues and discussion
Fixes #256 
 
 ## Screen-shots, if any
 
screenshot_20180225-025911

 ## Checklist
 
Make sure you've done all the following (You can delete the checklist before submitting)
 
 - [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.
 - [x] Code is well documented
 - [ ] Include unit tests for new functionality
 - [ ] All user-visible strings are made translatable
 - [x] Code passes Travis builds in your branch
 - [x] If you have multiple commits please combine them into one commit by squashing them.
 - [x] Read and understood the contribution guidelines .

### CODE REVIEW

**Comment by policorn** [comment]
Hi @huzaifaiftikhar, It works with fresh installs but if I upgrade from a previous version (for example, build & run master, build this PR code and upgrade the app) the app crashes with the following error:

```
02-25 01:00:35.665 15880-15905/openfoodfacts.github.scrachx.openfood E/SQLiteLog: (1) no such table: TAG
02-25 01:00:35.666 15880-15905/openfoodfacts.github.scrachx.openfood E/OpenFoodAPIClient: android.database.sqlite.SQLiteException: no such table: TAG (code 1): , while compiling: INSERT OR REPLACE INTO "TAG" ("NAME","PRODUCTS","URL","ID") VALUES (?,?,?,?)
```

Can you try to reproduce and get it fixed please?

**Comment by huzaifaiftikhar** [comment]
@policorn I guess this issue is regarding the schema. I will try to fix this and send a PR ASAP.

**Comment by teolemon** [comment]
CC @itchix for the GreenDAO issue

**Comment by huzaifaiftikhar** [comment]
Regarding the problem with SQLiteException, I tried upgrading the schema version in gradle to 3. Still there was no luck and it crashes if we are upgrading (not a fresh install). However, I read everywhere including greendao's docs still no luck. [docs.](http://greenrobot.org/greendao/documentation/modelling-entities) I've seen a method in our codebase where it is written that we don't have to upgrade schema and just `switch` the versions.
Probably this was written consulting [drindt's comment here](https://github.com/greenrobot/greenDAO/issues/137)

We must have faced similar issue while upgrading from schema 1 to 2 and probably fixed it using the above method. Do you know any workaround for this issue, Here we have created a new table and the `OnUpgrade` method is never called not even after upgrading the schema to 3

**Comment by jaztriumph** [comment]
@huzaifaiftikhar I too faced the same issue then.  `onUpgrade` method will be called when you increase the schema version. So just make a new `case 3` in that switch and write `TagDao.createTable(db, true);` in your case that would be enough and change the `SQLiteDatabase` in parameters to `Database` by importing `org.greenrobot.greendao.database.Database`. I have done this in #887 and it worked well.

**Comment by huzaifaiftikhar** [comment]
@jaztriumph Yeah did that. I was avoiding to upgrade the schema version. Fixed now thanks :+1:

**Comment by policorn** [comment]
Hi @huzaifaiftikhar, there're some conflicting files, can you update/rebase and fix the issue please?

**Comment by huzaifaiftikhar** [comment]
@policorn I have fixed all the issues. Please review xD

**Comment by policorn** [comment]
Thanks @huzaifaiftikhar! Merged

**Pull request merged**
