### PR TITLE
Fixes #2529 : You can edit a product without being logged in if you click on "Add nutrition facts to compute Nutri-Score" #2529 

### LINKED ISSUE #2529: You can edit a product without being logged in if you click on "Add nutrition facts to compute Nutri-Score"
You can edit a product without being logged in if you click on "Add nutrition facts to compute Nutri-Score"
Can we protect it with a login prompt ?

### PR DESCRIPTION
**Pull request by mustaqmustu**
## Related issues and discussion
#2529 
 
 ## Screen-shots, if any
ezgif com-video-to-gif(12)

 
 ## Checklist
 
Make sure you've done all the following (You can delete the checklist before submitting)
 
 - [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.
 - [x] Code is well documented
 - [x] Include unit tests for new functionality
 - [x] All user-visible strings are made translatable
 - [x] Code passes Travis builds in your branch
 - [x] If you have multiple commits please combine them into one commit by squashing them.
 - [x] Read and understood the contribution guidelines .

### CODE REVIEW

**Comment by teolemon** [comment]
Merge conflicts @mustaqmustu

**Comment by mustaqmustu** [comment]
> Merge conflicts @mustaqmustu

Yeah ,solved them :)

**Comment by teolemon** [comment]
I think @deniger introduced a simplified method to do this ?

**Comment by deniger** [comment]
@teolemon  no :)
But I will be great if the code asking the user to login can be mutualized. Otherwise, we will a lot of duplicate code...
A proposition: we can merge this PR as is ( if tested and ok...:)) and then create a new task to mutualize code.

**Comment by teolemon** [comment]
``` 
/home/travis/build/openfoodfacts/openfoodfacts-androidapp/app/build/generated/data_binding_base_class_source_out/obfDebug/dataBindingGenBaseClassesObfDebug/out/openfoodfacts/github/scrachx/openfood/databinding/FragmentCategoryListBinding.java:4: error: cannot find symbol
import android.databinding.DataBindingComponent;
                          ^
  symbol:   class DataBindingComponent
  location: package android.databinding
/home/travis/build/openfoodfacts/openfoodfacts-androidapp/app/build/generated/data_binding_base_class_source_out/obfDebug/dataBindingGenBaseClassesObfDebug/out/openfoodfacts/github/scrachx/openfood/databinding/FragmentCategoryListBinding.java:29: error: cannot find symbol
  protected FragmentCategoryListBinding(DataBindingComponent _bindingComponent, View _root,
                                        ^
  symbol:   class DataBindingComponent
  location: class FragmentCategoryListBinding
/home/travis/build/openfoodfacts/openfoodfacts-androidapp/app/build/generated/data_binding_base_class_source_out/obfDebug/dataBindingGenBaseClassesObfDebug/out/openfoodfacts/github/scrachx/openfood/databinding/FragmentCategoryListBinding.java:52: error: cannot find symbol
      @Nullable ViewGroup root, boolean attachToRoot, @Nullable DataBindingComponent component) {
                                                                ^
  symbol:   class DataBindingComponent
  location: class FragmentCategoryListBinding
/home/travis/build/openfoodfacts/openfoodfacts-androidapp/app/build/generated/data_binding_base_class_source_out/obfDebug/dataBindingGenBaseClassesObfDebug/out/openfoodfacts/github/scrachx/openfood/databinding/FragmentCategoryListBinding.java:63: error: cannot find symbol
      @Nullable DataBindingComponent component) {
                ^
  symbol:   class DataBindingComponent
  location: class FragmentCategoryListBinding
/home/travis/build/openfoodfacts/openfoodfacts-androidapp/app/build/generated/data_binding_base_class_source_out/obfDebug/dataBindingGenBaseClassesObfDebug/out/openfoodfacts/github/scrachx/openfood/databinding/FragmentCategoryListBinding.java:72: error: cannot find symbol
      @Nullable DataBindingComponent component) {
                ^
  symbol:   class DataBindingComponent
  location: class FragmentCategoryListBinding
/home/travis/build/openfoodfacts/openfoodfacts-androidapp/app/build/generated/data_binding_base_class_source_out/obfDebug/dataBindingGenBaseClassesObfDebug/out/openfoodfacts/github/scrachx/openfood/databinding/CategoryRecyclerItemBinding.java:18: error: cannot find symbol
  protected CategoryRecyclerItemBinding(DataBindingComponent _bindingComponent, View _root,
                                        ^
  symbol:   class DataBindingComponent
  location: class CategoryRecyclerItemBinding
/home/travis/build/openfoodfacts/openfoodfacts-androidapp/app/build/generated/data_binding_base_class_source_out/obfDebug/dataBindingGenBaseClassesObfDebug/out/openfoodfacts/github/scrachx/openfood/databinding/CategoryRecyclerItemBinding.java:38: error: cannot find symbol
      @Nullable ViewGroup root, boolean attachToRoot, @Nullable DataBindingComponent component) {
                                                                ^
  symbol:   class DataBindingComponent
  location: class CategoryRecyclerItemBinding
/home/travis/build/openfoodfacts/openfoodfacts-androidapp/app/build/generated/data_binding_base_class_source_out/obfDebug/dataBindingGenBaseClassesObfDebug/out/openfoodfacts/github/scrachx/openfood/databinding/CategoryRecyclerItemBinding.java:49: error: cannot find symbol
      @Nullable DataBindingComponent component) {
                ^
  symbol:   class DataBindingComponent
  location: class CategoryRecyclerItemBinding
/home/travis/build/openfoodfacts/openfoodfacts-androidapp/app/build/generated/data_binding_base_class_source_out/obfDebug/dataBindingGenBaseClassesObfDebug/out/openfoodfacts/github/scrachx/openfood/databinding/CategoryRecyclerItemBinding.java:58: error: cannot find symbol
      @Nullable DataBindingComponent component) {
                ^
  symbol:   class DataBindingComponent
  location: class CategoryRecyclerItemBinding
/home/travis/build/openfoodfacts/openfoodfacts-androidapp/app/src/main/java/openfoodfacts/github/scrachx/openfood/views/product/summary/SummaryProductFragment.java:159: error: variable LOGIN_ACTIVITY_REQUEST_CODE is already defined in class SummaryProductFragment
    private static final int LOGIN_ACTIVITY_REQUEST_CODE = 1;
                             ^
/home/travis/build/openfoodfacts/openfoodfacts-androidapp/app/src/main/java/openfoodfacts/github/scrachx/openfood/dagger/component/AppComponent.java:29: error: cannot find symbol
            return DaggerAppComponent.builder()
                   ^
  symbol:   variable DaggerAppComponent
  location: class Initializer
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
11 errors
```

**Comment by mustaqmustu** [comment]
@teolemon I dont know why the build is failing...Its working in android studio

**Comment by deniger** [comment]
@mustaqmustu in the class SummaryProductFragment, the constant "LOGIN_ACTIVITY_REQUEST_CODE" is defined twice: line 79 and 159

**Comment by deniger** [comment]
@mustaqmustu another point: if the user log in, he is not redirected to the edit view.
You should add code as it's done in: ProductFragment#onActivityResult

**Comment by mustaqmustu** [comment]
> Please see my 2 last comments

yeah I will work on it

**Comment by mustaqmustu** [comment]
> ```
> /home/travis/build/openfoodfacts/openfoodfacts-androidapp/app/build/generated/data_binding_base_class_source_out/obfDebug/dataBindingGenBaseClassesObfDebug/out/openfoodfacts/github/scrachx/openfood/databinding/FragmentCategoryListBinding.java:4: error: cannot find symbol
> import android.databinding.DataBindingComponent;
>                           ^
>   symbol:   class DataBindingComponent
>   location: package android.databinding
> /home/travis/build/openfoodfacts/openfoodfacts-androidapp/app/build/generated/data_binding_base_class_source_out/obfDebug/dataBindingGenBaseClassesObfDebug/out/openfoodfacts/github/scrachx/openfood/databinding/FragmentCategoryListBinding.java:29: error: cannot find symbol
>   protected FragmentCategoryListBinding(DataBindingComponent _bindingComponent, View _root,
>                                         ^
>   symbol:   class DataBindingComponent
>   location: class FragmentCategoryListBinding
> /home/travis/build/openfoodfacts/openfoodfacts-androidapp/app/build/generated/data_binding_base_class_source_out/obfDebug/dataBindingGenBaseClassesObfDebug/out/openfoodfacts/github/scrachx/openfood/databinding/FragmentCategoryListBinding.java:52: error: cannot find symbol
>       @Nullable ViewGroup root, boolean attachToRoot, @Nullable DataBindingComponent component) {
>                                                                 ^
>   symbol:   class DataBindingComponent
>   location: class FragmentCategoryListBinding
> /home/travis/build/openfoodfacts/openfoodfacts-androidapp/app/build/generated/data_binding_base_class_source_out/obfDebug/dataBindingGenBaseClassesObfDebug/out/openfoodfacts/github/scrachx/openfood/databinding/FragmentCategoryListBinding.java:63: error: cannot find symbol
>       @Nullable DataBindingComponent component) {
>                 ^
>   symbol:   class DataBindingComponent
>   location: class FragmentCategoryListBinding
> /home/travis/build/openfoodfacts/openfoodfacts-androidapp/app/build/generated/data_binding_base_class_source_out/obfDebug/dataBindingGenBaseClassesObfDebug/out/openfoodfacts/github/scrachx/openfood/databinding/FragmentCategoryListBinding.java:72: error: cannot find symbol
>       @Nullable DataBindingComponent component) {
>                 ^
>   symbol:   class DataBindingComponent
>   location: class FragmentCategoryListBinding
> /home/travis/build/openfoodfacts/openfoodfacts-androidapp/app/build/generated/data_binding_base_class_source_out/obfDebug/dataBindingGenBaseClassesObfDebug/out/openfoodfacts/github/scrachx/openfood/databinding/CategoryRecyclerItemBinding.java:18: error: cannot find symbol
>   protected CategoryRecyclerItemBinding(DataBindingComponent _bindingComponent, View _root,
>                                         ^
>   symbol:   class DataBindingComponent
>   location: class CategoryRecyclerItemBinding
> /home/travis/build/openfoodfacts/openfoodfacts-androidapp/app/build/generated/data_binding_base_class_source_out/obfDebug/dataBindingGenBaseClassesObfDebug/out/openfoodfacts/github/scrachx/openfood/databinding/CategoryRecyclerItemBinding.java:38: error: cannot find symbol
>       @Nullable ViewGroup root, boolean attachToRoot, @Nullable DataBindingComponent component) {
>                                                                 ^
>   symbol:   class DataBindingComponent
>   location: class CategoryRecyclerItemBinding
> /home/travis/build/openfoodfacts/openfoodfacts-androidapp/app/build/generated/data_binding_base_class_source_out/obfDebug/dataBindingGenBaseClassesObfDebug/out/openfoodfacts/github/scrachx/openfood/databinding/CategoryRecyclerItemBinding.java:49: error: cannot find symbol
>       @Nullable DataBindingComponent component) {
>                 ^
>   symbol:   class DataBindingComponent
>   location: class CategoryRecyclerItemBinding
> /home/travis/build/openfoodfacts/openfoodfacts-androidapp/app/build/generated/data_binding_base_class_source_out/obfDebug/dataBindingGenBaseClassesObfDebug/out/openfoodfacts/github/scrachx/openfood/databinding/CategoryRecyclerItemBinding.java:58: error: cannot find symbol
>       @Nullable DataBindingComponent component) {
>                 ^
>   symbol:   class DataBindingComponent
>   location: class CategoryRecyclerItemBinding
> /home/travis/build/openfoodfacts/openfoodfacts-androidapp/app/src/main/java/openfoodfacts/github/scrachx/openfood/views/product/summary/SummaryProductFragment.java:159: error: variable LOGIN_ACTIVITY_REQUEST_CODE is already defined in class SummaryProductFragment
>     private static final int LOGIN_ACTIVITY_REQUEST_CODE = 1;
>                              ^
> /home/travis/build/openfoodfacts/openfoodfacts-androidapp/app/src/main/java/openfoodfacts/github/scrachx/openfood/dagger/component/AppComponent.java:29: error: cannot find symbol
>             return DaggerAppComponent.builder()
>                    ^
>   symbol:   variable DaggerAppComponent
>   location: class Initializer
> Note: Some input files use or override a deprecated API.
> Note: Recompile with -Xlint:deprecation for details.
> Note: Some input files use unchecked or unsafe operations.
> Note: Recompile with -Xlint:unchecked for details.
> 11 errors
> ```

@teolemon I'm also facing these errors.I referred [this](https://stackoverflow.com/questions/50594507/cannot-find-symbol-databindingcomponent-on-android-studio-3-2-canary-16-kotlin-p),But im unable to solve them,I need help .

**Comment by deniger** [comment]
@mustaqmustu another point: if the user log in, he is not redirected to the edit view.
You should add code as it's done in: ProductFragment#onActivityResult. Do you have to fix this ?

**Comment by teolemon** [comment]
Merging this one, with the understanding that @deniger will make the fixes in another PR

**Pull request merged**
