### PR TITLE
Closes #506: Getting information from wikidata.

### LINKED ISSUE #506: Using Wikidata Toolkit Java Library to enrich facets in the app
Many facets of Open Food Facts (categories, labels…) are linked to Wikidata, which is linked to Wikipedia.

Thus, by getting the Wikidata ID from the API, we can get Wikidata info we can display, and links to Wikipedia, so that the users can get more knowledge: controversies about additives, more info about the wine they are drinking…

https://github.com/Wikidata/Wikidata-Toolkit

### PR DESCRIPTION
**Pull request by Shubham2320**
## Description

- Categories, Labels and Additives are now linked with Wikidata.

- At present, not all categories, labels and additives have Wikidata id so to distinguish them I've used `name : Wiki link present` as the name on the product page it can be changed if a better option is suggested.

- If Wikidata id is present for any item a bottom sheet appears on click of that item and label, description and Wikipedia link for that item is shown on the sheet.

- On click of Wikipedia links opens Wikipedia page of that item.

- An option to browse product is also added which allows the user to search product by that category, label or additive which open list of product in productBrowsingActivity.

- The items which don't contain Wikidata ID would work as before i.e onClicking these items user would be taken to productBrowsingActivity to browse products.

## Related issues and discussion
#506 
 
 ## Screen-shots, if any

wikilink

informationwikidata

**Wikipedia page opened in CustomTab:**

wikipedia

@teolemon @Karljoones @policorn please review this PR :).

### CODE REVIEW

**Comment by Shubham2320** [comment]
The travis-ci test passed before this time it  failed just because 
The job exceeded the maximum time limit for jobs, and has been terminated.

**Comment by Shubham2320** [comment]
@Karljoones thanks. Now I too think the same I'll make the changes. :)

**Comment by teolemon** [comment]
I would probably rename it: "Going further" or "Explore", rather than mentionning Wikidata that will be only one of the sources, and more a middleman than a destination.
It would put "Wikidata data" at the bottom, small and grey (as a footnote)

**Comment by teolemon** [comment]
Can we solve this the conflicts and merge this one ?

**Comment by Shubham2320** [comment]
@teolemon I've to make some Ux changes as suggested, I'll do that by tomorrow and then solve the conflicts too.

**Comment by teolemon** [comment]
@Shubham2320 I'm meeting some Wikipedia/Wikidata contributors from Albania on Saturday. I'll try to demo them the feature. :)

**Comment by Shubham2320** [comment]
@Karljoones I've made some Ux changes please review this one.

**Comment by Shubham2320** [comment]
@Karljoones please review I've made some changes.

**Screenshot:**

**Comment by teolemon** [comment]
@Karljoones

**Comment by Karljoones** [comment]
I like it, it's simple and gives the information that the user needs. I feel that this could be expanded in the future so that is also awesome

**Comment by teolemon** [comment]
merging. Thanks a lot @Shubham2320

**Pull request merged**
