### PR TITLE
Closes #1053: Corrects alerts for no connectivity

### LINKED ISSUE #1053: Wrong message display when connectivity is lost during search.
**Checklist**
- [x] Bug Report - The issue you are reporting might be there already. Please search for the [issues tracker](https://github.com/openfoodfacts/openfoodfacts-androidapp/issues) before creating or reporting an issue.
- [x] Before reporting, please ensure (if you can) that you have tested it with the latest (dev) version of the software.
- [x] Don't forget to tag your issue, it makes it easier to discover.
**Summary:** 

When after loading the search results, if connectivity is lost, the app shows that the product doesn't exist in the OpenFoodFacts database. However, there should be a message showing no internet connection rather than the message that the product doesn't exist.

**Steps to reproduce:** 
1. Search for an item
2. Turn off connection
3. Click on any of the search results.

**Expected behaviour:** 
The app should display the correct behaviour i.e show no connectivity.

**Observed behaviour:** 

No such product message is shown.

**Screenshots:** 
28642901_1613503248737652_626461977_o

### PR DESCRIPTION
**Pull request by samagra14**
## Description

This PR removes the wrong alert dialog and replaces it with a more accurate connectivity check. Besides I have removed a lot of redundant boiler plate code.

## Related issues and discussion
#1053 
 
 ## Screen-shots, if any
 NA (All the existing layouts are used)
 ## Checklist
 
Make sure you've done all the following (You can delete the checklist before submitting)
 
 - [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.
 - [x] Code is well documented
 - [x] All user-visible strings are made translatable
 - [x] Code passes Travis builds in your branch
 - [x] If you have multiple commits please combine them into one commit by squashing them.
 - [x] Read and understood the contribution guidelines .

### CODE REVIEW

**Comment by samagra14** [comment]
@Karljoones @teolemon  Please have a look here.

**Comment by Karljoones** [comment]
Please provide screenshots with any PRs that have any form of layout changes.

**Comment by samagra14** [comment]
@Karljoones there has been no layout change. The following layout : 
28584474_1611570842264226_647152436_o
is repeated several times in the codebase. To remove redundancy I have just made a seperate layout file for the recurring layout and included it in the original one via ` <include layout="layout.xml">` tag.

**Comment by Karljoones** [comment]
I am having another look at this and think that it might be best to just show a dialog to the user explaining why they can not open the recipe rather than take them away from the list. Giving them the option to dismiss the dialog and still be on the list would be best, they can dismiss it, reconnect and then try again.

**Comment by samagra14** [comment]
@Karljoones So should I replace this with an alert dialog that shows the message to connect to the internet ?

**Comment by ManavPoddar** [comment]
@Karljoones, @samagra14   there's one more issue here. If we have loaded the complete list once,  then it doesn't matter whether we have internet connection or not. If we go to menu and then again to the categories page, it will load immediately since our list is already loaded. But after putting the internet check, we cant access the list because of the "check your connection" dialog page which appears if we dont have an internet connection.

Steps to reproduce:-
Open categories -> after it loads go to menu->switch off the internet->categories (earlier the list loaded although we didnt have a internet connection since it was already loaded once)


In my opinion we should add a check for whether the recycler view is empty or not rather than the internet check. This would enable us to view the list even if the internet is not working. Also it would generalize the case of  having some issue with the category list.

**Comment by Karljoones** [comment]
Yeah. It might be best to inform the user that they are not connected, and give them the option to try again or cancel. Basically what you have, but in a dialog.

**Comment by samagra14** [comment]
@Karljoones I have made the changes. Now this alert pops up when the user is not connected to the internet : 
28755339_1615489808538996_1959397605_o

**Comment by samagra14** [comment]
@Karljoones This should work.

**Comment by samagra14** [comment]
@Karljoones This should work.
28822121_1615987885155855_1105433796_o

**Comment by Karljoones** [comment]
Looks good to me 👍 Now, could you have a look at resolving the conflicts?

**Comment by samagra14** [comment]
@Karljoones @teolemon 
Please merge, I have resolved merge conflicts.

**Comment by samagra14** [comment]
@Karljoones @teolemon Please merge this or else merge conflicts will arise again.

**Comment by policorn** [comment]
Hi @samagra14, I've tested your PR merging master (up to 7bdd5e9 commit), I found that enabling airplane mode after performing a successful search keeps the loading animation going on, not sure if this PR was also aiming to fix that behavior. 

I've used a Nexus 6 emulator API 22: 

pr1054

**Comment by samagra14** [comment]
@policorn Hi. Actually, this PR was not intended to solve the above issue. However I will resolve it in the same PR. Thanks @policorn.

**Comment by policorn** [comment]
Great, thanks @samagra14! We'll wait for that fix

**Comment by Karljoones** [comment]
Poke @samagra14

**Comment by samagra14** [comment]
@Karljoones @teolemon I guess this implementation was shifted to a common ProductBrowsingListActivity.java file and the existing fragment was removed. I have made the relevant changes in ProductBrowsingActivity.java. Please have a look.

**Comment by gulzar1996** [comment]
I think showing a dialog for internet dis-connectivity is a bad UX as it disturbs the user when he/she is navigating the app. Instead we can implement something like this. [Library Link](https://github.com/iammert/StatusView).
Your views @Karljoones @samagra14 ?

art

**Comment by Karljoones** [comment]
@gulzar1996 this is when the user clicks on the item, even if that status view was implemented, we would need _some_ feedback for the user if they click on an item in the list

**Comment by Karljoones** [comment]
@samagra14 can you do a final check of the conflicts so we can merge this?

**Comment by samagra14** [comment]
@Karljoones @teolemon 
I have resolved the conflicts. Please merge.

**Comment by Karljoones** [comment]
Merged, thanks @samagra14

**Pull request merged**
