### PR TITLE
Addressing #1897: changed the Sign Up buttom to a link

### PR DESCRIPTION
**Pull request by schokotets**
## Description
Changed "Sign up" button to "Sign up" link/TextView.
For the U in Sign Up to be uppercase, the translations would need to be changed

## Related issues and discussion
#1897
 
 ## Screenshot
| old | new |
| ---- | ---- |
| old layout | new layout |

### CODE REVIEW

**Comment by teolemon** [comment]
How about we turn both in buttons, with a different color perhaps ?

**Comment by teolemon** [comment]
(I'm concerned about conversion, and "clickability")

**Comment by schokotets** [comment]
will the changes be merged?

**Comment by PrajwalM2212** [comment]
@teolemon Shall I merge this PR.  Even i am worried about coversion. Earlier the signup button was big and more appealing to the eyes. 
Instead we can maybe create a in app signup.

**Comment by schokotets** [comment]
Its appealingness was the problem of the Sign Up button. I don't know about the implementation of the sign up process, and would like to look into it, but would suggest merging this PR as a temporary fix.

**Comment by teolemon** [comment]
fair enough. merging then :-)

**Comment by teolemon** [comment]
Thanks a lot @schokotets :-)
Congrats on your first PR for Open Food Facts 🍾

**Pull request merged**
