### PR TITLE
build: only build html docs if merged

### PR DESCRIPTION
**Pull request by VaiTon**

### CODE REVIEW

**Review by teolemon — APPROVED** [review]
mmh… for the chmod, there was a good reason for it, but I can't find it

**Comment by teolemon** [comment]
https://github.com/openfoodfacts/openfoodfacts-androidapp/commit/1fbd64213f622c0119db281053c9731bb7412f9e

**Comment by VaiTon** [comment]
> mmh… for the chmod, there was a good reason for it, but I can't find it

We can leave it if you prefer. No big deal.

**Comment by teolemon** [comment]
that's ok with me as you did, merging

**Pull request merged**
