### PR TITLE
Fix additives explorer UI and search

### PR DESCRIPTION
**Pull request by PrajwalM2212**
#2176 

Improve additives UI and fix search.
screenshot_1548952202

### CODE REVIEW

**Comment by teolemon** [comment]
```
2019-02-01 17:42:27.789 31457-31457/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: openfoodfacts.github.scrachx.openfood, PID: 31457
    java.lang.ArrayIndexOutOfBoundsException: length=1; index=1
        at openfoodfacts.github.scrachx.openfood.views.AdditivesExplorer$1.onQueryTextChange(AdditivesExplorer.java:155)
        at android.support.v7.widget.SearchView.onTextChanged(SearchView.java:1180)
        at android.support.v7.widget.SearchView$10.onTextChanged(SearchView.java:1714)
        at android.widget.TextView.sendOnTextChanged(TextView.java:9754)
        at android.widget.TextView.setText(TextView.java:5733)
        at android.widget.TextView.setText(TextView.java:5571)
        at android.widget.EditText.setText(EditText.java:122)
        at android.widget.TextView.setText(TextView.java:5528)
        at android.support.v7.widget.SearchView.onActionViewExpanded(SearchView.java:1294)
        at android.support.v7.widget.Toolbar$ExpandedActionViewMenuPresenter.expandItemActionView(Toolbar.java:2396)
        at android.support.v7.view.menu.MenuBuilder.expandItemActionView(MenuBuilder.java:1348)
        at android.support.v7.view.menu.MenuItemImpl.expandActionView(MenuItemImpl.java:810)
        at android.support.v7.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:978)
        at android.support.v7.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:963)
        at android.support.v7.widget.ActionMenuView.invokeItem(ActionMenuView.java:624)
        at android.support.v7.view.menu.ActionMenuItemView.onClick(ActionMenuItemView.java:150)
        at android.view.View.performClick(View.java:6597)
        at android.view.View.performClickInternal(View.java:6574)
        at android.view.View.access$3100(View.java:778)
        at android.view.View$PerformClick.run(View.java:25885)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6718)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

**Comment by teolemon** [comment]
Still crashing here

**Comment by PrajwalM2212** [comment]
@teolemon This may take some time to arrive at the correct solution as it wont crash on both my mobile and emulator. But I think it was due to 
screen shot 2019-02-01 at 10 40 29 pm

Also does crash happen in categories explorer ?

**Comment by teolemon** [comment]
No, it doesn't.

**Comment by PrajwalM2212** [comment]
@teolemon Based on the error log `toLowerCase().split("- ")[1]` only this could give `java.lang.ArrayIndexOutOfBoundsException` may be due to a outlier. But now I have put a guard to it.

**Comment by teolemon** [comment]
Looks good. Merging. Thanks @PrajwalM2212

**Pull request merged**
