### PR TITLE
fixes #1152 Made CommonActivity to Show list of products and made additive clickable.

### LINKED ISSUE #1152: In ProductActivity Additives, Ingredients can be made clickable.
In ProductActivity Additives can be made clickable and we can browse products containing these parameters.

### LINKED ISSUE #1164: Missing space in offline screen
image
Sorry,something >>> Sorry, something

### PR DESCRIPTION
**Pull request by Shubham2320**
## Description

- Removed SearchProductResultsFragment as we now have a common Activity to show the list of products.

- Changed the name of BrandActivity to ProductBrowsingListActivity which would be used to show the list of products.

- Made additives clickable.

## Related issues and discussion
closes #1152 
closes #1164
 
 ## Screen-shots, if any
 
additive

additivelist

### CODE REVIEW

**Comment by PrajwalM2212** [comment]
@Shubham2320  Let this be the final state of SearchProductResultsFragment . I will add search by label, categories and Emb Code to it.

**Comment by Shubham2320** [comment]
😄 Sure @PrajwalM2212

**Comment by PrajwalM2212** [comment]
@teolemon @Karljoones It seems all searches will be handled by one activity . 
Can you review and merge this pull request as no development can be made on product browsing issues until decision is taken on this pull request.

**Comment by PrajwalM2212** [comment]
Thanks @Karljoones  .

**Comment by Shubham2320** [comment]
Thanks @Karljoones 😄

**Pull request merged**
