### PR TITLE
Translation refresh

### PR DESCRIPTION
**Pull request by teolemon**
Refresh of the pot and po files

2 caveats:
1 - something with the units_array
```pierreslam$ a2po export
   [created] locale/arrays.pot
   [updated] locale/strings.pot
             - Warning: The array "units_array" contains items that can't be processed (reason: empty resources not supported) - the array will be incomplete
```
2 - a2po import needed to convert back into string files for actual use.

### CODE REVIEW

**Comment by herau** [comment]
@teolemon is it ready to merge ?

**Comment by teolemon** [comment]
Yes. I haven't imported the changes back to the xml files tough.

**Comment by teolemon** [comment]
I've refreshed the XML files.

**Comment by teolemon** [comment]
added romanian and italian

**Comment by teolemon** [comment]
Synced in master. There's a merge conflict to fix in app/src/main/res/values-fr/strings.xml

**Comment by teolemon** [comment]
Can it be merged ? @herau ?

**Pull request merged**
