### PR TITLE
Fixed #304 : Notification to propose sending offline products that need to be sent (rebased)

### LINKED ISSUE #304: Notification to propose sending offline products that need to be sent
When (Wifi) network is detected, add a notification to propose sending offline products that need to be sent.

### PR DESCRIPTION
**Pull request by ross-holloway94**
Supercedes #1398 , rebased on master.

Many thanks @PrajwalM2212 .

### CODE REVIEW

**Comment by PrajwalM2212** [comment]
@ross-holloway94  Sorry for the touble . I will fix it .

**Comment by PrajwalM2212** [comment]
It seems i cannot do changes on this PR

**Comment by ross-holloway94** [comment]
@PrajwalM2212 it's a merge conflict problem. I will fix in a second, don't worry :)

**Comment by PrajwalM2212** [comment]
I will do the rebase or fix conflicts of my PR from next time . Otherwise i wont get any credicts for the hours of work i put in .☺

**Comment by ross-holloway94** [comment]
@prajwalM2212 That's why I tagged your PR and tagged you, wasn't intending any plagarism. But ok, no problem

**Comment by PrajwalM2212** [comment]
@ross-holloway94 It really doesnt matter as far as OFF benifits from it but if my contributions show up on the contributions page it would really help me . Companies see open source contributions as a proof of experience in working in real world software . So it would help me if my contributions show up on my contributions page.

**Pull request merged**
