### PR TITLE
Open Beauty Facts - Branch

### PR DESCRIPTION
**Pull request by teolemon**
- I just suffixed every string that needs to be changed with _obf. Everything is still commented out.
- I added the Open Beauty Facts logo

### CODE REVIEW

**Comment by teolemon** [comment]
Is it possible to add commented out lines or will it create issues ?

**Comment by herau** [comment]
why not create a fork for obf instead of only one repo for two apps ?

**Comment by teolemon** [comment]
Maintenance efforts.

**Comment by herau** [comment]
@teolemon and using another branch ?

**Comment by teolemon** [comment]
Well this is a branch (obf-start) :-)
My point is that constantly rebasing the branch might be a pain.

**Pull request closed without merging**
