### PR TITLE
Fix #2606: user should be redirected to edit mode after login

### LINKED ISSUE #2552: Serving size is only in g/mg/ug
**Summary:**

In the Nutrition Facts tab, when adding the 'Serving size' value, you can only select g/mg/ug. There should be options for l/ml as well (in the case of beverages)

**Device and Android version:**

Latest Android version of the app (not beta)

### LINKED ISSUE #2601: Issue with the portion checker on new empty product
image

### LINKED ISSUE #2603: Version 3.1.2 requires serving size
**Checklist**
- [x] Bug Report - The issue you are reporting might be there already. Please search on the [issues tracker](https://github.com/openfoodfacts/openfoodfacts-androidapp/issues) before creating or reporting an issue.
- [x] Before reporting, please ensure (if you can) that you have tested it with the latest (dev) version of the software.
- [x] Don't forget to tag your issue, it makes it easier to discover.
**Summary:** 
Version 3.1.2 does not accept to save a new product: it complains about an empty serving size or with a 0 value. It should not expect to not have anything entered.

**Steps to reproduce:** 
Add a new product by scanning its barcode, add at least one photo, but leave the serving size empty.

**Expected behavior:** 
The app should not require a serving size.

**Observed behavior:** 
The app complains about an empty serving size if left empty or a positive number serving size if a 0 was entered.

### LINKED ISSUE #2606: The user should be redirected to edit mode after login
1. The user click on "Add Nutrition facts to compute..."
2. he signs in
3. He is redirected to the view mode but He should be redirected to the edit mode

### LINKED ISSUE #2620: Nutrition Facts are not correctly displayed on all products
image
https://barcode.tec-it.com/en/EAN13?data=5400101047594

### PR DESCRIPTION
**Pull request by deniger**
Several fixes:
 - the user is redirected to edit mode / Your contributions after login
 -  The main menu is updated after login/logout actions
 - Refactor login methods in BaseActivity
 - Fix #2601: Issue with the portion checker on new empty product  
 - Fix #2603 as duplication of #2601
 - Fix #2552: Serving size does not have mL/L
 - Fix #2620

Tests done for #2552: 
if the serving size is in ml or l, the Overview and Nutrition tab will use ml instead of g

image

image

### CODE REVIEW

**Comment by teolemon** [comment]
arf, merge conflict

**Comment by teolemon** [comment]
image

**Comment by teolemon** [comment]
(Before any portion, the website displays per 100g as well)
https://fr.openfoodfacts.org/produit/3217690055624/oasis-sirop-mangue-pomme

**Comment by teolemon** [comment]
Imputing 75cL doesn't change anything. Now adding a portion…

**Comment by deniger** [comment]
The serving size unit is used to determine the unit. I don't how to do otherwise....


---- On Fri, 10 May 2019 14:35:54 +0200 notifications@github.com wrote ----



Imputing 75cL doesn't change anything. Now adding a portion…

**Comment by teolemon** [comment]
image
Little mismatch between portions if 100mL as a portion @stephanegigandet @deniger

**Comment by teolemon** [comment]
Yup, it was more a memento for @stephanegigandet since we could probably be smarter about it server side. 
The PR looks good to merge.

**Pull request merged**
