### PR TITLE
Fixed #461 : Include timestamp in history

### LINKED ISSUE #461: Include timestamp in history
Let the person know when he/she last scanned the product.

### PR DESCRIPTION
**Pull request by PrajwalM2212**
## Description

Included timestamp in history

## Related issues and discussion
#461 
 
 ## Screen-shots, if any
 
 
timestamp

### CODE REVIEW

**Comment by PrajwalM2212** [comment]
@l-o-b-s-t-e-r   But it is according to the mocks  by @teolemon . Refer the issue for more info .

**Comment by PrajwalM2212** [comment]
@l-o-b-s-t-e-r  Thanks for the suggestion . 
timestamp1

**Comment by teolemon** [comment]
How about something like 15 minutes ago, 5 hours ago, 5 days ago ?
And perhaps a tiny barcode icon next to the barcode, a tiny clock/history next to the barcode
And removing the share icon, and replacing it by a color dot for the Nutriscore ?

**Comment by PrajwalM2212** [comment]
I have added time as you desired.
I have also added icon of barcode and clock/history as you desired.
timestamp3

Removing the share icon, and replacing it by a color dot for the Nutriscore is another issue #840. We will solve it there.

**Comment by Karljoones** [comment]
Hi @PrajwalM2212 thanks for the work, however, could you make the barcode and the clock icon the same size? It looks like the clock is a larger icon. 

And we are not working on the share icon in this pull request, could you make sure that you do not edit the original icon? It looks like the scaling was changed...

**Comment by PrajwalM2212** [comment]
Share icon edit was by mistake , I have made it right again.
tstamp

**Comment by Karljoones** [comment]
Thank you, @PrajwalM2212, could you make the other changes too and then we can review the PR again?

**Comment by PrajwalM2212** [comment]
The clock icon comes from android itself and cannot be changed . The only workaround is to increase size of barcode . Do you want this change ?
tstamp2

**Comment by teolemon** [comment]
Can we perhaps get the same icon as the History one in the menu ?

**Comment by PrajwalM2212** [comment]
I will look into it .

**Comment by PrajwalM2212** [comment]
@teolemon  I have set the same icon as the one in the menu . I had to create a new drawable as the one used in menu was blue in colour.

time_stamp

**Comment by Karljoones** [comment]
Merged, thanks @PrajwalM2212!

**Pull request merged**
