### PR TITLE
Fix #2187 Crash in the product page in the OBF flavor and new issue with Question

### LINKED ISSUE #2187: Crash in the product page in the OBF flavor
```2019-02-01 18:25:50.870 8840-8840/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: openfoodfacts.github.scrachx.openbeauty, PID: 8840
    java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.fasterxml.jackson.databind.JsonNode.toString()' on a null object reference
        at openfoodfacts.github.scrachx.openfood.network.OpenFoodAPIClient$3.onResponse(OpenFoodAPIClient.java:233)
        at retrofit2.ExecutorCallAdapterFactory$ExecutorCallbackCall$1$1.run(ExecutorCallAdapterFactory.java:70)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6718)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
2019-02-01 18:25:50.928 910-1347/? E/InputDispatcher: channel '49aa0cc openfoodfacts.github.scrachx.openbeauty/openfoodfacts.github.scrachx.openfood.views.MainActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
2019-02-01 18:25:52.896 12467-12467/openfoodfacts.github.scrachx.openbeauty E/RecyclerView: No adapter attached; skipping layout```

### PR DESCRIPTION
**Pull request by deniger**
## Related issues and discussion
+ Fix #2187 Crash in the product page in the OBF flavor 
+ Fix issue if not question found (java.lang.NullPointerException: The mapper function returned a null value)

### CODE REVIEW

**Comment by teolemon** [comment]
Also @raphael0202 @deniger can we ensure only logged in users can answer / see questions  (perhaps see, and ask for login to answer, but that's a bit shady)

**Comment by deniger** [comment]
I can add this to this PR... :)

**Comment by deniger** [comment]
> 
> 
> Also @raphael0202 @deniger can we ensure only logged in users can answer / see questions (perhaps see, and ask for login to answer, but that's a bit shady)

Done in last commit.
Something to review: it seems that the method `SummaryProductFragment#showProductQuestion`  is called twice

**Comment by teolemon** [comment]
Small conflict to merge.
Is `import org.apache.commons.lang3.StringUtils;` still imported/needed ?

**Comment by teolemon** [comment]
otherwise, good to merge

**Comment by deniger** [comment]
@teolemon everything should be ok now
StringUtils is used in a new method

**Comment by teolemon** [comment]
Merging @deniger

**Pull request merged**
