### PR TITLE
Closes #1253: Fix nutrition facts layout

### LINKED ISSUE #1253: Nutrition Facts layout not symmetrical and hides values
**Checklist**
- [x] Bug Report - The issue you are reporting might be there already. Please search on the [issues tracker](https://github.com/openfoodfacts/openfoodfacts-androidapp/issues) before creating or reporting an issue.
- [x] Before reporting, please ensure (if you can) that you have tested it with the latest (dev) version of the software.
- [x] Don't forget to tag your issue, it makes it easier to discover.

**Summary:** 
In the nutrition facts, the layout of the table being created is not correct and the values go out the screen if the text is long.

**Expected behavior:** 
Symmetrical table which is readable should have been displayed and values shouldn't go out of the view.

**Observed behavior:** 
Table not properly generated.

**Screenshots:** 
screenshot_20180315-230407

### PR DESCRIPTION
**Pull request by huzaifaiftikhar**
## Description
Fixes the layout of the nutrition facts table. All the values are properly displayed now. Also added a string in _strings.xml_ as it was missing and was causing build errors.

## Related issues and discussion
Fixes #1253 
 
 ## Screen-shots, if any
screenshot_20180315-235832

 
 ## Checklist
 
Make sure you've done all the following (You can delete the checklist before submitting)
 
 - [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.
 - [x] Code is well documented
 - [x] Include unit tests for new functionality
 - [x] All user-visible strings are made translatable
 - [x] Code passes Travis builds in your branch
 - [x] If you have multiple commits please combine them into one commit by squashing them.
 - [x] Read and understood the contribution guidelines.

### CODE REVIEW

**Comment by huzaifaiftikhar** [comment]
@Karljoones Thanks for such a quick review :slightly_smiling_face:  Although the Travis build is still in progress.

**Comment by Karljoones** [comment]
@huzaifaiftikhar that's why i haven't merged it ;)

**Comment by teolemon** [comment]
Hold my beer, since we're soon going to introduce a second table for dehydrated products :-)

**Comment by jaztriumph** [comment]
@huzaifaiftikhar @Karljoones travis build is failing because of  exceeding the time limit. I am seeing this is happening a lot. I think we need to upgrade our .travis.yml file. we can refer [this](https://stackoverflow.com/questions/45817256/how-to-avoid-the-job-exceeded-the-maximum-time-limit-for-jobs-and-has-been-ter)

**Comment by huzaifaiftikhar** [comment]
@teolemon Where will we place the second table? Or will the second table replace this one? 
@jaztriumph I agree with you. The travis build is failing often due to this reason.

**Comment by teolemon** [comment]
It will be a third column (and potentially a fourth). I'll outline changes on the API when they are live.

Merging for now. Thanks @huzaifaiftikhar

**Pull request merged**
