### PR TITLE
Closes #518: OFF and OBF logos are in the wrong languages 

### LINKED ISSUE #518: the OFF and OBF logos are in the Wrong languages
The Open Beauty Facts logo has the English tagline, regardless of the language
The Open Food Facts logo has the French tagline, regardless of the language

### PR DESCRIPTION
**Pull request by huzaifaiftikhar**
## Description
- I have used a logo without tagline and a TextView below it to show the slogan in the HomeScreen. The TextView is translatable and hence changes as the user switches the locale.
- In the splash activity, we used drawable as a background in styles which was static. Now I have created a new layout for splash activity. However, this is not as visible as it was earlier as this activity is switched with another activity instantly and the layout is not visible. It is only visible when we open the application for the first time (fresh install or after data clear, basically during taxonomies download) as data is being downloaded at that time.
## Related issues and discussion
Fixes #518
 
 ## Screen-shots, if any
**This is how the home screen logo will change depending upon the locale.** 
videotogif_2018 04 07_15 48 28

**This is how the splash screen looks.**
videotogif_2018 04 01_21 15 01

 ## Checklist
 
Make sure you've done all the following (You can delete the checklist before submitting)
 
 - [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.
 - [x] Code is well documented
 - [x] Include unit tests for new functionality
 - [x] All user-visible strings are made translatable
 - [x] Code passes Travis builds in your branch
 - [x] If you have multiple commits please combine them into one commit by squashing them.
 - [x] Read and understood the contribution guidelines.

### CODE REVIEW

**Comment by huzaifaiftikhar** [comment]
@teolemon I need your opinion on this one.

**Comment by teolemon** [comment]
Can we add the tagline using a translatable string if the translated logo doesn't exist ?

**Comment by huzaifaiftikhar** [comment]
Yes, we can add a translatable string below the logo if translatable logo doesn't exist. 
Can you also suggest what to do with the splash​ screen?

**Comment by teolemon** [comment]
The splash screen could be without the tagline. Or even rotate a couple of translations of the slogan while the app is loading (to show the project is international, ideally in very different languages like Russian, Chinese, Hindi, English…)

**Comment by huzaifaiftikhar** [comment]
@teolemon This seems a nice idea! I will try to implement this xD

**Comment by huzaifaiftikhar** [comment]
@teolemon I have created a splash screen as per the idea proposed by you. The text is a little blurred in the gif however on actual device it looks fine. I will send a new commit after getting the designed approved.
videotogif_2018 03 31_02 07 30
How does this look? :slightly_smiling_face:

**Comment by huzaifaiftikhar** [comment]
Updated Splash Screen 
videotogif_2018 04 01_21 15 01

**Comment by teolemon** [comment]
We're going to make a new release soon. How ready is the feature ?

**Comment by huzaifaiftikhar** [comment]
@teolemon In few hours from now xD

**Comment by teolemon** [comment]
Can you rebase on latest trunk ? It should fix the build.

**Comment by huzaifaiftikhar** [comment]
@teolemon Done :slightly_smiling_face:

**Comment by Karljoones** [comment]
Merged, thanks @huzaifaiftikhar

**Comment by Chomusuke12345** [comment]
Hey @huzaifaiftikhar, 
Something went wrong with the build.

TravisCI finished with status `errored`, which means the build failed because something unrelated to the tests, like a problem a dependency or the build process itself.

**Pull request merged**
