### PR TITLE
Fix #2086 propose a new way to delete item on swipe

### LINKED ISSUE #2086: Trash icon visible after swiping in History section
**Summary:** 

In the history section, the trash icon used to delete an item is visible even after deleting the item.

**Steps to reproduce:** 

Go to History section from Navigation Drawer. Swipe any item to the left and click the trash icon visible on the right. The item will get deleted but the trash icon will be still visible.

**Expected behavior:** 

After clicking the trash icon, it should be gone.

**Observed behavior:** 

The trash icon found by swiping the item to the left is visible even after deleting the item.

**Device and Android version:** 

Model - Mi Redmi Note 5
Android version - Android Oreo (8.1)
ROM - Custom

**Screenshots:** 

whatsappvideo20190111at84

### PR DESCRIPTION
**Pull request by deniger**
## Description
To  fix #2086 Trash icon visible after swiping in History section, the swipe behavior is refactored.

delete

### CODE REVIEW

**Comment by teolemon** [comment]
I would make the red more standard, and the trash icon white (possibly) ?

**Comment by teolemon** [comment]
(I'm not suggesting to change the swipe direction)
image

**Comment by deniger** [comment]
Ok will change the color/icon

**Comment by brandenfung** [comment]
> Ok will change the color/icon

Maybe something along the lines of material red (#f44336)?

**Comment by deniger** [comment]
Ok. I will just search for this color code ;)


---- On Sun, 07 Apr 2019 13:25:36 +0200 notifications@github.com wrote ----



Ok will change the color/icon

Maybe something along the lines of material red (#f44336)?

**Comment by deniger** [comment]
with icon + background image:
image

Sorry, but I include a new bugfix in this PR: I noticed that if a user starts to scan from the History screen and navigates back to the history screen, the new products were not displayed -> Fixed.

**Comment by teolemon** [comment]
@brandenfung good to merge ?

**Pull request merged**
