### PR TITLE
Fixes #934: Improved UI of history list item

### LINKED ISSUE #934: Improve UI of History list item
Mobile phone Vivo Y28(screen size 4.7")

**How it is looking right now:**

screenshot_2018-02-26-16-12-45

**Expected:**

screenshot_2018-02-26-16-01-41

### PR DESCRIPTION
**Pull request by shivanshsoni**
#solved #934 

**After changing**
screenshot_2018-02-26-16-01-41

### CODE REVIEW

**Comment by teolemon** [comment]
@shivanshsoni Can you remove the share icons while we're at it ? We need to take all the available space.

**Comment by shivanshsoni** [comment]
@teolemon I think it is providing an additional feature of sharing and we have already provided all the details along with share feaure.

**Comment by shivanshsoni** [comment]
If you want I can remove share button. Just give me 5 minutes

**Comment by shivanshsoni** [comment]
screenshot_2018-02-26-17-12-53

**Comment by shivanshsoni** [comment]
kooking something like this without share button

**Comment by policorn** [comment]
Hi @teolemon, if it's ok with you let me know and I test it

**Comment by teolemon** [comment]
I would have removed the whitespace on the right and left. Let's test and merge, and keep iterating.

**Comment by policorn** [comment]
Thanks @shivanshsoni! Merged

**Pull request merged**
