### PR TITLE
fixes related to #2746 + barcode 1 can be used

### PR DESCRIPTION
**Pull request by deniger**
+ #2746 selectable images are sorted from newer to older
+ #2746 add the language code in the language spinner

### CODE REVIEW

**Comment by teolemon** [comment]
nice one for the permissions. that was bugging me. 
is there some code missing ?

**Comment by deniger** [comment]
Not I believe there are too much code there :)
I'll test it again




---- On Tue, 18 Jun 2019 15:51:49 +0200 Pierre Slamich <mailto:notifications@github.com> wrote ----


nice one for the permissions. that was bugging me.
 is there some code missing ?

**Comment by teolemon** [comment]
I meant the language selection + image sorting: I don't see the matching code changes

**Comment by deniger** [comment]
sorry a buggy push...

**Pull request merged**
