### PR TITLE
Notification issues [Needs runtime testing]

### LINKED ISSUE #1702: (26 crash reports) android.app.RemoteServiceExceptiona
android.app.RemoteServiceExceptiona : 
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:2095)
  at android.os.Handler.dispatchMessage (Handler.java:109)
  at android.os.Looper.loop (Looper.java:166)
  at android.app.ActivityThread.main (ActivityThread.java:7367)
  at java.lang.reflect.Method.invoke (Method.java)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:469)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:963)

### PR DESCRIPTION
**Pull request by ross-holloway94**
## Description

Following potential solutions at https://stackoverflow.com/questions/25317659/how-to-fix-android-app-remoteserviceexception-bad-notification-posted-from-pac .
If anybody has a Huawei I would appreciate if they could test this PR, specifically connecting to wifi when offline products are waiting to be uploaded.

## Related issues and discussion
Fixes #1702

### CODE REVIEW

**Comment by ross-holloway94** [comment]
@teolemon There is an answer on the article which suggests it *could* cause the issue

**Comment by ross-holloway94** [comment]
@Karljoones there should be no harm in doing so. I'll leave it up to the team.

**Comment by teolemon** [comment]
Limited connectivity for the next few days (marriage of my best friend). Please take the lead ;)

**Comment by Karljoones** [comment]
Merged, thanks @ross-holloway94, if we notice anything up with it we can sort it

**Comment by ross-holloway94** [comment]
@Karljoones great, ping me on Slack if you do.
@teolemon Have a nice time :)

**Pull request merged**
