### PR TITLE
fixes #1108 Make packaging clickable

### LINKED ISSUE #1108: Make packaging clickable on Product Page
One of the killer things on Open Food Facts web version is being able to browse all products of a same packaging by clicking on the packaging field on the product page (eg: Plastic)
It would be great to make the brand field clickable

https://in.openfoodfacts.org/product/8904063200945/haldirams-bhujia

Example with Plastic
https://world.openfoodfacts.org/packaging/plastic
https://world.openfoodfacts.org/packaging/plastic.json

### PR DESCRIPTION
**Pull request by ManavPoddar**
## Description

Now packaging is clickable with Recycler view

## Related issues and discussion
#1108

### CODE REVIEW

**Comment by PrajwalM2212** [comment]
@ManavPoddar A single activity  has been created to handle all searches by @Shubham2320 in https://github.com/openfoodfacts/openfoodfacts-androidapp/pull/1161 . We have decided to add clickables on top of that . I will be adding categories, emb codes and labels.
Can you also make packaging clickable on top of that otherwise there will be conflicts .
.

**Comment by ManavPoddar** [comment]
Yeah sure @PrajwalM2212 , thanks for noticing, I'll fix it soon  :)

**Comment by ManavPoddar** [comment]
fixed this issue in PR #1117

**Comment by Karljoones** [comment]
Is this PR to be closed? That's what I get from your last comment...

**Comment by ManavPoddar** [comment]
yes @Karljoones, i've fixed it in #1117

**Pull request closed without merging**
