### PR TITLE
Re-enabled additives detection for Open Beauty Facts

### LINKED ISSUE #1659: Reenable additives detection for Open Beauty Facts
Reenable additives detection for Open Beauty Facts.

### PR DESCRIPTION
**Pull request by vanshikaarora**
## Description
Enables "additives" for build variant obf

#fixes #1659
## Screen-shots
Screenshot_20190517_132039

### CODE REVIEW

**Comment by vanshikaarora** [comment]
@teolemon @deniger . Can you please help with travis-ci?

**Comment by vanshikaarora** [comment]
Thanks for approving the PR @VaiTon :)

**Comment by teolemon** [comment]
Ok, let's merge anyway. Being able to explore isn't bad, I guess.

**Comment by vanshikaarora** [comment]
Thanks for approving the PR @teolemon :)

**Pull request merged**
