### PR TITLE
Fixes #2611: Added dependencies version in root project

### LINKED ISSUE #2611: Minor gradle refactor
**Summary:**
In Gradle, versions of some dependency are mentioned directly but according to the convention it should be fetched from rootProject.

**Expected behavior:**
Dependencies version must be fetched from the root project.

**Observed behavior:**
Versions of dependencies are directly mentioned in gradle files.

### PR DESCRIPTION
**Pull request by RajaVamsi11**
## Description

Added dependencies version in root project and called from there to the app gradle file.
## Related issues and discussion
Fixes #2611 
 
 ## Checklist
 
Make sure you've done all the following (You can delete the checklist before submitting)
 
 - [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.
 - [x] Code is well documented
 - [x] Include unit tests for new functionality
 - [x] All user-visible strings are made translatable
 - [x] Code passes Travis builds in your branch
 - [x] If you have multiple commits please combine them into one commit by squashing them.
 - [x] Read and understood the contribution guidelines.

### CODE REVIEW

**Comment by RajaVamsi11** [comment]
@teolemon Can you please this PR?

**Comment by RajaVamsi11** [comment]
@teolemon @Karljoones  Can you please review this PR?

**Comment by RajaVamsi11** [comment]
@deniger Can you please review this PR?

**Comment by deniger** [comment]
All good. Thanks  @RajaVamsi11

**Pull request merged**
