### PR TITLE
closes #331 Include the number of products to be sent in the sidebar Offline Mode item

### LINKED ISSUE #331: Include the number of products to be sent in the sidebar "Offline Mode" item
Include the number of products to be sent in the sidebar "Offline Mode" item
https://github.com/mikepenz/Android-ActionItemBadge

### PR DESCRIPTION
**Pull request by Shubham2320**
## Related issues and discussion
Closes #331 
 
Implemented an ActionBar item in OfflineEditFragment which holds the count of saved items waiting to be uploaded online.

 ## Screen-shots, if any
 

Please suggest any more changes, if required :).

### CODE REVIEW

**Comment by teolemon** [comment]
I was referring to the Menu sidebar actually. Also I was thinking of a perfect round.

**Comment by Shubham2320** [comment]
Ohh could you please provide me more details, I'll make changes accordingly.

**Comment by Karljoones** [comment]
This menu item

**Comment by Shubham2320** [comment]
Okay, I am going to send a new PR for that :).

**Pull request closed without merging**
