### PR TITLE
Fix #254 Add commas between allergenic ingredients

### LINKED ISSUE #254: Add commas between allergenic ingredients
screenshot_20161115-140056

### PR DESCRIPTION
**Pull request by naofum**
screenshot_2017-01-09-00-17-04

### CODE REVIEW

**Comment by herau** [comment]
maybe replace by [Chips](https://material.io/guidelines/components/chips.html) soon.

what do you think @teolemon ? maybe also allergens (with different colors according to toxicity)

**Comment by teolemon** [comment]
chips yes, colors: it raises the question of datasource: where does the current one come from ?

**Comment by herau** [comment]
additives are fetched the every time the application is launched (SplashActivity)

**Comment by teolemon** [comment]
I mean: opinions are emitted on additives, but this is not Open Food Facts data.

**Pull request merged**
