### PR TITLE
Fixed #1082: Sync old history entries (Quantity and Nutriscore)

### LINKED ISSUE #1082: Nutriscore not correctly shown in history
image

### PR DESCRIPTION
**Pull request by jaztriumph**
## Description

As in old history database there were no quantity and nutriscore columns, I have added those values when ever user opens the app.

## Related issues and discussion
closes #1082

### CODE REVIEW

**Comment by policorn** [comment]
Hi @jaztriumph, please fix the conflict

**Comment by teolemon** [comment]
Oops, another conflict related to menu changes. Can you fix it so that we can merge ?

@policorn are you ok otherwise ?

**Comment by Karljoones** [comment]
There are a few conflicts that will need to be resolved

**Comment by l-o-b-s-t-e-r** [comment]
Actually it doesn't resolve the issue.

**Comment by jaztriumph** [comment]
@l-o-b-s-t-e-r   yes this should have been done in the upgrade function in `DatabaseHelper` when the schema was upgraded from 5 -> 6 but it wasn't , so the result was many users have already upgraded to schema 6, now if we even write the sync function in `DatabaseHepper` upgrade function it won't sync their database because they are already using schema 6. Another option is that we can upgrade the database schema to 7 and write the sync function in when upgraded to schema 7. @Karljoones if you like the last option I would make the changes accordingly.

**Comment by l-o-b-s-t-e-r** [comment]
"many users have already upgraded to schema 6" - I don't think so, because on the [PlayMarket](https://play.google.com/store/apps/details?id=org.openfoodfacts.scanner&hl=ru) the last update date is 3 Feb 2018

**Comment by jaztriumph** [comment]
@l-o-b-s-t-e-r then lets wait and see what maintainers would say and I will do accordingly.

**Comment by policorn** [comment]
Hi @l-o-b-s-t-e-r @jaztriumph, latest published version is [0.8.2](https://github.com/openfoodfacts/openfoodfacts-androidapp/tree/0.8.2) 2018-03-10 via F-droid (https://f-droid.org/en/packages/openfoodfacts.github.scrachx.openfood/)

**Comment by jaztriumph** [comment]
@Karljoones @policorn please review this PR.

**Comment by jaztriumph** [comment]
@Karljoones what's the status of this PR.

**Comment by teolemon** [comment]
Merged, thanks @jaztriumph

**Pull request merged**
