### PR TITLE
Closes #1110 : Add a contributor tab to products 

### LINKED ISSUE #1110: Add a contributor tab to products
We display the Add date, the last edit date, and the list of contributors

```Product added on September 12, 2013 at 3:19:18 AM CEST by miles67off.
Last edit of product page on March 4, 2018 at 12:53:55 PM CET by kiliweb. 
Product page also edited by babaorome, jacob80, openfoodfacts-contributors, sebleouf, tacite.```

We miss information about contributors to a product.
https://en.wiki.openfoodfacts.org/API#Contributors

### PR DESCRIPTION
**Pull request by PrajwalM2212**
## Description

Adds modification history and states 

## Related issues and discussion
#1110 
 
 ## Screen-shots, if any

### CODE REVIEW

**Comment by PrajwalM2212** [comment]
This PR is still **work in progress** .

**Comment by PrajwalM2212** [comment]
c
screenshot_1523698995

@teolemon  Till now the contributors tab looks like this . I should still add the photos
I have added the modification history .
I have also added the states 
Both states and modifications are clickable .

**Comment by PrajwalM2212** [comment]
screenshot_1523771902

**Comment by teolemon** [comment]
Can you rebase on latest trunk ? It should fix the build.

**Comment by Karljoones** [comment]
@PrajwalM2212 can we remove the comma from the end of the lists and the extra space in front of it?

**Comment by PrajwalM2212** [comment]
I will rebase and fix conflicts .

**Comment by PrajwalM2212** [comment]
@ross-holloway94  Changes made and rebase done .

**Comment by teolemon** [comment]
I'm restarted the failed part of the build.

**Pull request merged**
