### PR TITLE
Fixes #832: Improved camera icon in Product addition form

### LINKED ISSUE #832: Invisible camera icon in the Product addition form
Invisible camera icon in the Product addition form
I've tweaked the colors so it is visible. It probably shouldn't be here ?
image

### PR DESCRIPTION
**Pull request by AbsolutelySaurabh**
## Description

The camera icon was invisible earlier, which has now been improved.

## Related issues and discussion
#832  
 
 ## Screen-shots, if any
screenshot_20180220-223042

### CODE REVIEW

**Comment by huzaifaiftikhar** [comment]
@AbsolutelySaurabh I think the camera icon should have been removed from there. It has no use.

**Comment by PrajwalM2212** [comment]
@teolemon 
screen shot

The text can be changed to "Only one photo is required to add a new product" .

**Comment by Karljoones** [comment]
I agree, this icon should be removed.

@PrajwalM2212 you can create a new issue for this if you think it should be changed :)

**Comment by teolemon** [comment]
Let's close this

**Pull request closed without merging**
