### PR TITLE
Hide layout and reformat code

### LINKED ISSUE #810: Product not found is shown even when the app is searching for products
**Summary:** 

While searching for a product the message "product not found" is shown even while the app is still in searching mode. 

**Steps to reproduce:** 
Search for a product, While the app is searching for a product the "products not found" layout is displayed.

**Expected behavior:** 

The message "product not found should not be displayed".

**Observed behavior:** 

Product not found screen is displayed.

**Screen-shots:** 

videotogif_2018 02 19_21 22 30

### PR DESCRIPTION
**Pull request by huzaifaiftikhar**
## Description
Now search works as desired.

## Related issues and discussion
Fixes #810 
 
 ## Screen-shots, if any
 
videotogif_2018 02 19_21 44 01

 ## Checklist
 
 Please make sure these boxes are checked before submitting your pull request - thanks!
 
 
 
 - [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.
 
 - [x] If you have multiple commits please combine them into one commit by squashing them.
 
 - [x] Read and understood the contribution guidelines .

### CODE REVIEW

**Comment by Shubham2320** [comment]
Hey, @huzaifaiftikhar it's already been fixed in PR #737 please recheck.

**Comment by huzaifaiftikhar** [comment]
@Karljoones Please review.

**Comment by Karljoones** [comment]
@teolemon can you have a look at this? I think it looks ok to merge but want someone else to look at it first

**Comment by teolemon** [comment]
@policorn Can you have a second look ?
Expected behaviour: 
- still displays the "Add product prompt" if no results at the end of the network calls
- doesn't display the "Add product prompt" during network calls

**Comment by policorn** [comment]
Hi @teolemon, verified. Can be merged.

**Comment by teolemon** [comment]
Merged, thanks @huzaifaiftikhar :)

**Pull request merged**
