### PR TITLE
Fixes #2669: Deleted KeepAliveService and removed method using this service

### LINKED ISSUE #2669: Register KeepAliveService in AndroidManifest file
**Summary**
When I inspected the whole project in Android studio it shows this in Android Lint Correctness warnings.
For `KeepAliveService.java`

screenshot from 2019-03-03 19-39-29

As our service is not registered in Manifest file, I am going to make it registered in the manifest file using the `<service>` tag.

### PR DESCRIPTION
**Pull request by RajaVamsi11**
## Description

Registered KeepAliveService in the AndroidManifest file. Activities, Services, and Broadcast receivers should be registered in the AndroidManifets.XML file using the respective tags.

## Related issues and discussion
Fixes #2669

### CODE REVIEW

**Comment by deniger** [comment]
Not sure about the impact of this modification and it seems that it's not used.
The service is only called by the method CustomTabsHelper#addKeepAliveExtra.
But this method is not used.

My suggestion will be to delete this method and delete the service...

**Comment by RajaVamsi11** [comment]
> Not sure about the impact of this modification and it seems that it's not used.
> The service is only called by the method CustomTabsHelper#addKeepAliveExtra.
> But this method is not used.
> 
> My suggestion will be to delete this method and delete the service...

**Comment by deniger** [comment]
It's fine for me...

**Comment by RajaVamsi11** [comment]
@deniger Updated according to the changes requested. Please review once.

**Comment by deniger** [comment]
ok for me. @teolemon  do you remember why this service has been created ?

**Pull request merged**
