### PR TITLE
Fix ssl handshake issues on android 7

### PR DESCRIPTION
**Pull request by huzaifaiftikhar**
**Description**
1. The issue was happening because of `javax.net.ssl.SSLHandshakeException`. To fix this I changed the TLS version to 1.2 since that's the maximum version our backend supports.
2. A complete report for the accepted cipher suites and protocols that we support can be checked at [ssllabs](https://www.ssllabs.com/ssltest/analyze.html?d=ssl-api.openfoodfacts.org)
3. Tested on Android versions 5.0 to 11.0 (including both)

**Closes**
https://github.com/openfoodfacts/openfoodfacts-androidapp/issues/3527

### CODE REVIEW

**Comment by teolemon** [comment]
I'm going to build an APK to get Android 7 users to test it.

**Comment by teolemon** [comment]
@huzaifaiftikhar do you have this issue on building ? Did you refresh your clone recently ?
openfood/models/CategoryDao.java:16: error: cannot find symbol
public class CategoryDao extends AbstractDao<Category, Long> {
                                             ^
  symbol: class Category

**Comment by huzaifaiftikhar** [comment]
> @huzaifaiftikhar do you have this issue on building ? Did you refresh your clone recently ?
> openfood/models/CategoryDao.java:16: error: cannot find symbol
> public class CategoryDao extends AbstractDao<Category, Long> {
> ^
> symbol: class Category

Yup got this on `develop` and `master` branch as well, seems to be some cache that is preserved by GreenDao. Go to Build -> Clean Project to fix this.

**Comment by VaiTon** [comment]
@teolemon did you test this one?

**Review by VaiTon — APPROVED** [review]

**Comment by teolemon** [comment]
Not myself. I'm waiting for @CharlesNepote 's feedback since he owns an Android 7 device.

**Comment by huzaifaiftikhar** [comment]
> Not myself. I'm waiting for @CharlesNepote 's feedback since he owns an Android 7 device.

Or use BrowerStack's [open-source plan](https://www.browserstack.com/open-source)!

**Comment by teolemon** [comment]
I have just applied. 48hr wait to validate the account.

**Comment by teolemon** [comment]
Little merge conflict. I guess we can use the version in Utils ?

**Pull request merged**
