### PR TITLE
fixes #2265 : adds scroll to preferences

### LINKED ISSUE #2265: Add scroll bar to preferences
**Checklist**
- [x] Bug Report - The issue you are reporting might be there already. Please search on the [issues tracker](https://github.com/openfoodfacts/openfoodfacts-androidapp/issues) before creating or reporting an issue.
- [x] Before reporting, please ensure (if you can) that you have tested it with the latest (dev) version of the software.
- [x] Don't forget to tag your issue, it makes it easier to discover.
**Summary:** 

Summarize your issue in one sentence (what goes wrong, what did you expect to happen)
when we open preferences,there is no scroll bar.Adding a scroll bar might be better.

**Steps to reproduce:** 
1.Open the app
2.Go to preferences

**Expected behavior:** 

A scroll bar must be present in preferences.

**Observed behavior:** 

There is no scroll bar.

**Device and Android version:** 
Device is asus 3s max.OS is 7.1.
**Screenshots:**

### PR DESCRIPTION
**Pull request by mustaqmustu**
## Description

Changed preferences.xml as there is no scroll view in it.

## Related issues and discussion

fixes #2265
 
 ## Screen-shots, if any
 
 ## Checklist
 
Make sure you've done all the following (You can delete the checklist before submitting)
 
 - [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.
 - [x] Code is well documented
 - [x] Include unit tests for new functionality
 - [x] All user-visible strings are made translatable
 - [ ] Code passes Travis builds in your branch
 - [ ] If you have multiple commits please combine them into one commit by squashing them.
 - [x] Read and understood the contribution guidelines .

### CODE REVIEW

**Comment by Karljoones** [comment]
Do you have a video of this working?

**Comment by mustaqmustu** [comment]
> Do you have a video of this working?



> Do you have a video of this working?

@Karljoones I think there is alredy a scroll view involved in it..But it is not visible
view

**Comment by PrajwalM2212** [comment]
No change. It is same as before.
Also create a new branch for opening a PR.

**Comment by Karljoones** [comment]
Going to close this off because there were no changes in this.

**Pull request closed without merging**
