### PR TITLE
huge-sonar-pr

### PR DESCRIPTION
**Pull request by teolemon**

### CODE REVIEW

**Comment by VaiTon** [comment]
@teolemon there are no changes

**Comment by teolemon** [comment]
I'm just doing minor changes to trigger build

**Comment by teolemon** [comment]
-v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/openfoodfacts-androidapp/openfoodfacts-androidapp":"/github/workspace" 3888d3:6defc8db142e46feab3cb0e0cd6f6624
Set the SONAR_TOKEN env variable.

**Comment by teolemon** [comment]
weirdly not working

**Pull request closed without merging**
