### PR TITLE
Closes #1178: Added toast for no translations available in allergen list

### PR DESCRIPTION
**Pull request by ManavPoddar**
## Description

Added a toast message to notify the users if no translations are available for alergens
## Related issues and discussion
#1178 
 
 ## Screen-shots, if any
 
screenshot_20180324-012108

### CODE REVIEW

**Comment by ManavPoddar** [comment]
hey @Karljoones , added a toast for no translations available in allergen alert. Kindly review this PR :)

**Comment by Karljoones** [comment]
@teolemon apart from the capitalisation of the string, what do you think of this feature?

**Comment by teolemon** [comment]
Ideally, it would default to letting the user add allergens in English, thus making the message obsolete.
And perhaps - in that case-  adding a little link at the bottom to the Allergen taxonomy page.

"Translate the Allergen taxonomy in your language on the Open Food Facts coordination wiki. Note: you need to be logged in on the main Open Food Facts website to be able to edit"

https://en.wiki.openfoodfacts.org/Global_allergens_taxonomy

**Comment by ManavPoddar** [comment]
Hey @teolemon, so should I add "Translate the Allergen taxonomy in your language on the Open Food Facts coordination wiki. Note: you need to be logged in on the main Open Food Facts website to be able to edit" with the link https://en.wiki.openfoodfacts.org/Global_allergens_taxonomy at the bottom of the page. Also, should I keep or remove the toast message ?

**Comment by Karljoones** [comment]
@ManavPoddar Maybe get rid of the toast and add a view in the middle of the screen with:
> There are no allergen translations available in your language

And then have the text at the bottom

**Comment by ManavPoddar** [comment]
Added a new view and link at the bottom. Also removed the toast message

screenshot_20180331-152103
screenshot_20180331-152053

**Comment by Karljoones** [comment]
Hi @ManavPoddar, a few things the message should be center justified to ensure that it looks like it is in the center of the screen. Also the user does not need to see that link, consider adding a button with just "Visit Open Food Facts". Also it appears that there is an extra bit of whitespace before " Note"

**Comment by ManavPoddar** [comment]
Hey @Karljoones, updated the PR, please have a look :)

**Comment by ross-holloway94** [comment]
@teolemon translations are causing issues again here.

**Comment by teolemon** [comment]
Can you rebase on latest trunk ? It should fix the build.

**Comment by ManavPoddar** [comment]
Yeah sure :)

**Comment by ManavPoddar** [comment]
Hi, there are merge conflicts in all the strings.xml files due to duplicate entries. Is there any simpler way of resolving the conflict rather than opening each string.xml and deleting the duplicate entries?

**Comment by Karljoones** [comment]
Hi @ManavPoddar you could try rebase this, it should resolve the issues with the duplicate entries.

**Comment by Karljoones** [comment]
Hi @ManavPoddar, I am going to close this PR for now. I was looking through the file changes and noticed that it reverts a lot of the translations. For example, it replaces some German text with English text. This should not be the case. I'm sorry :(

**Pull request closed without merging**
