### PR TITLE
Fixes #631 (Added confirmation before logging out)

### LINKED ISSUE #631: Add confirmation step before logging out
Add confirmation step before logging out. This will avoid unvolontary logout. As reported by Qian.

"You're about to log out. Confirm ?"
Yes/No

### PR DESCRIPTION
**Pull request by ManognaMutyala**
## Description

Added confirmation before logging out

## Related issues and discussion
#631

### CODE REVIEW

**Comment by itchix** [comment]
DialogInterface is missing on the import.
R.string.ok and R.string.cencel doesn't exist too.

Can you use `new MaterialDialog.Builder` instead of `AlertDialog.Builder`

**Comment by ManognaMutyala** [comment]
I will make necessary changes @itchix

**Comment by samagra14** [comment]
@ManognaMutyala After every commit, please make sure that you check your Travis build. They are quite easy to correct and require minimal changes. Here it says that something is wrong with R.string.ok . Please also mention the device with which the code was tested.

**Comment by teolemon** [comment]
@ManognaMutyala can you make the fixes for @itchix so that I can merge it ? :)

**Comment by ManognaMutyala** [comment]
I am really sorry for the delay @teolemon !! I will make changes soon!!

**Comment by ManognaMutyala** [comment]
It would look something like this.
https://drive.google.com/file/d/1Blq9MPHgeY9z79qV8omFiphmMt3uMykr/view?usp=sharing

**Comment by teolemon** [comment]
Merging, thanks @samagra14

**Comment by policorn** [comment]
Hi @teolemon; this merge has broken the build in master (missing dependencies) - It's probably fixed by 54d7fd6744075f98e510db66eb87f7382fb909e3 (committed as part of #883)

**Pull request merged**
