### PR TITLE
fix: build test fails

### LINKED ISSUE #3787: map_returnsListOfCorrectlyMappedLabels_SubElementsAreMappedCorrectly FAILED (LabelsWrapperTest.kt:65)
openfood.models.entities.label.LabelsWrapperTest > map_returnsListOfCorrectlyMappedLabels_SubElementsAreMappedCorrectly FAILED
com.google.common.truth.ComparisonFailureWithFacts at LabelsWrapperTest.kt:65

### LINKED ISSUE #3789: toString_returnsProperlyFormattedString FAILED - ProductStateTest.kt:26
openfood.models.ProductStateTest > toString_returnsProperlyFormattedString FAILED
com.google.common.truth.ComparisonFailureWithFacts at ProductStateTest.kt:26

### PR DESCRIPTION
**Pull request by kartikaysharma01**
#### Related issues

Fixes #3787 
Fixes #3789 

#### Screenshots

image

image

### CODE REVIEW

**Comment by teolemon** [comment]
```
openfoodfacts.github.scrachx.openfood.models.entities.additive.AdditivesWrapperTest > map_returnsListOfCorrectlyMappedAdditives FAILED
    com.google.common.truth.ComparisonFailureWithFacts at AdditivesWrapperTest.kt:46

openfoodfacts.github.scrachx.openfood.models.entities.allergen.AllergensWrapperTest > map_returnsListOfCorrectlyMappedSubAllergens_LanguageCode FAILED
    com.google.common.truth.ComparisonFailureWithFacts at AllergensWrapperTest.kt:67

openfoodfacts.github.scrachx.openfood.models.entities.allergen.AllergensWrapperTest > map_returnsListOfCorrectlyMappedSubAllergens_Names FAILED
    com.google.common.truth.ComparisonFailureWithFacts at AllergensWrapperTest.kt:75
```

**Comment by kartikaysharma01** [comment]
> ```
> openfoodfacts.github.scrachx.openfood.models.entities.additive.AdditivesWrapperTest > map_returnsListOfCorrectlyMappedAdditives FAILED
>     com.google.common.truth.ComparisonFailureWithFacts at AdditivesWrapperTest.kt:46
> 
> openfoodfacts.github.scrachx.openfood.models.entities.allergen.AllergensWrapperTest > map_returnsListOfCorrectlyMappedSubAllergens_LanguageCode FAILED
>     com.google.common.truth.ComparisonFailureWithFacts at AllergensWrapperTest.kt:67
> 
> openfoodfacts.github.scrachx.openfood.models.entities.allergen.AllergensWrapperTest > map_returnsListOfCorrectlyMappedSubAllergens_Names FAILED
>     com.google.common.truth.ComparisonFailureWithFacts at AllergensWrapperTest.kt:75
> ```

I think these files are undergoing refactor by @VaiTon. 
@VaiTon Can you please confirm?

**Comment by VaiTon** [comment]
> 
> 
> > ```
> > openfoodfacts.github.scrachx.openfood.models.entities.additive.AdditivesWrapperTest > map_returnsListOfCorrectlyMappedAdditives FAILED
> >     com.google.common.truth.ComparisonFailureWithFacts at AdditivesWrapperTest.kt:46
> > 
> > openfoodfacts.github.scrachx.openfood.models.entities.allergen.AllergensWrapperTest > map_returnsListOfCorrectlyMappedSubAllergens_LanguageCode FAILED
> >     com.google.common.truth.ComparisonFailureWithFacts at AllergensWrapperTest.kt:67
> > 
> > openfoodfacts.github.scrachx.openfood.models.entities.allergen.AllergensWrapperTest > map_returnsListOfCorrectlyMappedSubAllergens_Names FAILED
> >     com.google.common.truth.ComparisonFailureWithFacts at AllergensWrapperTest.kt:75
> > ```
> 
> I think these files are undergoing refactor by @VaiTon.
> @VaiTon Can you please confirm?

I commited something but I finished ref them.

**Comment by kartikaysharma01** [comment]
> I commited something but I finished ref them.

In that case, I will give them another look if the already existing PR fails to close the issue.

**Comment by teolemon** [comment]
@VaiTon @kartikaysharma01 what's the status on that one ?
I'd really like to make the build green again (MBGA)

**Comment by kartikaysharma01** [comment]
> @VaiTon @kartikaysharma01 what's the status on that one ?
> I'd really like to make the build green again (MBGA)

It's clear for review.

**Pull request merged**
