### PR TITLE
New material compliant UI (close #397)

### LINKED ISSUE #397: Improve Main activity UX
- Use SearchView with VoiceSearch button
<br />- Use Material Design light theme
<br />- Remove all menu item and put links in the text 
<br />- Update the scan button with a barcode icon and with a Material design ux (circle button)
<br />
<br />/cc @teolemon

### PR DESCRIPTION
**Pull request by herau**
⚠️  Work in progress

only for UX review with @teolemon

### CODE REVIEW

**Comment by herau** [comment]
screenshot_1483633373


screenshot_1483633376


screenshot_1483633383

**Comment by teolemon** [comment]
image

**Comment by teolemon** [comment]
Conflicts to resolve.
Also, since the Android default for FABs is red, and that is part of the logo's colors, we can color it that way.
image

**Comment by teolemon** [comment]
history still in white image

**Comment by herau** [comment]
screenshot_1484134512

screenshot_1484134510

screenshot_1484134517

screenshot_1484134527

screenshot_1484134535

screenshot_20170111-125136

> @teolemon @itchix Still a scrolling issue in this view because the topbar should be disappear during scrolling down  and only show the tabbar like in [this video](https://storage.googleapis.com/material-design/publish/material_v_10/assets/0B6Okdz75tqQsLXBSOXZjOXVDQTg/patterns-scrolling-techniques_tabs_xhdpi_004.mp4)

**Comment by teolemon** [comment]
How to contribute

**Comment by teolemon** [comment]
<3 <3 <3

**Comment by itchix** [comment]
I'm reviewing it

**Comment by herau** [comment]
@itchix don't hesitate to find the issue in the layout `OpenFoodFacts-androidApp/app/src/main/res/layout/activity_product.xml` for the scrolling ;-)

**Comment by itchix** [comment]
You can merge first? I'll work on it

**Pull request merged**
