### PR TITLE
design: updated icons for obf and off

### PR DESCRIPTION
**Pull request by VaiTon**
image
image
image

### CODE REVIEW

**Comment by VaiTon** [comment]
@teolemon are you comfortable changing the off icon too?

**Comment by stephanegigandet** [comment]
I very much like the OBF icon. I think it would be a great idea to make the OFF icon in the same style (with food products instead of beauty products).

**Comment by teolemon** [comment]
Can we use that as an interim, while someone designs one ?

**Comment by teolemon** [comment]
Ok, let's merge 👍

**Pull request merged**
