### PR TITLE
Fixed WrapperTests

### LINKED ISSUE #3788: map_returnsListOfCorrectlyMappedSubAllergens_LanguageCode FAILED - AllergensWrapperTest.kt:67
openfood.models.entities.allergen.AllergensWrapperTest > map_returnsListOfCorrectlyMappedSubAllergens_LanguageCode FAILED
com.google.common.truth.ComparisonFailureWithFacts at AllergensWrapperTest.kt:67

 openfood.models.entities.allergen.AllergensWrapperTest > map_returnsListOfCorrectlyMappedSubAllergens_Names FAILED
com.google.common.truth.ComparisonFailureWithFacts at AllergensWrapperTest.kt:75

 openfood.models.entities.additive.AdditivesWrapperTest > map_returnsListOfCorrectlyMappedAdditives FAILED
com.google.common.truth.ComparisonFailureWithFacts at AdditivesWrapperTest.kt:46

### PR DESCRIPTION
**Pull request by mrudultora**
#### Related issues
Fixes #3788 

#### Screenshots

img1

img2

img3

### CODE REVIEW

**Comment by VaiTon** [comment]
Ehm.. I don't know... Because you just put the values that we get, but are them correct?

**Comment by mrudultora** [comment]
@VaiTon I think when someone wrote these tests, he would have interchanged the values. I swapped the array index and then it was working fine.

**Comment by naivekook** [comment]
I think this is correct fix, but will be better not to change the assertion lines, but change the `val stringMap = hashMapOf` to `val stringMap = mapOf`
the main problem is how `hashMapOf` works you can see the example here https://pl.kotl.in/tdXOWAJ21

cc @VaiTon @mrudultora

**Comment by mrudultora** [comment]
@naivekook I guess, `val stringMap = hashMapOf to val stringMap = mapOf` is only used in **AdditivesWrapperTests**. In **AllergensWrapperTests** `mapOf` is used. So, I think assertion lines must be changed in that. Thanks, for your suggestions.

**Comment by mrudultora** [comment]
@VaiTon As stated by @naivekook I replaced _hashMapOf_ with _mapOf_ and reverted the assertion lines to the original ones. But in **AllergensWrapperTests** I think assertion lines must be changed.

**Comment by teolemon** [comment]
openfoodfacts.github.scrachx.openfood.models.ProductStateTest > toString_returnsProperlyFormattedString FAILED
    com.google.common.truth.ComparisonFailureWithFacts at ProductStateTest.kt:26

openfoodfacts.github.scrachx.openfood.models.entities.label.LabelsWrapperTest > map_returnsListOfCorrectlyMappedLabels_SubElementsAreMappedCorrectly FAILED
    com.google.common.truth.ComparisonFailureWithFacts at LabelsWrapperTest.kt:65

**Comment by teolemon** [comment]
https://github.com/openfoodfacts/openfoodfacts-androidapp/blob/develop/app/src/test/java/openfoodfacts/github/scrachx/openfood/models/entities/label/LabelsWrapperTest.kt#L65
https://github.com/openfoodfacts/openfoodfacts-androidapp/blob/develop/app/src/test/java/openfoodfacts/github/scrachx/openfood/models/ProductStateTest.kt#L26

**Comment by teolemon** [comment]
It stopped working after the refactor: https://github.com/openfoodfacts/openfoodfacts-androidapp/commit/86a1d6952587df7280e44a76b22517ad2ed0601f

**Comment by teolemon** [comment]
The label related changes I see in that refactor commit are in ProductRepository.kt

**Comment by kartikaysharma01** [comment]
@teolemon The label wrapper and product state test have been fixed in https://github.com/openfoodfacts/openfoodfacts-androidapp/pull/3790

**Comment by mrudultora** [comment]
@teolemon For few tests @kartikaysharma01 had made the PR. Remaining ones had been fixed in this PR.

**Pull request merged**
