### PR TITLE
Closes #489: Enabled Shrink resources in build.gradle

### LINKED ISSUE #489: enable shrinkResources in build.gradle
Libraries that you add to your code may include unused resources. Gradle can automatically remove resources on your behalf if you enable shrinkResources in your app's build.gradle file.
```
android {
    // Other settings

    buildTypes {
        release {
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}
```
https://developer.android.com/topic/performance/reduce-apk-size.html

### PR DESCRIPTION
**Pull request by ManognaMutyala**
## Description

Changes are made to reduce apk size by enabling shrink resources

## Related issues and discussion
#489 
 
 
 
 ## Checklist
 
Make sure you've done all the following (You can delete the checklist before submitting)
 
 - [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.
 - [x] Code is well documented
 - [x] Include unit tests for new functionality
 - [x] All user-visible strings are made translatable
 
 - [x] If you have multiple commits please combine them into one commit by squashing them.
 - [x] Read and understood the contribution guidelines .

### CODE REVIEW

**Comment by Karljoones** [comment]
Hi @ManognaMutyala can you have a look at the Travis build and resolve any checks that may have been failing?

**Comment by ManognaMutyala** [comment]
Definitely @Karljoones, I will try rectifying errors

**Comment by ManognaMutyala** [comment]
@iml-v I had already done what you said in the previous commits but I had to delete them because of some issues with the branches.As you said on adding aaptOptions doesn't solve the problem, it's just another way of reducing the size of apk.There is some problem with proguard.txt files. Anyways thanks for the suggestion.

**Comment by Karljoones** [comment]
@ManognaMutyala how is this PR coming along? I see that the travis build is failing, could you have another look at this?

**Comment by Karljoones** [comment]
This build is failing due to issues with proguard, can you have a look into this please?

**Comment by ManognaMutyala** [comment]
Ok @Karljoones  I will look into it

**Comment by Karljoones** [comment]
Poke @ManognaMutyala

**Comment by ManognaMutyala** [comment]
@Karljoones  It passes travis build test

**Comment by Karljoones** [comment]
@teolemon can you have a quick look at this and merge if you see fit? I think it's good for merging

**Comment by teolemon** [comment]
Merging, thanks @ManognaMutyala  :)

**Comment by ManognaMutyala** [comment]
Welcome @teolemon :)

**Pull request merged**
