### PR TITLE
Fixed #882: frozen camera preview

### LINKED ISSUE #882: Frozen camera preview
Steps:
1. Open screen to scan bar code.
2. Choose the "Select camera" option in toolbar
3. Click cancel in pop up dialog

Actual result: the camera preview is frozen, there is no ability to scan bar code.
Expected result: camera preview is working, there is ability to scan bar code.

### PR DESCRIPTION
**Pull request by l-o-b-s-t-e-r**
1) Fixed the build, because the project wasn't building.
2) Also fixed frozen camera bug. Removed stopping of the camera before opening "Select a camera" dialog. Added refreshing of camera when user chooses different camera.

### CODE REVIEW

**Comment by policorn** [comment]
Hi @l-o-b-s-t-e-r, can you leave this PR just for the build fix (thanks!) and create a new one with the frozen camera?

**Comment by policorn** [comment]
I've created the issue #885 for the build issue

**Comment by policorn** [comment]
Hi @l-o-b-s-t-e-r, nevermind; another user has created a PR with the isolated fix for the master branch. I'll be reviewing your fix for the Camera bug shortly

**Comment by policorn** [comment]
HI @teolemon, this can be merged

**Comment by l-o-b-s-t-e-r** [comment]
@teolemon 
fixed merge conflicts

**Comment by policorn** [comment]
Thanks @l-o-b-s-t-e-r, merged

**Pull request merged**
