### PR TITLE
Fixed #855: Automatic detection of text in image

### LINKED ISSUE #855: Add message to ensure text is legible when taking the ingredient and nutrition picture
image
"Is text legible ? " and a button to take the photo again.

### PR DESCRIPTION
**Pull request by ManognaMutyala**
## Description
Automated detection of text is made during the addition of images of nutrition and ingredients.Let's user to add image only if text is detected !!

## Related issues and discussion
Fixes #855 
 
 ## Screen-shots, if any
https://drive.google.com/file/d/1_tmpNdxY3fLH6kRby0p4ohKzoINLmGRc/view?usp=sharing
It would look something like this

 
 ## Checklist
 
Make sure you've done all the following (You can delete the checklist before submitting)
 
 - [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.
 - [x] Code is well documented
 - [x] Include unit tests for new functionality
 - [x] All user-visible strings are made translatable
 - [x] Code passes Travis builds in your branch
 - [x] If you have multiple commits please combine them into one commit by squashing them.
 - [x] Read and understood the contribution guidelines .

### CODE REVIEW

**Comment by Shubham2320** [comment]
Ohh! great you've used Tesseract to implement OCR, but I don't think this was asked on issue #855.

**Comment by Shubham2320** [comment]
There is also an issue for OCR #583.

**Comment by ManognaMutyala** [comment]
Thanks, @Shubham2320 , I know this was not the feature which was asked in the issue #855 but the end goals are same to determine the readability of text.I wanted to work on the issue #583 but couldn't understand about NSNW.  @teolemon, Kindly insist me if I have to submit a new issue for the above PR.

**Comment by teolemon** [comment]
- NSFW = Non Safe For Work. EG detecting people who send nude pictures. But we will do that server side. 
- Also, I'm not a big than of blocking completely submissions if no text is found. Just a transiant alert probably ("We couldn't detect any text in this image. Can you try making it sharper ?")
- Can you remove the dependancy on 'com.google.android.gms:play-services-vision:9.0.0+' ? The app will be distributed to people who don't want any non-free dependancy (on the Play Store). You can either use tesseract or we could add an API

**Comment by Karljoones** [comment]
Poke @ManognaMutyala

**Comment by ManognaMutyala** [comment]
I am really sorry @Karljoones, I had my exams these days.Also, I require an API key to add this functionality, if you want me to remove com.google.android.gms:play-services-vision:9.0.0+

**Comment by Karljoones** [comment]
No worries @ManognaMutyala! Hope your exams went well, don't worry about this PR until your exams are done. In terms of API keys, ping @teolemon

**Comment by ManognaMutyala** [comment]
@teolemon  could you please provide me API key for ocr?

**Comment by Karljoones** [comment]
@teolemon can you have a look into this one?

**Comment by Karljoones** [comment]
Hey @ManognaMutyala just discussed this with another maintainer and we decided that it may be best just to close this PR and not merge the code. 

We feel that this would be preventing users from contributing, and this may cause a hurdle that they have to jump over. We want to make it as easy as possible for them to contribute their data.

Secondly, the user of the play services vision library has some market limitations, for example, this is not available in China or through F-Droid.

As always, thank you for your work on this and sorry that we are not going to merge this!

**Pull request closed without merging**
