### PR TITLE
Fixes #1114 Make stores clickable

### LINKED ISSUE #1114: Make stores clickable
One of the killer things on Open Food Facts web version is being able to browse all products of a same store by clicking on the Store field on the product page (eg: Reliance Fresh)
It would be great to make the store field clickable

https://world.openfoodfacts.org/product/8904063200945/haldirams-bhujia

Example with Reliance Fresh
https://world.openfoodfacts.org/store/reliance-fresh
https://world.openfoodfacts.org/store/reliance-fresh.json

### PR DESCRIPTION
**Pull request by ManavPoddar**
## Description

Stores are now clickable
 
 ## Screen-shots, if any
 
screenshot_20180304-205130
screenshot_20180304-205127

### CODE REVIEW

**Comment by teolemon** [comment]
conflict

**Comment by ManavPoddar** [comment]
waiting for #1140 to merge so that there are no conflicts

**Comment by Karljoones** [comment]
#1140 Is merged, please resolve conflicts :)

**Comment by ManavPoddar** [comment]
Working on it, will submit a PR soon :)

**Comment by teolemon** [comment]
This probably needs to be migrated to the new system or closed.

**Comment by ManavPoddar** [comment]
hey @teolemon , in #1161, a common activity is made, so would be implementing the fix using that activity. 
:)

**Comment by Karljoones** [comment]
Hey guys. Is this being changed to use the new activity to show the information? Or are we going to close this PR?

**Comment by ManavPoddar** [comment]
Hey @Karljoones , I've made the changes and used the new ProductListActivity to show the information. Please review it :)

**Comment by Karljoones** [comment]
Merged, thanks @ManavPoddar

**Pull request merged**
