### PR TITLE
added ISSUE_TEMPLATE.md for new issue creation

### PR DESCRIPTION
**Pull request by iml-v**
fix : #717 created template for creating new issue by contributors (what they observed and what should be instead of that ) how others can reproduce same issue like this .

### CODE REVIEW

**Comment by iml-v** [comment]
@teolemon  review this PR.

**Comment by iml-v** [comment]
@ross-holloway94  thanks for review , i will do that soon .

**Comment by iml-v** [comment]
@ross-holloway94  @teolemon  done changes 👍

**Comment by teolemon** [comment]
thanks @iml-v

**Pull request merged**
