### PR TITLE
fixes #930 In AlertUserFragment we're only abstracting english and  french allergens from AllergenDao

### LINKED ISSUE #930: In AlertUserFragment we're only abstracting english and french allergens from AllergenDao
**Code:**

```java
for (Allergen a : mAllergensFromDao) {
            if (Locale.getDefault().getLanguage().contains("fr")){
                if(a.getIdAllergen().contains("fr:")) allS.put(index, a.getName().substring(a.getName().indexOf(":")+1));
            } else if (Locale.getDefault().getLanguage().contains("en")) {
                if(a.getIdAllergen().contains("en:")) allS.put(index, a.getName().substring(a.getName().indexOf(":")+1));
            }
            index++;
        }
```
Here in this code, we're only abstracting English and French allergens. However, I've checked allergens of other languages are also present in AllergenDao so instead of just these two languages we should check for each language which has been chosen by the user.

I've already fixed this and going to send a PR soon.

### PR DESCRIPTION
**Pull request by Shubham2320**
## Description

Fixes #930 and also optimised the code little bit as in previous code `Locale.getDefault().getLanguage()` was called for each element of  AllergenDao so instead of this it is now called just one time before starting of the loop.

**Example of languages which are in AllergenDao and are not used before:**
Italian, German, Japanese, Russian, etc.

## Related issues and discussion
#930

### CODE REVIEW

**Comment by teolemon** [comment]
This makes me think that we should look for all translations of an allergen, in all available languages on the product. This might yield false positives but will be safer than the current implementation.

**Comment by Shubham2320** [comment]
yep, I agree.

**Comment by teolemon** [comment]
merging, we need to open an issue about my remark

**Comment by Shubham2320** [comment]
Shall I open a new issue?

**Comment by teolemon** [comment]
Please do, you can copy paste directly from here

**Pull request merged**
