### PR TITLE
Landscape enabled

### PR DESCRIPTION
**Pull request by iml-v**
## Description

 #186 Landscape screen orientation enabled in tab  

## Related issues and discussion
 #186
 
 ## Screen-shots, if any
 
lanscape-mode
lanscape-mode1

 ## Checklist
 
Make sure you've done all the following (You can delete the checklist before submitting)
 
 - [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.
 - [x] Code is well documented
 - [x] Include unit tests for new functionality
 - [x] All user-visible strings are made translatable
 - [x] Code passes Travis builds in your branch
 - [x] If you have multiple commits please combine them into one commit by squashing them.
 - [x] Read and understood the contribution guidelines .

### CODE REVIEW

**Comment by iml-v** [comment]
@teolemon Please review this PR . I have tested this on  TAB Android 8.0.0  Nexus 9 API 26 working well .

**Comment by Karljoones** [comment]
I see no issues with the code. Might be best to go the full way and allow for users to use landscape on their phones if they want to. How does a product view look with this?

**Comment by PrajwalM2212** [comment]
@teolemon @Karljoones  This is not the way to enable the app for use in landscape mode . 
For landscape mode we need to create separate layouts . For designing for tablets we need to implement something called "Master Detail Flow" . 
Let the task of enabling the app for tablets be kept for later as there is a lot of work involved .

**Comment by iml-v** [comment]
@Karljoones This is how product view looks 
productview
ha

**Comment by teolemon** [comment]
Merged, thanks @iml-v

**Pull request merged**
