### PR TITLE
Fixed #301 : Add a link in settings to ask for translation help

### LINKED ISSUE #301: Add a link in settings to ask for translation help
This is the place people look to switch language. We can thus link to an entry:
"Help translate Open Food Facts" "Bring the open food database to your language" to
https://crowdin.com/project/openfoodfacts/XX (ru; fr…)
https://crowdin.com/project/openfoodfacts

### PR DESCRIPTION
**Pull request by PrajwalM2212**
## Description

Added a link in settings to ask for translation help

## Related issues and discussion
#301 
 
 ## Screen-shots, if any
 
translate

### CODE REVIEW

**Comment by PrajwalM2212** [comment]
I will make the change.

**Comment by PrajwalM2212** [comment]
translate

**Comment by Karljoones** [comment]
Thank you for making the changes, just want to wait for the travis build to complete and then we can merge

**Comment by Karljoones** [comment]
Oh! Just one final thing that I completely missed first time around, make sure that the string for the URL is non-translatable! Just to make sure nothing goes wrong with it :)

**Pull request closed without merging**
