### PR TITLE
Fixes #813 Add Intro Screens

### LINKED ISSUE #813: Add Intro Screens
**Summary:** 

Currently when a user opens the app for the first time their is no intro screens about what are the main features of the app or how should the user proceed in the app.

**Steps to reproduce:** 

Open the App for the first time.

**Observed behavior:** 

Adding intro screens in the android app will make it more appealing to new users.

**Screen-shots:** 

This is the intro screen of one of the apps made by me and adding screens like this will make the app more appealing to new users.

I would like to work on this feature.

### PR DESCRIPTION
**Pull request by Arshilgenius**
## Description

Currently when a user opens the app for the first time their is no intro screens about what are the main features of the app or how should the user proceed in the app.

## Related issues and discussion
Fixes #813
 
 ## Screen-shots, if any

 
 ## Checklist
 
Make sure you've done all the following (You can delete the checklist before submitting)
 
 - [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.
 - [x] Code is well documented
 - [ ] Include unit tests for new functionality
 - [x] All user-visible strings are made translatable
 - [x] Code passes Travis builds in your branch
 - [x] If you have multiple commits please combine them into one commit by squashing them.
 - [x] Read and understood the contribution guidelines .

### CODE REVIEW

**Comment by Karljoones** [comment]
I think that these look wonderful!

**Comment by Arshilgenius** [comment]
@Karljoones  thanks :D took my almost whole day but it was worth it :)

**Comment by teolemon** [comment]
👍

**Comment by Karljoones** [comment]
Just waiting to ensure that the travis build builds right, after that we are golden to merge!

**Comment by Karljoones** [comment]
Merged, thanks @Arshilgenius!

**Pull request merged**
