### PR TITLE
Hid search option in action bar of preferences screen,Fixes #1073

### LINKED ISSUE #1073: Removal of search icon in preference screen
**Checklist**
- [x] Bug Report - The issue you are reporting might be there already. Please search for

 the [issues tracker](https://github.com/openfoodfacts/openfoodfacts-androidapp/issues) before creating or reporting an issue.
- [x] Before reporting, please ensure (if you can) that you have tested it with the latest (dev) version of the software.
- [x] Don't forget to tag your issue, it makes it easier to discover.
**Summary:** 
Search option for products is displayed on action bar of preference screen which shouldn't be placed.

**Steps to reproduce:** 
I would like to hide search button 

How can we reproduce the issue?
Hide the search option 

**Screenshots:** 

img_20180303_230558

### PR DESCRIPTION
**Pull request by ManognaMutyala**
## Description

Made search option invisible

## Related issues and discussion
#1073
 
 ## Screen-shots, if any
screenshot_20180303-230234

 
 ## Checklist
 
Make sure you've done all the following (You can delete the checklist before submitting)
 
 - [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.
 - [x] Code is well documented
 - [x] Include unit tests for new functionality
 - [x] All user-visible strings are made translatable
 - [x] Code passes Travis builds in your branch
 - [x] If you have multiple commits please combine them into one commit by squashing them.
 - [x] Read and understood the contribution guidelines.

### CODE REVIEW

**Comment by Shubham2320** [comment]
I think search functionality should also be disabled on other similar fragments as well, like offlineEditFragment.

**Comment by ManognaMutyala** [comment]
@Shubham2320  I will work on it !!!

**Comment by Karljoones** [comment]
So it can be disabled for the following:

- Search by barcode
- Offline Edit
- Allergen Alert

**Comment by teolemon** [comment]
Merged.

**Comment by teolemon** [comment]
Thanks @ManognaMutyala :)
@Karljoones Perhaps keeping it in Search by barcode ?

**Pull request merged**
