### PR TITLE
fixes #2273 : When no items are added to offline edit, Text is misplaced 

### LINKED ISSUE #2273: When no items are added to offline edit, Text is misplaced
**Checklist**
- [x] Bug Report - The issue you are reporting might be there already. Please search on the [issues tracker](https://github.com/openfoodfacts/openfoodfacts-androidapp/issues) before creating or reporting an issue.
- [x] Before reporting, please ensure (if you can) that you have tested it with the latest (dev) version of the software.
- [x] Don't forget to tag your issue, it makes it easier to discover.
**Summary:** 

When no items are added to offline edit, Text is misplaced

**Steps to reproduce:** 

1.Go to offline edit
2.See the error if you haven't add any items

**Expected behavior:** 

The test view must be in a proper position

**Device and Android version:** 

Asus 3s max.OS 7.1

**Screenshots:** 
addlist

### PR DESCRIPTION
**Pull request by mustaqmustu**
## Description
Edited fragments_offline_edit.xml as  when no items are added to offline edit, Text is misplaced 

## Related issues and discussion
#2273 
offpic

 

 
Make sure you've done all the following (You can delete the checklist before submitting)
 
 - [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.
 - [x] Code is well documented
 - [x] Include unit tests for new functionality
 - [x] All user-visible strings are made translatable
 - [x] Code passes Travis builds in your branch
 - [x] If you have multiple commits please combine them into one commit by squashing them.
 - [x] Read and understood the contribution guidelines .

### CODE REVIEW

**Comment by Karljoones** [comment]
It might be best to center this text rather than have it scroll. That way the user sees the full text as soon as they open the fragment rather than scroll.

**Comment by mustaqmustu** [comment]
> It might be best to center this text rather than have it scroll. That way the user sees the full text as soon as they open the fragment rather than scroll.

ok i will go with it

**Comment by Karljoones** [comment]
Thanks @mustaqmustu 👏

**Comment by Karljoones** [comment]
Let me know when this is done and I can merge it

**Comment by mustaqmustu** [comment]
> Let me know when this is done and I can merge it

Can u check it out once now?

**Comment by Karljoones** [comment]
Thanks @mustaqmustu :)

**Pull request merged**
