### PR TITLE
Added styles to some of the buttons in edit section to maintain consistency in app

### PR DESCRIPTION
**Pull request by mustaqmustu**
Make sure you've done all the following (You can delete the checklist before submitting)
 
 - [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.
 - [x] Code is well documented
 - [x] Include unit tests for new functionality
 - [x] All user-visible strings are made translatable
 - [x] Code passes Travis builds in your branch
 - [x] If you have multiple commits please combine them into one commit by squashing them.
 - [x] Read and understood the contribution guidelines .

### CODE REVIEW

**Comment by Karljoones** [comment]
Can you include some screenshots please?

**Comment by mustaqmustu** [comment]
> Can you include some screenshots please?

image
image
image
image

**Comment by teolemon** [comment]
@mustaqmustu Can you take advantage of the PR to ensure that "Take more photo" is not hidden in simplified addition mode ?

**Comment by teolemon** [comment]
Can you add a little space before the button ?
image

**Comment by mustaqmustu** [comment]
> Can you add a little space before the button ?
> image

@teolemon done
image

**Comment by teolemon** [comment]
looks good for me @Karljoones

**Pull request merged**
