### PR TITLE
Fixes #2671: Updated compile and target SDK versions of the app

### LINKED ISSUE #2671: Update the compile and target SDK version
**Summary**

The compileSdkVersion and targetSdkVersion which are set to versions 27 and 27, respectively, must be changed to 28( Android Pie) as the latest Android APIs must be used to make use of the latest features.

### PR DESCRIPTION
**Pull request by RajaVamsi11**
## Description

Updated compile and target SDK versions ( from 27 to 28 ) of the app in the build. gradle file to make use of the latest features.

## Related issues and discussion
Fixes #2671

### CODE REVIEW

**Comment by RajaVamsi11** [comment]
@deniger Please take a look at this PR.

**Comment by VaiTon** [comment]
@RajaVamsi11 would you please rebase on latest commits to see if it pass the checks?

**Comment by RajaVamsi11** [comment]
@VaiTon @deniger Rebased the commits and it passed all the checks. Please review it again.

**Comment by RajaVamsi11** [comment]
@deniger Please review this PR.

**Comment by deniger** [comment]
Should be revert as materialDrawer is not compatible with sdk 28 (com.mikepenz.materialdrawer.view.BezelImageView)
To reproduce: upgrade to version 28 and try to open the main menu ( top left).

**Pull request merged**
