### PR TITLE
Fixed #1376 #1377 #1379 #1380 #1365 (Disabled Nutrition grade overlay, grade sorting in history, photos tabs for OPF)

### LINKED ISSUE #1376: Add a special "Photos" tab for opf flavour to display all uploaded image for a product
Add a special "Photos" tab for opf flavour to display all uploaded images for a product

### PR DESCRIPTION
**Pull request by PrajwalM2212**
## Description

1.Disabled grade overlay in History for OBF, OPFF and OPF flavors
2.Disabled the ingredients tab for the opf flavour
3.Added a special "Photos" tab for opf flavour to display all uploaded image for a product
4.Disabled nutrition grade in History sorting for OBF, OPFF and OPF
5.Extracted a string as a non translatable string

## Related issues and discussion
#1376 #1377 #1379 #1380 #1365 
 
 ## Screen-shots, if any
Disabled Nutrition grade overlay
screenshot_1522679478
Disabled Nutrition grade sorting
screenshot_1522679445
Photos Tab
screenshot_1522679227
Added Photos Tab
screenshot_1522679221

### CODE REVIEW

**Comment by PrajwalM2212** [comment]
@teolemon I have sent one PR for all 5 issues because individually some of the issues were very small.

**Comment by teolemon** [comment]
The photos tabs could be an optional tab for all flavors, for power contributors (eg, not enabled by default)

**Comment by PrajwalM2212** [comment]
@teolemon  Do you want photos tab to be in all flavors ?

**Comment by teolemon** [comment]
Enabled by default in OPF, and behind a setting in OFF, OBF, OPFF
"Show Product photos tab"
"Show a tab with all product photos ever taken"

**Comment by PrajwalM2212** [comment]
@teolemon 
image
Done

**Comment by teolemon** [comment]
Can you rebase on latest trunk ? It should fix the build.

**Comment by PrajwalM2212** [comment]
Rebase done

**Comment by PrajwalM2212** [comment]
Can this PR be reviewed ?

**Comment by teolemon** [comment]
@PrajwalM2212 Can you do one more rebase ? >_<

**Comment by PrajwalM2212** [comment]
@teolemon Rebase done and conflicts fixed

**Comment by Karljoones** [comment]
Just restarted the Travis build to see if we can get it passing before merging.

**Comment by teolemon** [comment]
Build passing. Just a merge conflict left.

**Comment by Karljoones** [comment]
Hi @PrajwalM2212 could you have a look into the failing build?

**Comment by PrajwalM2212** [comment]
@Karljoones  Many PR's have been getting this error. Restarting the build should solve like others.

**Comment by Karljoones** [comment]
@PrajwalM2212 I've already restarted it three times with no avail unfortunately, I'll restart it again to see if we can get it to trigger. I am aware that it was building before fixing conflicts

**Comment by Karljoones** [comment]
Merged before it fails again! Thanks @PrajwalM2212

**Pull request merged**
