### PR TITLE
Fixed #1109 : Make country clickable on Product Page

### LINKED ISSUE #1084: History should be fully translatable
image
Note that"'History" activity title should be translatable as well as the timestamp.

### LINKED ISSUE #1109: Make country clickable on Product Page
One of the killer things on Open Food Facts web version is being able to browse all products of a same country by clicking on the Country field on the product page (eg: France)
It would be great to make the country field clickable

https://world.openfoodfacts.org/product/8904063200945/haldirams-bhujia

Example with India
https://world.openfoodfacts.org/country/india
https://world.openfoodfacts.org/country/india.json

### PR DESCRIPTION
**Pull request by PrajwalM2212**
## Description
Country is now clickable on product page.

## Related issues and discussion
#1109 
 
 ## Screen-shots, if any
 
 countries
countryweb

### CODE REVIEW

**Comment by PrajwalM2212** [comment]
@teolemon Conflicts resolved and Travis check passed .

**Comment by PrajwalM2212** [comment]
@teolemon To provide more in-app experience , I will implement this in recycler view .

**Comment by PrajwalM2212** [comment]
@teolemon To give users more in-app experience , I am implementing this in recycler view.

**Comment by Shubham2320** [comment]
Hey, @PrajwalM2212 😄  you can use `BrandActivity.java` class for this, just by using some if else conditions in this activity as products by brand, categories and stores provide a similar response and it would quite not good to make different activities for all these. You may change the name of activity to some common name for brand, categories and stores and use it there if you wish. Also, you can use Search.java class to hold the JSON response.

**Pull request closed without merging**
