### PR TITLE
Added list name on product summary page

### LINKED ISSUE #2250: Show if a product belongs to one of the lists on the summary tab
Show if a product belongs to one of the user's lists on the summary tab

### PR DESCRIPTION
**Pull request by prashantkh19**
## Related issues and discussion
#fixes #2250 
 
 ## Screen-shot
device-2019-02-21-150735

### CODE REVIEW

**Comment by teolemon** [comment]
Can you move it to below the Nova/Nutri-Score ? 
Also, I was thinking of a perhaps colored chip design with numbers (different PR)
image

**Comment by Karljoones** [comment]
@prashantkh19 can you take another look at this?

**Comment by teolemon** [comment]
We can ship it without a fancy UX if it's stable.

**Comment by teolemon** [comment]
Ok, merging then 👍 
Thanks a lot @prashantkh19

**Pull request merged**
