### PR TITLE
Cleanup strings.xml

### PR DESCRIPTION
**Pull request by teolemon**

### CODE REVIEW

**Comment by teolemon** [comment]
R.string.not_support_books                      │ /Users/pierre/StudioProjects/openfoodfacts-androidapp/app/src/opff/res/values-ga/stri… │ 0.00 kb      │
│R.string.slide_4_desc                           │ /Users/pierre/StudioProjects/openfoodfacts-androidapp/app/src/opff/res/values-ga/stri… │ 0.00 kb      │
│R.string.slide_2_desc                           │ /Users/pierre/StudioProjects/openfoodfacts-androidapp/app/src/opff/res/values-ga/stri… │ 0.00 kb      │
│R.string.slide_1_title                          │ /Users/pierre/StudioProjects/openfoodfacts-androidapp/app/src/opff/res/values-ga/stri… │ 0.00 kb      │
│R.string.slide_4_title                          │ /Users/pierre/StudioProjects/openfoodfacts-androidapp/app/src/opff/res/values-ga/stri… │ 0.00 kb      │
│R.string.slide_1_desc                           │ /Users/pierre/StudioProjects/openfoodfacts-androidapp/app/src/opff/res/values-ga/stri… │ 0.00 kb      │
│R.string.translate_help_summary                 │ /Users/pierre/StudioProjects/openfoodfacts-androidapp/app/src/opff/res/values-ga/stri… │ 0.00 kb      │
│R.string.slide_2_title                          │ /Users/pierre/StudioProjects/openfoodfacts-androidapp/app/src/opff/res/values-ga/stri… │ 0.00 kb      │
│R.string.txtDialogsContentPowerMode             │ /Users/pierre/StudioProjects/openfoodfacts-androidapp/app/src/opff/res/values-ga/stri… │ 0.00 kb      │
│R.string.translate_help_title                   │ /Users/pierre/StudioProjects/openfoodfacts-androidapp/app/src/opff/res/values-ga/stri… │ 0.00 kb      │

**Comment by teolemon** [comment]
│R.string.slide_2_title                          │ /Users/pierre/StudioProjects/openfoodfacts-androidapp/app/src/opf/res/values-ur/strin… │ 0.00 kb      │
│R.string.txtDialogsContentPowerMode             │ /Users/pierre/StudioProjects/openfoodfacts-androidapp/app/src/opf/res/values-ur/strin… │ 0.00 kb      │
│R.string.translate_help_title                   │ /Users/pierre/StudioProjects/openfoodfacts-androidapp/app/src/opf/res/values-ur/strin… │ 0.00 kb      │
│R.string.slide_4_desc                           │ /Users/pierre/StudioProjects/openfoodfacts-androidapp/app/src/opf/res/values-ur/strin… │ 0.00 kb      │
│R.string.slide_2_desc                           │ /Users/pierre/StudioProjects/openfoodfacts-androidapp/app/src/opf/res/values-ur/strin… │ 0.00 kb      │
│R.string.not_support_books                      │ /Users/pierre/StudioProjects/openfoodfacts-androidapp/app/src/opf/res/values-ur/strin… │ 0.00 kb      │
│R.string.slide_4_title                          │ /Users/pierre/StudioProjects/openfoodfacts-androidapp/app/src/opf/res/values-ur/strin… │ 0.00 kb      │
│R.string.slide_1_title                          │ /Users/pierre/StudioProjects/openfoodfacts-androidapp/app/src/opf/res/values-ur/strin… │ 0.00 kb      │
│R.string.slide_1_desc                           │ /Users/pierre/StudioProjects/openfoodfacts-androidapp/app/src/opf/res/values-ur/strin… │ 0.00 kb      │
│R.string.translate_help_summary                 │ /Users/pierre/StudioProjects/openfoodfacts-androidapp/app/src/opf/res/values-ur/strin… │ 0.00 kb

**Comment by teolemon** [comment]
│R.string.slide_1_desc                           │ /Users/pierre/StudioProjects/openfoodfacts-androidapp/app/src/off/res/values-sl/strin… │ 0.00 kb      │
│R.string.slide_2_title                          │ /Users/pierre/StudioProjects/openfoodfacts-androidapp/app/src/off/res/values-sl/strin… │ 0.00 kb      │
│R.string.not_support_books                      │ /Users/pierre/StudioProjects/openfoodfacts-androidapp/app/src/off/res/values-sl/strin… │ 0.00 kb      │
│R.string.slide_2_desc                           │ /Users/pierre/StudioProjects/openfoodfacts-androidapp/app/src/off/res/values-sl/strin… │ 0.00 kb      │
│R.string.slide_4_desc                           │ /Users/pierre/StudioProjects/openfoodfacts-androidapp/app/src/off/res/values-sl/strin… │ 0.00 kb      │
│R.string.slide_1_title                          │ /Users/pierre/StudioProjects/openfoodfacts-androidapp/app/src/off/res/values-sl/strin… │ 0.00 kb      │
│R.string.txtDialogsContentPowerMode             │ /Users/pierre/StudioProjects/openfoodfacts-androidapp/app/src/off/res/values-sl/strin… │ 0.00 kb      │
│R.string.slide_4_title                          │ /Users/pierre/StudioProjects/openfoodfacts-androidapp/app/src/off/res/values-sl/strin… │ 0.00 kb

**Comment by teolemon** [comment]
│R.string.slide_4_desc                           │ /Users/pierre/StudioProjects/openfoodfacts-androidapp/app/src/obf/res/values-vec/stri… │ 0.00 kb      │
│R.string.slide_2_desc                           │ /Users/pierre/StudioProjects/openfoodfacts-androidapp/app/src/obf/res/values-vec/stri… │ 0.00 kb      │
│R.string.slide_1_title                          │ /Users/pierre/StudioProjects/openfoodfacts-androidapp/app/src/obf/res/values-vec/stri… │ 0.00 kb      │
│R.string.slide_4_title                          │ /Users/pierre/StudioProjects/openfoodfacts-androidapp/app/src/obf/res/values-vec/stri… │ 0.00 kb      │
│R.string.translate_help_summary                 │ /Users/pierre/StudioProjects/openfoodfacts-androidapp/app/src/obf/res/values-vec/stri… │ 0.00 kb      │
│R.string.slide_1_desc                           │ /Users/pierre/StudioProjects/openfoodfacts-androidapp/app/src/obf/res/values-vec/stri… │ 0.00 kb      │
│R.string.slide_2_title                          │ /Users/pierre/StudioProjects/openfoodfacts-androidapp/app/src/obf/res/values-vec/stri… │ 0.00 kb      │
│R.string.translate_help_title                   │ /Users/pierre/StudioProjects/openfoodfacts-androidapp/app/src/obf/res/values-vec/stri… │ 0.00 kb

**Review by naivekook — APPROVED** [review]
LGTM

**Pull request merged**
