### PR TITLE
Closes  #1487 : Clicking on the User image or anonymous should open the Login screen

### LINKED ISSUE #1487: Clicking on the User image or anonymous should open the Login screen
Clicking on the User image or anonymous should open the Login screen

### PR DESCRIPTION
**Pull request by PrajwalM2212**
## Description

Clicking either image or anonymous opens login screen

## Related issues and discussion
#1487  #1486 
 
 ## Screen-shots, if any

apr-22-2018 23-39-04

### CODE REVIEW

**Comment by PrajwalM2212** [comment]
This can be merged before future problems arise .

**Comment by PrajwalM2212** [comment]
@Karljoones  I have fixed the issue

**Comment by Karljoones** [comment]
Thanks @PrajwalM2212, we just need to get the travis build passing now, restarting the job

**Comment by Karljoones** [comment]
Merged, thanks @PrajwalM2212

**Pull request merged**
