### PR TITLE
Closes #1352: Added an option to disable cropping

### LINKED ISSUE #1352: Add an option to disable cropping
Add an option to disable cropping in the settings (it increases time spent on adding a new product)

### PR DESCRIPTION
**Pull request by Shubham-vish**
## Description

Added an option to disable the feature of cropping images while uploading product.
The option to enable or disable the feature is added in preferenceFragment.

## Related issues and discussion
closes #1352
 
 ## Screen-shots, if any

### CODE REVIEW

**Comment by teolemon** [comment]
"Enable crop and rotate on product upload"
"Crop and rotate slows down your contribution flow"

**Comment by Karljoones** [comment]
@Shubham2320 there are some conflicts here that need to be reviewed.

**Comment by teolemon** [comment]
@Shubham2320 can you rebase so that we can merge this one :)

**Comment by Karljoones** [comment]
Poke @Shubham2320, please see the above comment

**Comment by teolemon** [comment]
@Shubham2320 Can you rebase the branch so that we can merge it ?

**Comment by Karljoones** [comment]
I'm going to close this as there has been no progress, feel free to reopen it if you want to continue working on it

**Comment by Karljoones** [comment]
Hey @Shubham-vish, this is super late and I am unsure why it was never merged - but I am going to go ahead and close this off for now due to the conflicts and the age of the PR - but, if you are still interested in resolving them, it should be good to merge. Ping me on Slack if you have any questions.

**Comment by teolemon** [comment]
We completely reworked cropping, and it now works serverside. So will close this.

**Pull request closed without merging**
