### PR TITLE
Fixed #1206: Deleted old additives files 

### LINKED ISSUE #1206: Delete old additives files
app/src/main/assets/additives_fr.json
app/src/main/assets/additives_en.json

### PR DESCRIPTION
**Pull request by iml-v**
## Description

 #1206 Delete old additives files

## Related issues and discussion
#1206

### CODE REVIEW

**Comment by iml-v** [comment]
@teolemon  i have deleted additives files ,have a look at this PR #1207

**Comment by Karljoones** [comment]
@iml-v please have a look at the Travis build and see if you can resolve the issues

**Comment by iml-v** [comment]
@Karljoones  as i'm seeing ouput of travis ```No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.``` it is travis itself error we can't do anything ,no error because of deleting these files

**Comment by Karljoones** [comment]
@iml-v thanks for letting me know, I was on mobile and could not check this. 

@teolemon any idea what could be going on with this?

**Comment by policorn** [comment]
Restarting build as the last one got stuck

**Comment by iml-v** [comment]
@Karljoones  @policorn rebuilded ,travis build passed 😄

**Comment by teolemon** [comment]
thanks @iml-v

**Pull request merged**
