### PR TITLE
Fixes #2322: adding icons to buttons as a part of making pixel perfect app

### LINKED ISSUE #2322: Add icons to buttons
image

### PR DESCRIPTION
**Pull request by mustaqmustu**
## Description

added some icons .

## Related issues and discussion
#2322 
 
 ## Screen-shots, if any
Before:
image
After:
image

 
 ## Checklist
 
Make sure you've done all the following (You can delete the checklist before submitting)
 
 - [ ] Apply the `AndroidStyle.xml` style template to your code in Android Studio.
 - [ ] Code is well documented
 - [ ] Include unit tests for new functionality
 - [ ] All user-visible strings are made translatable
 - [ ] Code passes Travis builds in your branch
 - [ ] If you have multiple commits please combine them into one commit by squashing them.
 - [ ] Read and understood the contribution guidelines .

### CODE REVIEW

**Comment by teolemon** [comment]
Thanks for the PR. I'm not sure about the icon.
I've also created a board for top UX/UI issues: https://github.com/openfoodfacts/openfoodfacts-androidapp/projects/11 :-)

**Comment by mustaqmustu** [comment]
> Thanks for the PR. I'm not sure about the icon.
> I've also created a board for top UX/UI issues: https://github.com/openfoodfacts/openfoodfacts-androidapp/projects/11 :-)

@teolemon that icopn is "call to action" icon which means "a piece of content intended to induce a viewer, reader, or listener to perform a specific act, typically taking the form of an instruction or directive"

**Comment by mustaqmustu** [comment]
@teolemon can U merge it now :)

**Comment by teolemon** [comment]
@raphael0202 Do you think it makes sense with the PR you did for the product page ?

**Comment by raphael0202** [comment]
@teolemon The button style need to be consistent with the other buttons, so it's better to wait for my PR to be merged

**Comment by mustaqmustu** [comment]
@teolemon as there is no calculate icon in vector assets, I found that "call to action" icon will be the most suitable one.

**Comment by huzaifaiftikhar** [comment]
@raphael0202 is your PR merged now? 
@teolemon @brandenfung Final decision on this PR? To merge or update the icon?
ps: I don't find the icon to be self-explanatory, we can think of something more informative.

**Comment by teolemon** [comment]
@mustaqmustu The icon doesn't mean much unfortunately. Let's give up on that one :-/

**Pull request closed without merging**
