### PR TITLE
Closes #842: Fixed the position of Progress icon.

### LINKED ISSUE #842: Progress icon misplaced
The progress icon is misplaced when uploading offline products.
A nice improvement would be to indicate progress directly by turning the red cross icon on the product line into a progress indicator.

image

### PR DESCRIPTION
**Pull request by SaumiaSinghal**
## Description
Fixed the position of Progress icon.

Describe the changes made and why they were made instead of how they were made.

- Added a new boolean isUploading to check whether uploading of product information is in progress.
- Setting the value of booleanisUploading to true when the user is uploading the data.
- Displaying the progress bar at the required position in place of image icon in save list item.

## Related issues and discussion
Fixes #842 
 
## Screenshots, if any

ezgif com-video-to-gif

 ## Checklist
 
Make sure you've done all the following (You can delete the checklist before submitting)
 
 - [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.
 - [x] Code is well documented
 - [x] Include unit tests for new functionality
 - [x] All user-visible strings are made translatable
 - [x] Code passes Travis builds in your branch
 - [x] If you have multiple commits please combine them into one commit by squashing them.
 - [x] Read and understood the contribution guidelines .

### CODE REVIEW

**Comment by Karljoones** [comment]
Hi @SaumiaSinghal can we have a screenshot of this in action before merging?

**Comment by SaumiaSinghal** [comment]
Sorry @Karljoones for replying so late. I just realised that actually it's not working fine in every situation. I am still working on the issue.

**Comment by Karljoones** [comment]
Hi @SaumiaSinghal, not a problem! Let us know when this feature is ready and we can review and merge it then :)

**Comment by SaumiaSinghal** [comment]
Hie @teolemon, actually my PR is ready, but i'm getting some errors in the build on master branch.  What should i do about it? :(

**Comment by SaumiaSinghal** [comment]
Hey, I got the problem now..I'll submit a new PR by the end of the day.

**Comment by teolemon** [comment]
Your build looks all green @Karljoones ?

**Comment by Karljoones** [comment]
Merged, thanks @SaumiaSinghal!

**Pull request merged**
