### PR TITLE
Show grade nutrition on search and history view

### PR DESCRIPTION
**Pull request by itchix**
## Description

It's been a long time since I made a commit 😋 
So this PR to add some information about grade nutrition when somebody want to search a product.
I did the same add for history.

## Related issues and discussion
None
 
 ## Screen-shots, if any
screenshot_20180227-223503
screenshot_20180227-224219
 

 ## Checklist
 
Make sure you've done all the following (You can delete the checklist before submitting)
 
 - [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.
 - [x] Code is well documented
 - [ ] Include unit tests for new functionality
 - [x] All user-visible strings are made translatable
 - [x] Code passes Travis builds in your branch
 - [x] If you have multiple commits please combine them into one commit by squashing them.
 - [x] Read and understood the contribution guidelines .

### CODE REVIEW

**Comment by itchix** [comment]
I did some cleaning in the code by the way  :)

**Comment by teolemon** [comment]
Can you remove the share icon and put the dot there?

**Comment by policorn** [comment]
My two cents; would it be possible to add the nutrition grade letter within the colored circle to improve accessibility (i.e. color blind users)?

**Comment by teolemon** [comment]
@itchix 2 little conflicts before merging.

**Comment by teolemon** [comment]
I second the letters, since we have 2 shades of green, and one orange/yellow that can confuse people.

**Comment by itchix** [comment]
I'll try to look into it ASAP

**Pull request closed without merging**
