### PR TITLE
Fix problem that ui is not visible on android editor

### PR DESCRIPTION
**Pull request by cliffgr**
## Description

Problem to see the layout on my editor:

The surrounding layout (@layout/activity_welcome) did not actually include this layout. Remove tools:showIn=... from the root tag.

 ## Screen-shots, if any

xmlerror

### CODE REVIEW

**Comment by cliffgr** [comment]
My first Commit

**Comment by Karljoones** [comment]
Welcome @cliffgr and congrats on your first commit. I just restarted the Travis build. If if fails again, please have a look at the details of the failed build and resolve the issue if possible.

**Comment by Karljoones** [comment]
Merged, thanks @cliffgr!

**Comment by cliffgr** [comment]
@Karljoones  i will start with some refactorings to learn first about the project  and after i will try to fix issues

**Pull request merged**
