### PR TITLE
Fixed #334 : Sort by barcode, name, brand 

### LINKED ISSUE #334: Sort by barcode, name, brand
Being able to sort results by barcode and name and brand in the history view (and not much more since we're changing the API we use).

### PR DESCRIPTION
**Pull request by PrajwalM2212**
## Description

The history items can now be sorted based on title , brand , time , barcode and most importantly nutrition grade.

## Related issues and discussion
#334
 
 ## Screen-shots, if any

Dialog
screenshot_1522308926 
Sort by Time
screenshot_1522252998
Sort by Title
screenshot_1522253006
Sort by Brand
screenshot_1522309081
Sort by Grade
screenshot_1522255865

### CODE REVIEW

**Comment by Karljoones** [comment]
Can you show us sort by brand on a different example? The rest look fine to me. However, the icon is not consistent with the rest of the icons in the app. This should be a material design icon. 

It would probably be best to have this as a dialog to allow the user to choose the sorting direction.

**Comment by PrajwalM2212** [comment]
@Karljoones 
1. Icon made materialistic
2. Material Dialog created
3. Different brand example shown

**Comment by Karljoones** [comment]
Looks good to me, thank you for making the changes. Maybe "time" should be "Recently viewed"?

**Comment by PrajwalM2212** [comment]
@Karljoones "time" changed to "Recently viewed"

**Comment by teolemon** [comment]
It looks good as a first version, but I'm going to open a bug server side, so that we can sort all the products, and not just the first 10, the first 20…
An added advantage of adding a server side sorting API is that we can have more sorting criteria without increasing the initial size of the JSON 
Otherwise, fine for merging feature wise.

**Comment by Karljoones** [comment]
Merged, thanks @PrajwalM2212

**Pull request merged**
