### PR TITLE
Adds an empty tab called "Changes history"

### PR DESCRIPTION
**Pull request by TapsG**
New changes from original to our fork

### CODE REVIEW

**Comment by teolemon** [comment]
Thanks @TapsG 
can you provide a little context regarding the changes?

**Comment by TapsG** [comment]
Hello! Sorry, it was a mistake, accident.

Lähetetty Windows 10:n Sähköposti<https://go.microsoft.com/fwlink/?LinkId=550986>sta

Lähettäjä: Pierre Slamich<mailto:notifications@github.com>
Lähetetty: maanantai 8. helmikuuta 2021 21.25
Vastaanottaja: openfoodfacts/openfoodfacts-androidapp<mailto:openfoodfacts-androidapp@noreply.github.com>
Kopio: TapsG<mailto:joonast94@hotmail.fi>; Mention<mailto:mention@noreply.github.com>
Aihe: Re: [openfoodfacts/openfoodfacts-androidapp] Merge pull request #20 from openfoodfacts/develop (#3818)


Thanks @TapsG<https://github.com/TapsG>
can you provide a little context regarding the changes?

**Comment by teolemon** [comment]
Currently my understanding is that the PR adds an empty tab ?

**Comment by VaiTon** [comment]
> 
> Hello! Sorry, it was a mistake, accident.

If I understood correctly, creating this PR was an accident so I'm closing this. Feel free to reopen if I'm wrong!

**Comment by TapsG** [comment]
Yes, it was accident, and thanks for closing the request!

________________________________
Lähettäjä: VaiTon <notifications@github.com>
Lähetetty: keskiviikko 10. helmikuuta 2021 18.41
Vastaanottaja: openfoodfacts/openfoodfacts-androidapp <openfoodfacts-androidapp@noreply.github.com>
Kopio: TapsG <joonast94@hotmail.fi>; Mention <mention@noreply.github.com>
Aihe: Re: [openfoodfacts/openfoodfacts-androidapp] Adds an empty tab called "Changes history" (#3818)


Hello! Sorry, it was a mistake, accident.

If I understood correctly, creating this PR was an accident so I'm closing this. Feel free to reopen if I'm wrong!

**Pull request closed without merging**
