### PR TITLE
Fixed #1107 : Make labels clickable on product page

### LINKED ISSUE #1107: Make labels clickable on product page
One of the killer things on Open Food Facts web version is being able to browse all products of a same label by clicking on the label field on the product page (eg: Organic)
It would be great to make the brand field clickable

https://world.openfoodfacts.org/product/3560070575855/tofu-a-l-indienne-riz-basmati-et-lentilles-bio-carrefour-bio

Example with Organic
https://world.openfoodfacts.org/label/organic
https://world.openfoodfacts.org/label/organic.json

### PR DESCRIPTION
**Pull request by PrajwalM2212**
## Description

The labels are now clickable and open in a chrome custom tab.

## Related issues and discussion
#1107 
 
 ## Screen-shots, if any
 
label
labelweb

### CODE REVIEW

**Comment by teolemon** [comment]
To solve the empty page issue means looking at 
image

**Comment by PrajwalM2212** [comment]
@teolemon  I did not get what you are saying

**Comment by teolemon** [comment]
https://world.openfoodfacts.org/label/it:senza-coloranti

**Comment by PrajwalM2212** [comment]
@teolemon  So after the issues relating to using the new json files for translation are resolved , we will not get a empty page .

**Comment by teolemon** [comment]
You should already able to get **it:senza-coloranti** from the current JSON, and concatenate it to the proper base url (https://world-it.openfoodfacts.org/label/). 
The world version of OFF accepts any language when it has the lang prefix.

Ex: https://world-it.openfoodfacts.org/label/it:senza-coloranti

Using the multilingual JSON will mostly allow you to translate 'Senza Coloranti' to 'Without dyes' or 'Sans colorants'

**Comment by PrajwalM2212** [comment]
@teolemon Ok , understood.

**Comment by PrajwalM2212** [comment]
@teolemon  
json


There should be a array in the json to be able to loop through it and get the required label. 
I have marked the missing array in the image.

**Comment by PrajwalM2212** [comment]
@teolemon  Seems the new files have been used for translation in https://github.com/openfoodfacts/openfoodfacts-androidapp/pull/1115 .
So the current implementation must work .

**Comment by teolemon** [comment]
conflict to solve

**Comment by PrajwalM2212** [comment]
@teolemon Conflicts solved

**Comment by teolemon** [comment]
merged, thanks @PrajwalM2212 @Karljoones

**Pull request merged**
