### PR TITLE
Fix history tab refreshing layout issue

### PR DESCRIPTION
**Pull request by R4md4c**
####  Description
The issue was that we weren't hiding the empty layout when there were elements to be rendered.

#### Related issues
#4219

### CODE REVIEW

**Review by VaiTon — APPROVED** [review]
LGTM!

**Comment by teolemon** [comment]
Merging. Thanks :-)

**Comment by teolemon** [comment]
Can still reproduce with Open Pet Food Facts

**Comment by teolemon** [comment]
actually, it's all fixed. my bad

**Pull request merged**
