### PR TITLE
Fixes #596 (Offset for the splash screen loading dialog)

### LINKED ISSUE #530: Clicking on the scan button when you arrived from the history brings back to history
Clicking on the scan button when you arrived from the history brings back to history.
It should open the scan window instead.

### LINKED ISSUE #596: Upload popup misplaced on Moto G
When uploading several images in a row, the upload popup is misplaced on Moto G 

image

image

### PR DESCRIPTION
**Pull request by ManognaMutyala**
Places the loading message properly

### CODE REVIEW

**Comment by Karljoones** [comment]
If possible, could you please provide a screenshot of this?

**Comment by itchix** [comment]
screenshot_20180216-201620

Not working as expected

**Comment by Karljoones** [comment]
@itchix seems like we had the same idea. 😛 @ManognaMutyala could you have a look at this and make necessary changes?

**Comment by ManognaMutyala** [comment]
Definitely @Karljoones  I will make necessary changes

**Comment by Karljoones** [comment]
@ManognaMutyala Thanks! Let me know when they're done and I'll have another look

**Comment by sachincool** [comment]
what's the update  @ManognaMutyala? Any progress?

**Comment by Karljoones** [comment]
Closing, issue was fixed in another PR

**Pull request closed without merging**
