### PR TITLE
Remove unused title from 'doChooseOrTakePhotos' in BaseFragment.kt

### PR DESCRIPTION
**Pull request by naivekook**
fixed

#### Related issues
https://github.com/openfoodfacts/openfoodfacts-androidapp/wiki/Build-results

#### Related PRs
none

#### Screenshots
none

### CODE REVIEW

**Comment by naivekook** [comment]
@teolemon do I need to remove 'recycling_picture' string from all string files or just removing it from main string file is enough? and crowding automatically remove it from other files?

**Comment by VaiTon** [comment]
> 
> 
> @teolemon do I need to remove 'recycling_picture' string from all string files or just removing it from main string file is enough? and crowding automatically remove it from other files?

@teolemon I think that removing it from the main file should do the job, am I right?

**Comment by teolemon** [comment]
Yes

**Comment by naivekook** [comment]
cool, so we can merge it

**Review by VaiTon — APPROVED** [review]

**Pull request merged**
