### PR TITLE
Fixed deep link issue when opening product from web

### LINKED ISSUE #3712: Exception when opening a product page from a deeplink
Sentry Issue: [OPENFOODFACTS-ANDROID-1R3](https://sentry.io/organizations/openfoodfacts/issues/2138194279/?referrer=github_integration)

```
IllegalStateException: Activity ProductViewActivity started without 'state' serializable in intent.
    at openfoodfacts.github.scrachx.openfood.utils.FragmentExtKt.requireProductState(FragmentExt.kt:31)
    at openfoodfacts.github.scrachx.openfood.features.product.view.ProductViewActivity.onCreate(ProductViewActivity.kt:88)
    at android.app.Activity.performCreate(Activity.java:8000)
    at android.app.Activity.performCreate(Activity.java:7984)
    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
...
(12 additional frame(s) were not displayed)

RuntimeException: Unable to start activity ComponentInfo{org.openfoodfacts.scanner/openfoodfacts.github.scrachx.openfood.features.product.view.ProductViewActivity}: java.lang.IllegalStateException: Activity ProductViewActivity started without 'state' serializable in intent.
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3431)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3595)
    at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
    at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
    at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
...
(7 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by mrudultora**
####  Description
Added a check in `onCreate` and `onResume` whether the product is tried to opened through a deep link.

#### Related issues
Fixes #3712

#### Related PRs
None of the PRs related to this.

#### Screenshots

https://user-images.githubusercontent.com/65870389/104558658-29562b80-5669-11eb-9c3f-3a6a483368d2.mp4

### CODE REVIEW

**Comment by mrudultora** [comment]
@VaiTon  Also, look at the product name in video file I attached ( at 0:34 ) the name gets cutoff from the view. It doesn't look good. I think this can be opened as new issue. Your views ?

**Comment by VaiTon** [comment]
> @VaiTon Also, look at the product name in video file I attached ( at 0:34 ) the name gets cutoff from the view. It doesn't look good. I think this can be opened as new issue. Your views ?

Sure you can!

**Comment by VaiTon** [comment]
Also, @mrudultora, could you merge master?

**Comment by mrudultora** [comment]
> Also, @mrudultora, could you merge master?

I didn't get it. Please, clarify 😅 .

**Comment by VaiTon** [comment]
Tests are failing, I fixed it in the latest commit to `develop`. Could you merge `develop` into this branch?

**Comment by mrudultora** [comment]
@VaiTon  Merged `develop` into this branch. Tests are successful this time !

**Review by VaiTon — APPROVED** [review]

**Pull request merged**
