### PR TITLE
 Resolved layout issues for additive cards

### LINKED ISSUE #3760: Layout issues for additives cards in German
image
image

### PR DESCRIPTION
**Pull request by mrudultora**
####  Description
Changed the hardcoded _dp_ values to _match-parent_.

#### Related issues
Fixes #3760 

#### Related PRs
None

#### Screenshots

### CODE REVIEW

**Comment by VaiTon** [comment]
@mrudultora could you post a screenshot of the fix?

**Comment by mrudultora** [comment]
@VaiTon Added the screenshot. I had kept the text size same.

img

img

**Comment by VaiTon** [comment]
@mrudultora in the first screenshot you posted the text is not correctly displayed. Could we use maybe wrap_content?

**Comment by mrudultora** [comment]
@VaiTon `wrap_content` is not working as expected. Btw, I think one more problem is there in the layout. As many values are hard coded, if the text size is set to XL in settings, the layout will look weird.

**Pull request merged**
