### PR TITLE
Tab to browse all product images

### PR DESCRIPTION
**Pull request by PrajwalM2212**
## Description

Describe the changes made and why they were made instead of how they were made.

## Related issues and discussion
#fixes {Issue Number}
 
 ## Screen-shots, if any
 
 ## Checklist
 
Make sure you've done all the following (You can delete the checklist before submitting)
 
 - [ ] Apply the `AndroidStyle.xml` style template to your code in Android Studio.
 - [ ] Code is well documented
 - [ ] Include unit tests for new functionality
 - [ ] All user-visible strings are made translatable
 - [ ] Code passes Travis builds in your branch
 - [ ] If you have multiple commits please combine them into one commit by squashing them.
 - [ ] Read and understood the contribution guidelines .

### CODE REVIEW

**Comment by teolemon** [comment]
Tiny conflict to solve. + Crasher that might not have been commited
```2018-12-14 17:04:48.392 20619-20619/openfoodfacts.github.scrachx.openfood E/RecyclerView: No adapter attached; skipping layout
2018-12-14 17:04:48.432 20619-20619/openfoodfacts.github.scrachx.openfood E/AndroidRuntime: FATAL EXCEPTION: main
    Process: openfoodfacts.github.scrachx.openfood, PID: 20619
    java.lang.NullPointerException: Attempt to invoke virtual method 'org.json.JSONArray org.json.JSONObject.names()' on a null object reference
        at openfoodfacts.github.scrachx.openfood.fragments.ProductPhotosFragment$1.onImageResponse(ProductPhotosFragment.java:113)
        at openfoodfacts.github.scrachx.openfood.network.OpenFoodAPIClient$4.onResponse(OpenFoodAPIClient.java:264)
        at retrofit2.ExecutorCallAdapterFactory$ExecutorCallbackCall$1$1.run(ExecutorCallAdapterFactory.java:70)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
2018-12-14 17:04:48.474 960-1345/? E/InputDispatcher: channel '3efe145 openfoodfacts.github.scrachx.openfood/openfoodfacts.github.scrachx.openfood.views.HistoryScanActivity (server)' ~ Channel is unrecoverably broken and will be disposed!``` 

8480000331144

**Comment by teolemon** [comment]
also:
- legibility of the dropdown menu button (very complicated to click)
- adding an option 'Report image' to the dropdown menu which links to `mailto:contact@openfoodfacts.org?subject=Photo%20report%20for%20product%20XXX&body=I've%20spotted%20a%20problematic%20photo%20for%20product%20XXX`

**Comment by teolemon** [comment]
Just built it yesterday night. Much more convenient. 
- The Report bad image option would be nice to add `mailto:contact@openfoodfacts.org?subject=Photo%20report%20for%20product%20{{barcode}}&body=I've%20spotted%20a%20problematic%20photo%20for%20product%20{{barcode}}`
- Adding a "Take more photos" button in the tab when the user realizes some part of the product need to be rephotographed.

**Comment by teolemon** [comment]
@PrajwalM2212 merged master (we tweaked the API queries a bit) into your branch.

**Comment by teolemon** [comment]
@huzaifaiftikhar Can you have a quick look ?

**Comment by huzaifaiftikhar** [comment]
@teolemon I am sorry I won't be able to review this PR at the moment. Will review in a few days when I'm free.

**Comment by PrajwalM2212** [comment]
@teolemon 
screen shot 2019-01-04 at 8 00 32 pm

Regarding `code: 61167040 (no pictures)` , the search by barcode says that it is a invalid barcode

**Comment by teolemon** [comment]
@stephanegigandet we might receive additional mail. This will be an optional tab for power users.

**Comment by teolemon** [comment]
@PrajwalM2212 can you rebase before it gets too dirty ?

**Comment by teolemon** [comment]
Thanks @PrajwalM2212 👍

**Comment by teolemon** [comment]
I'm merging this one @PrajwalM2212 👍

**Pull request merged**
