### PR TITLE
fix issue #260 - Display additives as a structured list #260

### PR DESCRIPTION
**Pull request by sowmya9029**
## Description

Added list of additives with description.Added screenshot here  https://github.com/openfoodfacts/openfoodfacts-androidapp/issues/260

## Related issues and discussion
#{Issue Number}
 
 ## Screen-shots, if any
 
 ## Checklist
 
Make sure you've done all the following (You can delete the checklist before submitting)
 
 - [ ] Apply the `AndroidStyle.xml` style template to your code in Android Studio.
 - [ ] Code is well documented
 - [ ] Include unit tests for new functionality
 - [ ] All user-visible strings are made translatable
 - [ ] Code passes Travis builds in your branch
 - [ ] If you have multiple commits please combine them into one commit by squashing them.
 - [ ] Read and understood the contribution guidelines .

### CODE REVIEW

**Comment by teolemon** [comment]
@sowmya9029 Can you disable the popup on click ? It's displaying unsourced data.
We'll try to reintroduce advanced additive analysis, but at a later point, and with sourced data.

**Comment by sowmya9029** [comment]
Yes I can do that.

**Comment by teolemon** [comment]
@Karljoones @policorn @ross-holloway94 up for review

**Comment by teolemon** [comment]
merged, thanks @sowmya9029

**Pull request merged**
