### PR TITLE
Fixes and improvement to dark mode

### LINKED ISSUE #3337: Tracker issue for fixes and improvements to the dark mode
### Official Android guide to implement dark mode
https://developer.android.com/guide/topics/ui/look-and-feel/darktheme

### Fixed
- [x] + sign in the list modal should be white ([image](https://user-images.githubusercontent.com/1689815/87205116-f3756a80-c306-11ea-93cc-16dc621cc92a.png)) (fixed in 45cf75026f72d1512b3eacb752295054a008456b)
- [x] Deharcode color of home text (#3336)
- [x] Background color of cards in compare mode ([image](https://user-images.githubusercontent.com/1689815/87205105-e8223f00-c306-11ea-82ca-bc87209a99c2.png))
- [x] Background color of splash screen should be black ([image](https://user-images.githubusercontent.com/1689815/87205065-cb860700-c306-11ea-88b2-72311ab9279d.png))
- [x] [Fixes in the contributor screen](https://user-images.githubusercontent.com/1689815/87653460-d4873600-c755-11ea-9f06-eee32f3842a0.png)
[Code pointer](https://github.com/openfoodfacts/openfoodfacts-androidapp/blob/develop/app/src/main/java/openfoodfacts/github/scrachx/openfood/views/YourListedProductsActivity.java#L272)
- [x] ["Send an updated image" button icon color issue in "Nutrition" tab](https://user-images.githubusercontent.com/1689815/87659602-1caa5680-c75e-11ea-9dd1-4e8d97d68070.png)

### Points that really need fixing
- [x] Add a toggle in the settings for manual override
- [x] [Additives browser text in black](https://user-images.githubusercontent.com/1689815/87653264-9558e500-c755-11ea-9bb2-7ff129a6110d.png)
### Points that can wait

- [ ] Button not very visible in the ingredient analysis ([image](https://user-images.githubusercontent.com/1689815/85314774-41424400-b4ba-11ea-9334-f90c4f708fed.png))
- [ ] Dark mode for Robotoff questions ([image](https://user-images.githubusercontent.com/1689815/86471619-0227b480-bd3e-11ea-8b6d-0fd7ca8d6162.png))
- [ ] Nutrient value modal improvement ([image](https://user-images.githubusercontent.com/1689815/86470943-b9bbc700-bd3c-11ea-9492-a22d466527d1.png))
- [ ] [Request dark mode in webviews](https://developer.android.com/jetpack/androidx/releases/browser#1.2.0-alpha07)
- [ ] Dropdown in the image manager
- [ ] Product page refinements ([image](https://user-images.githubusercontent.com/1689815/86470714-4b770480-bd3c-11ea-9cb1-ac5d0e54636a.png))
- [ ] [Fixes for the allergy screen](https://user-images.githubusercontent.com/1689815/87653159-6fcbdb80-c755-11ea-9de3-05cd89d06992.png)
- [ ] [Background color of cards in the "Contribution" tab (needs to be enabled manually in settings)](https://user-images.githubusercontent.com/1689815/87653900-80c91c80-c756-11ea-92bb-7cabbffa721f.png)
- [ ] [Buttons - Edit mode](https://user-images.githubusercontent.com/1689815/87654109-c1c13100-c756-11ea-8a85-0be5027f5c5b.png)

### PR DESCRIPTION
**Pull request by mrudultora**
####  Description
Made many improvements in dark mode by adding new drawables for night mode. Also removed unnecessary code. Made the toolbar and navigationBar of webview to support dark mode.

#### Related issues
Fixes #3337 
**Note** - Some issues mentioned were already fixed. Remaining ones fixed by me are as follows with there respective screenshots :
• Buttons - Edit Mode [(Image 1)](https://user-images.githubusercontent.com/65870389/107665272-4bb48680-6cb3-11eb-8685-5109d93981f8.jpeg) [(Image 2)](https://user-images.githubusercontent.com/65870389/107665287-4eaf7700-6cb3-11eb-8543-6870960c9720.jpeg)
• Dark Mode for Robotoff questions and made the corners rounded [(Light Mode)](https://user-images.githubusercontent.com/65870389/107665275-4c4d1d00-6cb3-11eb-81dd-1173a010c6be.jpeg) [(Dark mode)](https://user-images.githubusercontent.com/65870389/107665265-4a835980-6cb3-11eb-9671-2c3fadf763d1.jpeg)
• Fixes for the allergy screen [(Image)](https://user-images.githubusercontent.com/65870389/107665278-4d7e4a00-6cb3-11eb-9b64-902e5de28349.jpeg)
• Implemented dark mode in webview [(Image)](https://user-images.githubusercontent.com/65870389/107665283-4e16e080-6cb3-11eb-8d1c-327cd925f2bc.jpeg)

#### Related PRs
Unable to find the closed PRs related to this.

### CODE REVIEW

**Comment by VaiTon** [comment]
@mrudultora did you test this on API 16?

**Comment by mrudultora** [comment]
> @mrudultora did you test this on API 16?

Umm, no! Most of the similar things are already implemented. So , I guess the remaining ones I fixed will not affect as such.

**Comment by VaiTon** [comment]
> 
> 
> > @mrudultora did you test this on API 16?
> 
> Umm, no! Most of the similar things are already implemented. So , I guess the remaining ones I fixed will not affect as such.

Could you test on API 16 please? So that we are sure.

**Comment by mrudultora** [comment]
Okay! I will update you soon.

**Comment by mrudultora** [comment]
@VaiTon Yes, you were right. It is crashing in API 16 and will surely crash in pre-lollipop devices (due to `drawableLeft` etc.). Can I add  `vectorDrawables.useSupportLibrary = true` in **build.gradle** ?
**OR** instead of doing this, I can directly add `app:drawableLeftCompat` instead of  `android:drawableLeft`. This is working completely fine on all the devices and there is no need to add `vectorDrawables.useSupportLibrary = true` in this case.

**Comment by VaiTon** [comment]
> 
> 
> @VaiTon Yes, you were right. It is crashing in API 16 and will surely crash in pre-lollipop devices (due to `drawableLeft` etc.). Can I add `vectorDrawables.useSupportLibrary = true` in **build.gradle** ?
> **OR** instead of doing this, I can directly add `app:drawableLeftCompat` instead of `android:drawableLeft`. This is working completely fine on all the devices and there is no need to add `vectorDrawables.useSupportLibrary = true` in this case.

I'd prefer the second one. Thanks. :)

**Comment by mrudultora** [comment]
After fixing the app is running completely fine in API 16. Added one of the screenshot.

img1

**Review by VaiTon — APPROVED** [review]

**Pull request merged**
