### PR TITLE
+ Fix #2359,  #2483translation issue

### LINKED ISSUE #2359: Traces are not translated
This is the same taxonomy as for the Allergen field (just above in the screenshot)

image

### LINKED ISSUE #2483: We display categories in French when the app is in Portuguese
image

It doesn't seem to be a server side issue, since we have the translation:
https://pt.openfoodfacts.org/aditivo/e300-acido-ascorbico

### PR DESCRIPTION
**Pull request by deniger**
## Description
+ transalte traces in IngredientsProductFragment
+ use LocaleHelper#getLanguage in code instead of Locale.getDefault...

## Related issues and discussion
+ Fix #2359 Traces are not translated
+ Fix #2483 We display categories in French when the app is in Portuguese

TODO: I suppose we should always use the method getLanguageTrimmed insteadof getLanguage, Could you confirm ?
 
 ## Screenshot
image

### CODE REVIEW

**Comment by deniger** [comment]
I suppose we should always use the method getLanguageTrimmed insteadof getLanguage, Could you confirm ?

**Comment by teolemon** [comment]
Yup, ideally

**Comment by deniger** [comment]
done

**Comment by teolemon** [comment]
@deniger another conflict XD

**Comment by deniger** [comment]
done ( and I believe there will have others :))

**Comment by teolemon** [comment]
Small merge conflict @deniger

**Comment by teolemon** [comment]
I'd like to merge this one and release a refreshed beta

**Pull request merged**
