### PR TITLE
fixes #1118 App crashes on tanslation fixes

### LINKED ISSUE #1118: App crashes on selecting Preference after translating to new language
**Checklist**
- [x] Bug Report - The issue you are reporting might be there already. Please search on the [issues tracker](https://github.com/openfoodfacts/openfoodfacts-androidapp/issues) before creating or reporting an issue.
- [x] Before reporting, please ensure (if you can) that you have tested it with the latest (dev) version of the software.
- [x] Don't forget to tag your issue, it makes it easier to discover.
**Summary:** 

When we select new language and again try open Preference then it crashes .

**Steps to reproduce:** 

1. select Hindi language from Select language 
2. Now again Select Preference  from drawer 

**Add system logs:**

Add log files here (if you are able to add).

**Expected behavior:** 

It should open Prefrence fragmenst 

**Observed behavior:** 

App crashes 

**Device and Android version:** 

Android 7.0 API 24

**Screenshots:** 

video2gif_20180305_035705 1

I am working on this .

### PR DESCRIPTION
**Pull request by iml-v**
## Description
fixes #1118 App crashes on selecting Preference after translation 
## Related issues and discussion
#1118 
 
 ## Screen-shots, if any
 
video2gif_20180305_042409 1

 ## Checklist
 
Make sure you've done all the following (You can delete the checklist before submitting)
 
 - [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.
 - [x] Code is well documented
 - [x] Include unit tests for new functionality
 - [x] All user-visible strings are made translatable
 - [x] Code passes Travis builds in your branch
 - [x] If you have multiple commits please combine them into one commit by squashing them.
 - [x] Read and understood the contribution guidelines .

### CODE REVIEW

**Comment by iml-v** [comment]
@teolemon @Karljoones Please review this PR #1119

**Comment by Karljoones** [comment]
Sorry @iml-v, i am not going to be merging this. "FAQ" is the key that we are looking for, whereas the string resource can be translated. The key is never translated.

**Comment by iml-v** [comment]
@Karljoones *But error is only that i find* 

```03-05 19:51:09.241 3244-3244/openfoodfacts.github.scrachx.openbeauty E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                       Process: openfoodfacts.github.scrachx.openbeauty, PID: 3244
                                                                                       java.lang.NullPointerException: Attempt to invoke virtual method 'void android.support.v7.preference.Preference.setOnPreferenceClickListener(android.support.v7.preference.Preference$OnPreferenceClickListener)' on a null object reference
                                                                                           at openfoodfacts.github.scrachx.openfood.fragments.PreferencesFragment.onCreatePreferences(PreferencesFragment.java:123)
                                                                                           at android.support.v7.preference.PreferenceFragmentCompat.onCreate(PreferenceFragmentCompat.java:224)
                                                                                           at android.support.v4.app.Fragment.performCreate(Fragment.java:2246)
                                                                                           at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1377)
                                                                                           at android.support.v4.app.FragmentTransition.addToFirstInLastOut(FragmentTransition.java:1187)
                                                                                           at android.support.v4.app.FragmentTransition.calculateFragments(FragmentTransition.java:1070)
                                                                                           at android.support.v4.app.FragmentTransition.startTransitions(FragmentTransition.java:115)
                                                                                           at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2374)
                                                                                           at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2332)
                                                                                           at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2239)
                                                                                           at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:700)
                                                                                           at android.os.Handler.handleCallback(Handler.java:751)
                                                                                           at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                           at android.os.Looper.loop(Looper.java:154)
                                                                                           at android.app.ActivityThread.main(ActivityThread.java:6776)
                                                                                           at java.lang.reflect.Method.invoke(Native Method)
                                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1518)
                                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)```

**Comment by iml-v** [comment]
@Karljoones  I have solved this Problem  and i am going to open new pull request for this.

**Comment by Karljoones** [comment]
It sounds like the language was changed on the device after this was set, so the app may be looking for "faq" that may have been translated, if it is translated into a different language and then stored with that key then it may not find "faq"

**Comment by iml-v** [comment]
@Karljoones then we should also use Key value for 'langHelp' ,'Terms ' also

**Pull request closed without merging**
