### PR TITLE
Implemented Product List Item As Card View

### PR DESCRIPTION
**Pull request by PrajwalM2212**
## Description

 Product list displayed in a card view.

## Related issues and discussion
#770 
 
 ## Screen-shots, if any

card_view

 
 ## Checklist
 
 Please make sure these boxes are checked before submitting your pull request - thanks!
 
 
 
 - [ ] Apply the `AndroidStyle.xml` style template to your code in Android Studio.
 
 - [ ] If you have multiple commits please combine them into one commit by squashing them.
 
 - [ ] Read and understood the contribution guidelines .

### CODE REVIEW

**Comment by PrajwalM2212** [comment]
@teolemon  I have completed the task .

**Comment by Karljoones** [comment]
Looks good! Any chance you could reduce the padding between the bottom and the top of the views? I can see from the code that it is 6dp, but this translates to 12dp between the items and looks a bit odd. Also, please use $rootProject.supportLibraryVersion for the version of the cardview library :)

**Comment by PrajwalM2212** [comment]
@Karljoones Glad you like it . I will make the required changes.

**Comment by Karljoones** [comment]
Hi @PrajwalM2212, I'm going to close this pull request too. Just make a new one once the changes have been made and request me to review it or ping me on Slack and I can have a look at it. If possible, try not include the commits that are there for the card view changes. (may be best to roll the code back)

**Pull request closed without merging**
