### PR TITLE
remove the LoadToast usage when we are trying to load a product

### PR DESCRIPTION
**Pull request by herau**
to avoid weird blue load toast whereas we trying to apply a Material Design UX.

### CODE REVIEW

**Comment by itchix** [comment]
Ok for me =)

**Comment by teolemon** [comment]
It looks like the toast is toast :-D

**Comment by teolemon** [comment]
ref of what's possible in terms of progress indicator in MD: https://material.io/guidelines/components/progress-activity.html#progress-activity-types-of-indicators

**Comment by itchix** [comment]
We need to remove all refs to LoadToast library in the app

**Pull request merged**
