### PR TITLE
Changed the button style of "go to full product" button in product comparison list layout and added icon to it.

### PR DESCRIPTION
**Pull request by mustaqmustu**
## Description
Changed the button style of "go to full product" button in product comparison list layout and added icon to it.
Describe the changes made and why they were made instead of how they were made. 
 ## Screen-shots, if any
 Before:
image
After:
image

 ## Checklist
 
Make sure you've done all the following (You can delete the checklist before submitting)
 
 - [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.
 - [x] Code is well documented
 - [x] Include unit tests for new functionality
 - [x] All user-visible strings are made translatable
 - [x] Code passes Travis builds in your branch
 - [x] If you have multiple commits please combine them into one commit by squashing them.
 - [ ] Read and understood the contribution guidelines .

### CODE REVIEW

**Comment by teolemon** [comment]
Can you use the fullscreen icon instead ? The back icon is confusing.

**Comment by deniger** [comment]
image
@teolemon  is it for you ? (2 lines...)

**Comment by teolemon** [comment]
Perhaps just shortening the English string will do ?
"Go to product", "Open product", "Full product" ?

**Comment by VaiTon** [comment]
> Perhaps just shortening the English string will do ?
> "Go to product", "Open product", "Full product" ?

"Go to product" is the more descriptive imo.

**Comment by teolemon** [comment]
k 👍

**Comment by mustaqmustu** [comment]
> k +1

done :)

**Comment by VaiTon** [comment]
@mustaqmustu can you post a screen if you have time?

**Comment by mustaqmustu** [comment]
> @mustaqmustu can you post a screen if you have time?

sure :)

image

**Pull request merged**
