### PR TITLE
Fixed #1134: Added option to change the language. 

### LINKED ISSUE #1134: Not able to add Allergen
**Summary:** 

Not able to add an Allergen.
videotogif_2018 03 06_21 36 09

**Screenshots:**

### PR DESCRIPTION
**Pull request by ManavPoddar**
## Description

Since there were no allergens for some languages, so Added a new dialog which asks the user whether he wants to change the language.

## Related issues and discussion
#1134 
 
 ## Screen-shots, if any
 
videotogif_2018 03 09_11 47 46

### CODE REVIEW

**Comment by ManavPoddar** [comment]
@teolemon  please take a look at this PR :)

**Comment by Karljoones** [comment]
I'm not sure that this is the best way of handling this. I have looked through the allergens list that has been added to the app recently and can confirm that there are no Hindi translations included in the list, as there were no translations included in the source where the list was gotten from. There definitely needs to be a solution to this, but I just do not think that this is the best way to do it

**Comment by ManavPoddar** [comment]
Hey @Karljoones, since there are no translations available, the app asks the users to download data for the translations. But again, after the download completes, the user is again  asked to download data. So I was thinking that we could notify the user about the unavailability of the allergens in his language. Shall I show a toast then instead of the dialog ? What do you suggest ?

**Comment by Karljoones** [comment]
@ManavPoddar I think that would be best. Default to English translations for now and let them know that there are no translations available

**Comment by ManavPoddar** [comment]
Opening a new PR, closing this one :)

**Pull request closed without merging**
