### PR TITLE
Fixes image issues + bottom bar

### LINKED ISSUE #2044: Enable contributors to select, rotate and crop images from product page on long press
Enable contributors to select, unselect, rotate and crop images from product page (in the summary, ingredients, nutrition tabs) on long press.
Enter an edit mode that enables to crop and rotate the current image, as well as select, rotate and crop one of the other images.
@PrajwalM2212 has already created a PR #2019  for a more general image selection tab that can be leveraged.

### LINKED ISSUE #2245: Add a bottom bar to home
image

### LINKED ISSUE #2386: java.lang.IllegalStateException  at openfoodfacts.github.scrachx.openfood.views.ContinuousScanActivity
```
java.lang.IllegalStateException: 
  at android.support.v4.app.FragmentManagerImpl.z (FragmentManagerImpl.java:40)
  at android.support.v4.app.FragmentManagerImpl.a (FragmentManagerImpl.java:2)
  at android.support.v4.app.BackStackRecord.a (BackStackRecord.java:71)
  at android.support.v4.app.BackStackRecord.d (BackStackRecord.java:1)
  at openfoodfacts.github.scrachx.openfood.views.ContinuousScanActivity$2.a (ContinuousScanActivity.java:1019)
  at openfoodfacts.github.scrachx.openfood.views.ContinuousScanActivity$2.a (ContinuousScanActivity.java:2)
  at io.reactivex.internal.operators.single.SingleDoOnSubscribe$DoOnSubscribeSingleObserver.a (SingleDoOnSubscribe.java:7)
  at io.reactivex.internal.operators.single.SingleObserveOn$ObserveOnSingleObserver.run (SingleObserveOn.java:14)
  at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run (HandlerScheduler.java:2)
  at android.os.Handler.handleCallback (Handler.java:873)
  at android.os.Handler.dispatchMessage (Handler.java:99)
  at android.os.Looper.loop (Looper.java:193)
  at android.app.ActivityThread.main (ActivityThread.java:6718)
  at java.lang.reflect.Method.invoke (Method.java)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:493)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:858)
```

### LINKED ISSUE #2395: Add a bottom bar to the scanner
Add a bottom bar to the scanner, like we did on iOS

image

### LINKED ISSUE #2397: Add bottom bar to the Allergen alert
image

### LINKED ISSUE #2614: java.lang.IllegalStateException  openfoodfacts.github.scrachx.openfood.views.ContinuousScanActivity$2.a
```
java.lang.IllegalStateException: 
  at android.support.v4.app.FragmentManagerImpl.z (FragmentManagerImpl.java:40)
  at android.support.v4.app.FragmentManagerImpl.a (FragmentManagerImpl.java:2)
  at android.support.v4.app.BackStackRecord.a (BackStackRecord.java:70)
  at android.support.v4.app.BackStackRecord.d (BackStackRecord.java:1)
  at openfoodfacts.github.scrachx.openfood.views.ContinuousScanActivity$2.a (ContinuousScanActivity.java:927)
  at openfoodfacts.github.scrachx.openfood.views.ContinuousScanActivity$2.a (ContinuousScanActivity.java:2)
  at io.reactivex.internal.operators.single.SingleDoOnSubscribe$DoOnSubscribeSingleObserver.a (SingleDoOnSubscribe.java:7)
  at io.reactivex.internal.operators.single.SingleObserveOn$ObserveOnSingleObserver.run (SingleObserveOn.java:14)
  at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run (HandlerScheduler.java:2)
  at android.os.Handler.handleCallback (Handler.java:873)
  at android.os.Handler.dispatchMessage (Handler.java:99)
  at android.os.Looper.loop (Looper.java:214)
  at android.app.ActivityThread.main (ActivityThread.java:6981)
  at java.lang.reflect.Method.invoke (Method.java)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:493)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1445)
```
image

### LINKED ISSUE #2616: Image rotation crashes without throwing any exception in LogCat
Image rotation crashes without throwing any exception in LogCat.
1. Edit mode
2. Click on front image
3. Rotate
4. Validate
5. Screen flash

### LINKED ISSUE #2618: Disable crop in the "Take more photo" button on the Summary tab
- [ ] Disable crop in the "Take more photos" button on the Summary tab. 
- [ ] Add a new button called "Send new front picture" to send a new front picture (with crop)

### PR DESCRIPTION
**Pull request by deniger**
## Description
Fix several issues with images: 
- add edit button to crop, rotate fix #2618
- remove crop step while uploading a new photo
- fix bug with scan activity

## Fixes
- Fix #2614
- Fix #2397
- Fix #2395
- Fix #2245
- Fix #2616
- Fix #2386
- Fix #2044

Add bottom navigation on several screens.

### CODE REVIEW

**Comment by teolemon** [comment]
image

**Comment by teolemon** [comment]
image
In some cases

**Comment by teolemon** [comment]
rebuilt, everything now looks good.

**Comment by teolemon** [comment]
Ok, tried uploading a product without setting any explicit language
image
We should probably have a prompt for the language if not set, instead of sending null

**Comment by deniger** [comment]
It s a new product? I ll fix asap


---- On Wed, 22 May 2019 17:47:00 +0200 notifications@github.com wrote ----



Ok, tried uploading a product without setting any explicit language

We should probably have a prompt for the language if not set, instead of sending null

**Comment by teolemon** [comment]
Yup, a bottle of lemonade. When life gives me lemonade, I usually scan it.

**Comment by deniger** [comment]
Is it possible to choose the user language by default?


---- On Wed, 22 May 2019 18:07:35 +0200 notifications@github.com wrote ----



Yup, a bottle of lemonade. When life gives me lemonade, I usually scan it.

**Comment by teolemon** [comment]
Yup, we can either make assumptions, or have a "Default language for new products" setting ?

**Comment by teolemon** [comment]
thanks for the very fine work @deniger 👌

**Pull request merged**
