### PR TITLE
Fixed #1230 : Create Adaptive Icon

### LINKED ISSUE #1230: Adaptative icons
We're not quite there yet. 
image
image
image

### PR DESCRIPTION
**Pull request by PrajwalM2212**
## Description

Created Adaptive Icon for Android O

## Related issues and discussion
#1230 

Before  
screenshot_1522774397
screenshot_1522774408
screenshot_1522774422
screenshot_1522774433

After 
screenshot_1522774513
screenshot_1522774503
image
screenshot_1522774494

### CODE REVIEW

**Comment by PrajwalM2212** [comment]
@teolemon @ross-holloway94 @Karljoones Is this what you wanted ?

**Comment by PrajwalM2212** [comment]
Can this PR be reviewed  ?

**Comment by PrajwalM2212** [comment]
@Karljoones  These icons were auto generated from Android Studio . I doubt i can do anything  to improve .

**Comment by Karljoones** [comment]
@PrajwalM2212 ah okay, I think maybe we will leave this for now and not implement it. It may be best just to wait for someone to design the icons to be the correct size and shapes.

**Comment by Karljoones** [comment]
I'm going to close this for now. I think when we make these, we will need to remake the icon completely to ensure that it looks consistent. I appreciate your work though! Sorry we are not merging this one.

**Pull request closed without merging**
