### PR TITLE
Added new camera icon for #388

### PR DESCRIPTION
**Pull request by Karljoones**
ic_add_a_photo_white_24dp added

### CODE REVIEW

**Comment by Karljoones** [comment]
Closed due to duplicate with merge #404, issues had not been closed accordingly.

**Comment by teolemon** [comment]
@Karljoones Not quite sure why no pull request ?
image

**Comment by Karljoones** [comment]
@teolemon I noticed that PR #404 refers to these issues and the icons. It also refers to issue #387, #388 and #389. The issues just were not closed or assigned. @naofum can you confirm that the correct icons are included in your PR?

**Comment by teolemon** [comment]
@Karljoones Can you fix the conflict on PR #404 as you see fit, and merge it ?

**Comment by Karljoones** [comment]
@teolemon I'll try my best to have a look at it today. Will update when working on it.

**Pull request closed without merging**
