### PR TITLE
Adds tests for home fragment

### PR DESCRIPTION
**Pull request by samagra14**
## Description

This is an attempt to begin the testing suite of the app. Currently, MainActivity cannot be tested due to a lot of interconnected Idling resources, therefore I am slightly modifying the main activity to make it fit for testing.
Besides this, I have added a FragmentTestActivity for the testing of a single fragment. I have added the test for the HomeFragment. I will be adding more espresso tests for the other fragments as well. 

* Modified MainActivity to make it fit for testing
* Added a FragmentTestActivity for testing individual fragments
* A small test for HomeFragment

I am also planning to open a discussion issue regarding MVVM and testing instructions for the app.

## Related issues and discussion
NA
 ## Checklist
 
Make sure you've done all the following (You can delete the checklist before submitting)
 
 - [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.
 - [x] Code is well documented
 - [x] Include unit tests for new functionality
 - [x] All user-visible strings are made translatable
 - [x] Code passes Travis builds in your branch
 - [x] If you have multiple commits please combine them into one commit by squashing them.
 - [x] Read and understood the contribution guidelines .

### CODE REVIEW

**Comment by samagra14** [comment]
@Karljoones @teolemon 
Please provide your views here.

**Comment by teolemon** [comment]
Tiny conflict to solve @samagra14

**Comment by teolemon** [comment]
poke @samagra14

**Comment by samagra14** [comment]
@teolemon I am writing a few more tests. I have to make a lot of changes to make them pass. I have set up a local Travis agent. I am trying to pass the build there. As soon as I am finished I will push the code along with the additional tests.

**Comment by teolemon** [comment]
Can you rebase on latest trunk ? It should fix the build.

**Comment by Karljoones** [comment]
@samagra14 is there any update on this?

**Comment by Karljoones** [comment]
Closing this for now, feel free to reopen when you have the opportunity to do more work with this

**Pull request closed without merging**
