### PR TITLE
Fixes #1097 App will not crash when language is changed Modified Pref…

### LINKED ISSUE #1097: Clicking on 'Preferences' crashes the app when language is changed to Hindi
**Checklist**
- [x] Bug Report - The issue you are reporting might be there already. Please search on the [issues tracker](https://github.com/openfoodfacts/openfoodfacts-androidapp/issues) before creating or reporting an issue.
- [x] Before reporting, please ensure (if you can) that you have tested it with the latest (dev) version of the software.
- [x] Don't forget to tag your issue, it makes it easier to discover.

**Summary:** 
When using the app in Hindi language and trying to go to the preferences screen the app crashes.

**Steps to reproduce:** 
Change the app language to Hindi, Open the Nav Drawer and click on the preferences option (the one with the settings icon). 

**Expected behavior:** 
Preferences screen should have been displayed.

**Observed behavior:** 
The app crashes.

### PR DESCRIPTION
**Pull request by vaishali51**
…erencesFragment.java

## Description

App crashes when language is changed in Preferences. Here is my contribution for this issue.

##
#1097
 
 ## 
screenshot_2018-03-04-14-40-06-451_openfoodfacts github scrachx openbeauty

 
 ##

### CODE REVIEW

**Comment by Karljoones** [comment]
Does this issue occur with the latest code?

**Comment by vaishali51** [comment]
Yes, this issue is still open.

**Comment by vaishali51** [comment]
Changes made :)

**Comment by Karljoones** [comment]
Does this issue still occur on the latest code?

**Pull request closed without merging**
