### PR TITLE
Show reload taxonomies option in preferences if local data is empty

### LINKED ISSUE #2941: Better handle JSON issues
image

### PR DESCRIPTION
**Pull request by ripetrescu**
Fixes #2941

Signed-off-by: Rares Petrescu <petrescu.rares@gmail.com>

## Description

- Display "Load ingredient detection data" if there is no analysis tag config stored in local db.
   If user selects it, it will reload the taxonomies using the LoadTaxonomiesService.

- gradle ++

### CODE REVIEW

**Comment by ripetrescu** [comment]
Screenshot_1576592041
Screenshot_1576592049

**Comment by ripetrescu** [comment]
Screenshot_1576592525

**Comment by ripetrescu** [comment]
@teolemon  I was thinking to have a permanent option in settings to fetch taxonomies manually, not only when ingredient analysis data is broken. This way, if by any reason the taxonomies are broken on server and device didn't store them, user can manually recheck to pull again. What do you think?

**Comment by teolemon** [comment]
It would be a good idea probably.

**Comment by teolemon** [comment]
Thank you @ripetrescu 👍 
merged

**Pull request merged**
