### PR TITLE
fixed #1162-Issues with timestamps in History

### LINKED ISSUE #1162: Issues with timestamps in History
image

- no space after numeric value
- the translatable string is "minutes ago". 5 minutes ago. But in French for instance, we must say: "Il y a 5 minutes" >> include a placeholder for the number in the string

### PR DESCRIPTION
**Pull request by iml-v**
## Description
fixed #1162  Issues with timestamps in Histor
 
 ## Screen-shots, if any
1.  
screenshot_20180308-230127 1

2.
 screenshot_20180309-064812 1

### CODE REVIEW

**Comment by iml-v** [comment]
@teolemon  Please review this  PR #1172

**Comment by l-o-b-s-t-e-r** [comment]
But you fixed only the first issue: "no space after numeric value"
What about the second: the translatable string is "minutes ago". 5 minutes ago ?

**Comment by iml-v** [comment]
@l-o-b-s-t-e-r i didn't get it what @teolemon  want to say because the format is for all language ```Text = String.valueOf(time) +" "+ mActivity.getString(R.string.id);```  how it can be different for different language like as said for french "5 minutes ago" --> "Il y a 5 minutes" . if you understand then Pls explain here .

**Comment by jaztriumph** [comment]
@iml-v time should be displayed as '1 minute ago' not  '1 minutes ago' same with hours and seconds.

**Comment by l-o-b-s-t-e-r** [comment]
I could be wrong, but I guess it should look like this:
Lets consider situation for "minutes" (for days, hours and seconds will be the same)
1) Open default strings.xml and add
<string name="minutes_ago_placeholder">%d minutes ago</string>
2) Open french string.xml and add
t<string name="minutes_ago_placeholder">Il y a %d minutes</string>
3) Open HistoryListAdapter and change
from String.valueOf(minutes) + mActivity.getString(R.string.minutes_ago);
to mActivity.getString(R.string.minutes_ago_placeholder, minutes);

here is explanation what is "%d" and how it works: https://docs.oracle.com/javase/tutorial/java/data/numberformat.html

Also I would suggest you to use [plurals](https://developer.android.com/guide/topics/resources/string-resource.html#Plurals)

**Comment by iml-v** [comment]
thanks a lot @l-o-b-s-t-e-r

**Comment by iml-v** [comment]
@teolemon i have done changes ,have a look a at this #1172

**Comment by l-o-b-s-t-e-r** [comment]
Apparently, you don't like plurals :D

**Comment by iml-v** [comment]
@l-o-b-s-t-e-r yeah you can say 😃 but i tried to implement that i was getting error so i have not done that part ```FATAL EXCEPTION: main
                                                                                     Process: openfoodfacts.github.scrachx.openfood, PID: 4192
                                                                                     android.content.res.Resources$NotFoundException: Plural resource ID #0x7f0e0002 quantity=32 item=other
                                                                                         at android.content.res.ResourcesImpl.getQuantityText(ResourcesImpl.java:268)
                                                                                         at android.content.res.Resources.getQuantityText(Resources.java:362)
                                                                                         at android.content.res.Resources.getQuantityString(Resources.java:438)
                                                                                         at openfoodfacts.github.scrachx.openfood.views.adapters.HistoryListAdapter.calcTime(HistoryListAdapter.java:93)```

**Comment by l-o-b-s-t-e-r** [comment]
Did you set quantity="other"?

**Comment by iml-v** [comment]
yes i did 
    ```<item quantity="one">%d second ago</item>```
      ```<item quantity="other">%d seconds ago</item>```

**Comment by Karljoones** [comment]
@iml-v try using a string resource and inserting the quantity into it, example:
`<string name="whatever">%1$d %2$s ago</string>` and then do `getString(R.string.whatever, second, getResources().getPlurals(R.plurals.second, second));`. Might solve your issue

**Comment by teolemon** [comment]
@iml-v @Karljoones just fixed tiny conflicts ? Is it ok to merge ?

**Comment by ManavPoddar** [comment]
thanks @Karljoones, it worked :)

**Comment by iml-v** [comment]
@Karljoones thanks

**Comment by iml-v** [comment]
@teolemon ,@ManavPoddar also have sent PR for plurals ,i will create conflicts i was also making changes for plurals

**Comment by Karljoones** [comment]
Hi @iml-v, #1094 was merged due to being created at an earlier date. Can you have a look to see if this resolve the issue, and if it does, can we close this?

**Comment by iml-v** [comment]
@Karljoones  it does not resolve issue @teolemon  second point was ```the translatable string is "minutes ago". 5 minutes ago. But in French for instance, we must say: "Il y a 5 minutes" >> include a placeholder for the number in the string``` so for that we have make changes for all locale

**Comment by Karljoones** [comment]
You're right, it doesn't. But the string `last_seen_string` will need to be translated by the translators, once this is translated it will read correctly and the plurals will need to be translated :)

**Comment by iml-v** [comment]
@Karljoones IMO we have add plurals for all language why see below otherwise it will not translatable in other language ,
```<plurals name="seconds_plural">
    <item quantity="one">सेकण्ड्</item>
    <item quantity="other">सेकण्ड्स</item>
  </plurals>
  <plurals name="minutes_plural">
    <item quantity="one">मिनट</item>
    <item quantity="other">मिनट्स</item>
  </plurals>
  <plurals name="hours_plural">
    <item quantity="one">घंटा </item>
    <item quantity="other">घंटे</item>
  </plurals>
  <plurals name="days_plural">
    <item quantity="one">दिन</item>
    <item quantity="other">दिन</item>
  </plurals>```

**Comment by iml-v** [comment]
@Karljoones if that is ok with you then you can close this 👍

**Comment by Karljoones** [comment]
They will be translated by the translators, we just have to sit tight and wait for them to do it! Thanks for all the work that you done in this PR and sorry that we are not merging the code!

**Pull request closed without merging**
