### PR TITLE
Add option to add a product if there are no search results

### LINKED ISSUE #477: Add a promo to add a product if there are no search results.
Add a promo to add a product if there are no search results (either by barcode or by scan)

### PR DESCRIPTION
**Pull request by huzaifaiftikhar**
## Description

Add option to add a product if there are no search results. Earlier there was no option to add a product if there were no search results. 

## Related issues and discussion
Fixes #477 
 
 ## Screen-shots, if any
screenshot_20180217-193651 
 ## Checklist
 
 Please make sure these boxes are checked before submitting your pull request - thanks!
 
 
 
 - [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.
 
 - [x] If you have multiple commits please combine them into one commit by squashing them.
 
 - [x] Read and understood the contribution guidelines .

### CODE REVIEW

**Comment by policorn** [comment]
Hi @huzaifaiftikhar, I've tested it searching with the home search and works as requested. 

The _add product option_ is not shown when searching by barcode though. Would it be possible to add this fallback option to it as well? @teolemon would it be the desired behavior?

**Comment by huzaifaiftikhar** [comment]
@policorn There is already an option to add product if *search by barcode* is not able to find the product on the database and the barcode is valid. 

#### Screenshots 
screenshot_20180218-151457

**Comment by policorn** [comment]
Hi @huzaifaiftikhar, my bad. It works as expected. I've also tested the resulting version (merged with the current HEAD commit) and it works ok.

**Comment by policorn** [comment]
Hi @teolemon, this one can be merged

**Comment by teolemon** [comment]
Merged, thanks @huzaifaiftikhar

**Pull request merged**
