### PR TITLE
Update OpenFoodAPIService.java

### PR DESCRIPTION
**Pull request by teolemon**
## Description

Describe the changes made and why they were made instead of how they were made.

## Related issues and discussion
#fixes {Issue Number}
 
 ## Screen-shots, if any
 
 ## Checklist
 
Make sure you've done all the following (You can delete the checklist before submitting)
 
 - [ ] Apply the `AndroidStyle.xml` style template to your code in Android Studio.
 - [ ] Code is well documented
 - [ ] Include unit tests for new functionality
 - [ ] All user-visible strings are made translatable
 - [ ] Code passes Travis builds in your branch
 - [ ] If you have multiple commits please combine them into one commit by squashing them.
 - [ ] Read and understood the contribution guidelines .

### CODE REVIEW

**Comment by deniger** [comment]
Maybe we could use this approach ( add an interceptor):
https://futurestud.io/tutorials/retrofit-add-custom-request-header

here: openfoodfacts.github.scrachx.openfood.utils.Utils#HttpClientBuilder

**Comment by teolemon** [comment]
Also, my code is duplicated. I stopped because I felt I was duplicating a lot of things.

**Comment by huzaifaiftikhar** [comment]
This cannot be merged as it is since the changes you have made in those methods are not reflected in the classes where they are actually used. The code won't compile this way. @deniger's method seems more appropriate.

**Comment by Karljoones** [comment]
Closing this for now

**Pull request closed without merging**
