### PR TITLE
OBF and OPFF ingredient analysis support

### PR DESCRIPTION
**Pull request by teolemon**
This PR tries to enable ingredient analysis support on Open Beauty Facts and Open Pet Food Facts, since we now parse ingredients there, and vegan, veggie and palm oil status make sense for both. 
I'm also pondering enabling additional ingredient detections for Open Beauty Facts.

### CODE REVIEW

**Comment by teolemon** [comment]
@VaiTon regarding the changes you made. Should I undraft the PR. It wasn't yet working on my last commit

**Comment by VaiTon** [comment]
> 
> 
> @VaiTon regarding the changes you made. Should I undraft the PR. It wasn't yet working on my last commit

What doesn't work?

**Comment by teolemon** [comment]
I didn't see the Vegan/Vegetarian analysis squares.

**Comment by VaiTon** [comment]
@teolemon what needs to be done here now that analysis is displayed?

**Comment by teolemon** [comment]
Nothing. We can merge if the modals appear correctly on clicking on the grey buttons. The rest of the work will be server side.

**Pull request merged**
