### PR TITLE
fix #704 (Added BottomNavigationView - Draft)

### LINKED ISSUE #704: Add a bottom navigation
image

- Language switching of the product
- Share button
- Jump to sections of the product
- Save product to a list

### PR DESCRIPTION
**Pull request by abhinavbajpai2012**
**Description**
Added BottomNavigationView to product_activity

**Related Issue**
#704
 
**Screen Shot**
 
screenshot_2018-02-15-00-36-20-778_openfoodfacts github scrachx openbeauty

 

-  [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.
 
 - [x] If you have multiple commits please combine them into one commit by squashing them.
 
 - [x] Read and understood the contribution guidelines .

### CODE REVIEW

**Comment by itchix** [comment]
It's a draft? Still in WIP?

**Comment by teolemon** [comment]
It's still a draft.

**Comment by policorn** [comment]
Hi @teolemon @abhinavbajpai2012 should I evaluate this one for merging? or still a WIP?

**Comment by Karljoones** [comment]
I'm going to close this due to inactivity, we can reopen if there is work done with it :)

**Pull request closed without merging**
