### PR TITLE
Update codestyle to be aligned with official kotlin style

### PR DESCRIPTION
**Pull request by naivekook**
####  Description
After opening the project in AS Arctic Fox I'm getting the next warning about style. So I updated codestyle to be aligned with official kotlin style.

#### Screenshots
Screen Shot 2021-04-08 at 10 45 38

### CODE REVIEW

**Comment by VaiTon** [comment]
I would prefer to postpone this until Artic Fox gets at least into beta.

**Comment by naivekook** [comment]
Makes sense
Also if we want to automate code style or add some static analyze we can look at ktlint and detekt

**Comment by VaiTon** [comment]
> Makes sense
> Also if we want to automate code style or add some static analyze we can look at ktlint and detekt

The Ideal solution would be to do this. Also using github actions to run this on PRs.

**Comment by teolemon** [comment]
@naivekook @VaiTon Isn't that the case now ? (Artic Fox)

**Pull request merged**
