### PR TITLE
Fixed #1214: Missing commas between brands ,EMB Code

### LINKED ISSUE #1214: Missing commas between brands

### PR DESCRIPTION
**Pull request by iml-v**
## Description
#1214 fixes Missing commas between brands & also in  EMB Code

## Related issues and discussion
#1214

### CODE REVIEW

**Comment by ManognaMutyala** [comment]
@iml-v  Are you sure that it doesn't append a comma after the last element too?

**Comment by iml-v** [comment]
@ManognaMutyala  thanks for noticing error ,i have not noticed this ,yes it will ,i will correct it

**Comment by iml-v** [comment]
@Karljoones  wait I am just updating code

**Comment by Karljoones** [comment]
@iml-v No worries, take your time :)

**Comment by iml-v** [comment]
@Karljoones  updated 
screenshot_20180312-171808 1

**Comment by Karljoones** [comment]
Great! Thank you. I noticed while looking at it there seems to be a space after the tags and before the comma, `Brand , brand`. Could you call the `trim()` on the items before putting them in the clickable? I know this is technically a different issue, but would make sense to include it in here. Would you mind looking into this? If you don't want to it's no problem and we can just merge this :)

**Comment by teolemon** [comment]
Ok, merging. Thanks @iml-v

**Comment by teolemon** [comment]
@iml-v Can you open an issue about what @Karljoones reviewed about trimming ?

**Comment by iml-v** [comment]
@teolemon i will solve this in next PR without opening an issue separately  ,thanks

**Pull request merged**
