### PR TITLE
Modified text view in CalculateDetails

### PR DESCRIPTION
**Pull request by Rutvikmodi**
## Description

Changed the Text View in CalculateDetails to "Nutrition facts table for xx g of this product"

### CODE REVIEW

**Comment by teolemon** [comment]
This is the bug currently in prod
```java.lang.RuntimeException: 
  at android.app.ActivityThread.performLaunchActivity (ActivityThread.java:2423)
  at android.app.ActivityThread.handleLaunchActivity (ActivityThread.java:2483)
  at android.app.ActivityThread.access$900 (ActivityThread.java:157)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1351)
  at android.os.Handler.dispatchMessage (Handler.java:102)
  at android.os.Looper.loop (Looper.java:148)
  at android.app.ActivityThread.main (ActivityThread.java:5477)
  at java.lang.reflect.Method.invoke (Method.java)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:726)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:616)
Caused by: java.util.UnknownFormatConversionException: 
  at java.util.Formatter$FormatSpecifierParser.unknownFormatConversionException (Formatter.java:2321)
  at java.util.Formatter$FormatSpecifierParser.advance (Formatter.java:2315)
  at java.util.Formatter$FormatSpecifierParser.parseConversionType (Formatter.java:2394)
  at java.util.Formatter$FormatSpecifierParser.parseArgumentIndexAndFlags (Formatter.java:2365)
  at java.util.Formatter$FormatSpecifierParser.parseFormatToken (Formatter.java:2298)
  at java.util.Formatter.doFormat (Formatter.java:1071)
  at java.util.Formatter.format (Formatter.java:1042)
  at java.util.Formatter.format (Formatter.java:1011)
  at java.lang.String.format (String.java:1554)
  at android.content.res.Resources.getString (Resources.java:430)
  at android.content.Context.getString (Context.java:436)
  at openfoodfacts.github.scrachx.openfood.views.product.CalculateDetails.onCreate (CalculateDetails.java)
  at android.app.Activity.performCreate (Activity.java:6445)
  at android.app.Instrumentation.callActivityOnCreate (Instrumentation.java:1108)
  at android.app.ActivityThread.performLaunchActivity (ActivityThread.java:2376)
  at android.app.ActivityThread.handleLaunchActivity (ActivityThread.java:2483)
  at android.app.ActivityThread.access$900 (ActivityThread.java:157)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1351)
  at android.os.Handler.dispatchMessage (Handler.java:102)
  at android.os.Looper.loop (Looper.java:148)
  at android.app.ActivityThread.main (ActivityThread.java:5477)
  at java.lang.reflect.Method.invoke (Method.java)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:726)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:616)```

**Comment by Karljoones** [comment]
@teolemon is that crash related to this PR, or has it been solved?

**Comment by teolemon** [comment]
It should probably solve it. Haven't tested the code.

**Comment by Karljoones** [comment]
Merged, thanks @Rutvikmodi

**Pull request merged**
