### PR TITLE
Autocancel CodeQL

### PR DESCRIPTION
**Pull request by teolemon**

### CODE REVIEW

**Comment by VaiTon** [comment]
Why should we cancel it?

**Comment by teolemon** [comment]
I got 150 Crowdin related builds yesterday in a branch. As the result, the release was queued, with hours to potentially wait.

**Comment by VaiTon** [comment]
I would prefer if we just disable CI for the l10n branches

**Comment by teolemon** [comment]
@VaiTon LGTM. I'll close this PR.

**Pull request closed without merging**
