### PR TITLE
Fixed #439 : Disable the dropdown

### LINKED ISSUE #439: Disable the drowdown
https://github.com/mikepenz/MaterialDrawer/blob/develop/FAQ/accountheader_single_profile_without_dropdown.md

### PR DESCRIPTION
**Pull request by PrajwalM2212**
## Description

The dropdown has been disabled

## Related issues and discussion
#439 
 
## Screen Shots
d

### CODE REVIEW

**Comment by teolemon** [comment]
@Karljoones afterthoughs ? What's inside currently bugs for me. And Multiaccount is not very useful. I think we'll handle multiple people for the allergen detector, but directly in allergens.

**Comment by Karljoones** [comment]
@teolemon I agree with this, it should be removed if it is not used. Plus the manage account button does not even work in there. Though if you did want to keep it, we could make sure that the manage account button works and move the logout button into the space that is there rather than having it as a menu item in the main menu. Up to you, at the moment though it is completely useless

**Comment by teolemon** [comment]
I'm not sure how signing would work if we moved all user management to the top

**Comment by Karljoones** [comment]
@teolemon could be tricky, let's merge this PR for now, that is something that can be added later

**Comment by teolemon** [comment]
Merged. Thanks @PrajwalM2212 @Karljoones :)

**Pull request merged**
