### PR TITLE
Fixes #2260 : App tagline is displayed in English when the language i…

### LINKED ISSUE #2260: App tagline is displayed in English when the language is set to Hindi in Home
**Summary:** 

Though we have tagline translation in Hindi which is well displayed in splash activity, it is being displayed in English in Home when the app language is set to Hindi.

**Screenshots:**

hindi2
hindi1

### PR DESCRIPTION
**Pull request by balaji-ramavathu**
…s set to Hindi in Home

## Description

Tagline is translated to Hindi

#fixes #2260

### CODE REVIEW

**Comment by teolemon** [comment]
@balaji-ramavathu 
However: 
- can you use https://translate.openfoodfacts.org in the future ?
- can you tweak it to say that it's open ?

**Comment by balaji-ramavathu** [comment]
Yeah sure, didn't know it before :-P

**Comment by Karljoones** [comment]
@balaji-ramavathu it would need to say 'open' rather than 'free'

**Comment by Karljoones** [comment]
Closing this off as this needs to be done via translate.openfoodfacts.org

**Pull request closed without merging**
