### PR TITLE
Fixed #1238, fixes #1240 : Translation Issues

### LINKED ISSUE #1238: Remove Fastscroller placeholder strings from translatable strings.
Remove Fastscroller placeholder strings from translatable strings. They have reappeared.

```
+  <string name="connection">Connected</string>
+  <string name="fastscroller_track">FastScroller track</string>
+  <string name="fastscroller_handle">FastScroller handle</string>
```

### LINKED ISSUE #1240: Remove image resolutions from translatable strings
Remove image resolutions from translatable strings

### PR DESCRIPTION
**Pull request by PrajwalM2212**
## Description

Fixed translation issues 

## Related issues and discussion
#1238 
#1240

### CODE REVIEW

**Comment by Karljoones** [comment]
Hi @PrajwalM2212 in terms of #1238, we are looking to remove these strings all together. Can you check if these are used in code, and if not, remove them completely from the project? The image resolution strings are perfect.

**Comment by PrajwalM2212** [comment]
@Karljoones Should i remove it from only the main strings.xml ?

**Comment by Karljoones** [comment]
@PrajwalM2212 Yes please, as far as I am aware, this will remove it from all of the rest through the translation service. Please run a check though to ensure that this is not used anywhere in the code as we do not want it to cause an issue :)

**Comment by Karljoones** [comment]
Thanks @PrajwalM2212, just waiting for the build to finish. Sound be okay to merge :)

**Comment by Karljoones** [comment]
Merged, thanks @PrajwalM2212

**Pull request merged**
