### PR TITLE
external API URL

### LINKED ISSUE #113: Turn the API url into a variable
So that we can switch it from Open Food Facts to Open Beauty Facts easily.
https://ssl-api.openfoodfacts.org/
https://ssl-api.openbeautyfacts.org/

### PR DESCRIPTION
**Pull request by herau**
external API URL of open food facts in res/values/strings.xml
fix #113

### CODE REVIEW

**Comment by herau** [comment]
@teolemon i put the api url in the `strings.xml` file; are you ok with that ?

**Comment by teolemon** [comment]
My main concern is preparing the way for Open Beauty Facts (and possibly debug version for the Open Food Facts preprod)
The only caveat could be overzealous translators ?

**Comment by herau** [comment]
@teolemon i just push the commit 7b492fc, which set the string variable non translatable.

**Comment by teolemon** [comment]
Also, given my broad knowledge of Java, I'd rather leave non-trivial code-reviews to @itchix ;-)

**Pull request merged**
