### PR TITLE
Xml recyclerView improves

### PR DESCRIPTION
**Pull request by cliffgr**
## Description

tools:listitem / tools:listheader / tools:listfooter
Intended for: <AdapterView> (and subclasses like <ListView>)

Used by: Android Studio layout editor

These attributes specify which layout to show in the layout preview for a list's items, header, and footer. Any data fields in the layout are filled with numeric contents such as "Item 1" so that the list items are not repetitive.

For example:

<ListView xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    android:id="@android:id/list"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    **tools:listitem="@layout/sample_list_item"
    tools:listheader="@layout/sample_list_header"
    tools:listfooter="@layout/sample_list_footer"** />

 ## Screen-shots, if any

Editor without ListItem attribute 

screenw whitout listitem

Editor with  ListItem attribute 

screen with listitem

### CODE REVIEW

**Comment by PrajwalM2212** [comment]
@cliffgr Can you do all changes that involves "tools:" in one PR only . And then the next PR could be kept for anything else.

**Comment by cliffgr** [comment]
yes... sorry

**Comment by PrajwalM2212** [comment]
@cliffgr  Are you going to add more "tools:" attribute to other elements ?

**Comment by cliffgr** [comment]
No ... but i will check the project again tomorrow for more improvements

**Comment by PrajwalM2212** [comment]
@cliffgr Ok ...tgen this can be merged .

**Comment by PrajwalM2212** [comment]
@cliffgr The travis failed 3 times . Check if there is any problem in code.

**Comment by cliffgr** [comment]
hello  . i will check it

**Comment by cliffgr** [comment]
My gradle build successfully
`gradlew connectedOpfDebugAndroidTest --stacktrace`


> Task :app:greendao 
Kept source for 0 classes and 20 methods because of @Keep annotation

> Task :app:connectedOpfDebugAndroidTest 
Starting 4 tests on Nexus 5X - 8.1.0


BUILD SUCCESSFUL in 2m 39s
62 actionable tasks: 2 executed, 60 up-to-date
C:\Users\cliff\Desktop\Velti\openfoodfacts-androidapp>

**Comment by cliffgr** [comment]
I am now on travis in my job we work with jenkins

Seem the error on travis is general:

```
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received
```

**Comment by PrajwalM2212** [comment]
Thanks @cliffgr

**Pull request merged**
