### PR TITLE
Import ingredient

### PR DESCRIPTION
**Pull request by dobriseb**
## Description

Add the import of ingredient.json from server to tables "ingredient", "ingredientName" and "ingredientsRelation" in database on the device.
Import countries too.

## Related issues and discussion
#2055 
 
 ## Screen-shots, if any
 
 ## Checklist
 
Make sure you've done all the following (You can delete the checklist before submitting)
 
 - [X] Apply the `AndroidStyle.xml` style template to your code in Android Studio.
 - [X] Code is well documented
 - [ ] Include unit tests for new functionality
 - [X] All user-visible strings are made translatable
 - [ ] Code passes Travis builds in your branch
 - [ ] If you have multiple commits please combine them into one commit by squashing them.
 - [X] Read and understood the contribution guidelines .

### CODE REVIEW

**Comment by teolemon** [comment]
```
Caused by: org.gradle.api.GradleException: Failed to install the following Android SDK packages as some licences have not been accepted.
   build-tools;27.0.3 Android SDK Build-Tools 27.0.3
To build this project, accept the SDK license agreements and install the missing components using the Android Studio SDK Manager.
Alternatively, to transfer the license agreements from one workstation to another, see http://d.android.com/r/studio-ui/export-licenses.html
```

**Comment by teolemon** [comment]
@ripetrescu @dobriseb is there anything blocking this one ?

**Comment by dobriseb** [comment]
Oups, I've found some little comment to change... hold on

**Comment by dobriseb** [comment]
Don't understand why checks have failed.

**Comment by teolemon** [comment]
some rebasing @dobriseb

**Comment by dobriseb** [comment]
Replaced by #2367

**Pull request closed without merging**
