### PR TITLE
Hided ecoscore in OBF scan

### LINKED ISSUE #3746: OBF - Eco-Score displayed on the scan card for cosmetics
Eco-Score displayed on the scan card for cosmetics
image

### PR DESCRIPTION
**Pull request by mrudultora**
####  Description
Ecoscore will be visible in **"off"** only .

#### Related issues
Fixes #3746 

#### Related PRs
None

#### Screenshots
img

### CODE REVIEW

**Comment by VaiTon** [comment]
Compilation error, maybe you need to import `AppFlavors`

**Comment by mrudultora** [comment]
> Compilation error, maybe you need to import `AppFlavors`

@VaiTon Already imported.

**Comment by mrudultora** [comment]
@VaiTon Any suggestion, on how to resolve this ?

**Comment by VaiTon** [comment]
> 
> 
> @VaiTon Any suggestion, on how to resolve this ?

I don't think you have committed the imports. Are you really sure? Because I can't find them in the diff view.

**Comment by mrudultora** [comment]
> > @VaiTon Any suggestion, on how to resolve this ?
> 
> I don't think you have committed the imports. Are you really sure? Because I can't find them in the diff view.

Actually, it was imported from before because `AppFlavors` was used in this file previously. If possible, just see the lines _280_ and _287_. Therefore, they are not shown in diff view.

**Comment by VaiTon** [comment]
@mrudultora try to merge master into this branch

**Comment by VaiTon** [comment]
Hmm, the build still errors with "Cannot find AppFlavors"

**Comment by mrudultora** [comment]
@VaiTon I tried `assembleDebug` and it's working fine (getting warnings but no errors). Also, I am able to build and run the app. As I am unable to solve this, I am closing this PR.

**Comment by VaiTon** [comment]
Please don't. When I have some time I'm checking this.

**Pull request merged**
