### PR TITLE
Created PULL_REQUEST_TEMPLATE.md for new contributor

### PR DESCRIPTION
**Pull request by iml-v**
fix issue :#716  created PULL_REQUEST_TEMPLATE.md  with some instruction(what to do ) before sending PR ,for new contributor in project .

### CODE REVIEW

**Comment by iml-v** [comment]
@teolemon review this PR.

**Comment by teolemon** [comment]
@ross-holloway94 what do you think of it ?

**Comment by ross-holloway94** [comment]
@teolemon Mostly I agree with what is stated. I disagree with squashing the commits though - that will prevent you cherry-picking or reverting.

**Comment by iml-v** [comment]
@ross-holloway94  if someone have made many commits for the single task ,then it is good that he squash them  and make single commit ,for different issues it is not recommended , it's only when multiple commit for single issue .i would like to hear from you on this .

**Comment by ross-holloway94** [comment]
@iml-v In my opinion, issues should be separated into branches, and then commits can be left separate on that particular branch. I believe this is how @teolemon prefers it?

**Comment by iml-v** [comment]
@ross-holloway94 that is right (separated branches) but my point is that when we do multiple commit regarding single task then before sending PR squash them in single so the whole work can come in single commit .so now should i make changes in Template ? @ross-holloway94  @teolemon  .

**Pull request merged**
