### PR TITLE
Fixed #1213 Categories not clickable

### LINKED ISSUE #1213: Categories not clickable

### PR DESCRIPTION
**Pull request by shivanshsoni**
fixed issue #1213

### CODE REVIEW

**Comment by shivanshsoni** [comment]
@Karljoones OK I will change it. Give me some time :)

**Comment by Karljoones** [comment]
Thanks @shivanshsoni! Take your time and let us know when you are ready to have the PR reviewed

**Comment by Shubham2320** [comment]
@shivanshsoni you can use `ProductBrowsingListActivity` to show the list of Products.  Do check out how brands, additive, country are made clickable and please adopt the same method too.

**Comment by PrajwalM2212** [comment]
@Karljoones @Shubham2320 I am working on making categories open in recycler view.

**Comment by shivanshsoni** [comment]
Sure @Shubham2320 Thanks!

**Comment by Karljoones** [comment]
@shivanshsoni & @Shubham2320 in that case, are we going to close this PR?

**Comment by Shubham2320** [comment]
@Karljoones yeah that would be fair. @shivanshsoni please try some other issues as @PrajwalM2212  has already taken this one.

**Comment by shivanshsoni** [comment]
Ok if @PrajwalM2212 is working on this then I am closing this PR.

**Pull request closed without merging**
