### PR TITLE
Fixed #517: Splash screen fix for Open Food Facts

### LINKED ISSUE #517: Logo splash screen broken on tablets and some phones.
Splash screen broken on tablets. The logo is distorted and takes the whole screen.

### PR DESCRIPTION
**Pull request by amanjeetsingh150**
## Description

The splash screen logo was broken at some phones as already mentioned in the issue. So I spent some time searching and reading articles about making splash screen properly for android apps. Then I discovered about something called 9 Patch PNGs from here which stretch good for all resolutions:<br>
https://medium.com/@101/splash-screen-in-android-769d3b0bafd0
I went for the tool provided by Google to produce 9 patch images of the logo instead the one we were previously using and included them. And used them accordingly.

## Related issues and discussion
#517 
 
 ## Screen-shots, if any
Outputs for 2 phones
1. MOTO E Android Version 5.1
<b>This was before:</b>

<br>
<b>This was after:</b>

2. XIOMI MI Redmi Note 2 Android 5.0.2
<b>Before:</b>

<br>
<b>After:</b>

<br>
I have tested this for all devices available at my home. Do tell me if any more optimization needs to be done.

<b>I have done this for Open Food Facts flavor till now. If it convinces all the mentors I will send quick PR for other flavors too</b>
Thanks.

### CODE REVIEW

**Comment by amanjeetsingh150** [comment]
@teolemon @Karljoones Please review. Thanks :+1:

**Comment by Karljoones** [comment]
Hi @amanjeetsingh150 the image on the splash screen should not be stretched at all

**Comment by amanjeetsingh150** [comment]
@Karljoones sure sir will try to adjust bounds of the image and update my PR.

**Comment by Karljoones** [comment]
@amanjeetsingh150 it should look like this: https://github.com/openfoodfacts/openfoodfacts-resources/blob/master/images/svg/logos/openfoodfacts-logo-en.svg

**Comment by amanjeetsingh150** [comment]
@Karljoones sure sir on the way to update it :+1:

**Comment by amanjeetsingh150** [comment]
Here is the best optimization I could achieve after adjusting bounds.
These are examples<br>
1. <b> In Moto E Android Version 5.1</b>

<br>
2. <b> In Redmi Note 4:</b>


Hope to get some reviews on this.
@Karljoones  @teolemon  Please review. Thanks. :+1:

**Comment by jaztriumph** [comment]
@amanjeetsingh150 Travis build failed in 5 mins due to something related to splash screen on other flavors, I think you will need to implement this in all other flavors in this PR itself only then Travis will pass.

**Comment by amanjeetsingh150** [comment]
@jaztriumph Yes I will fix this and update the PR as soon I get the reviews form mentors.

**Comment by amanjeetsingh150** [comment]
@Karljoones @teolemon Should I finalize this and do it for all the flavors?

**Comment by Karljoones** [comment]
It seems like it is still a little stretched on the Moto E...

**Comment by amanjeetsingh150** [comment]
Hey @Karljoones yes sir I will update the PR quickly for all flavors and will try to fix that stretching.

**Comment by amanjeetsingh150** [comment]
@teolemon @Karljoones I have updated the PR and done the changes for all the flavors of the app. The stretched image has also been adjusted. Please do have a look and review for any further changes if required.
<b>Moto E</b><br>

**Comment by amanjeetsingh150** [comment]
@Karljoones should I close this and send new PR for this?

**Comment by Karljoones** [comment]
@amanjeetsingh150 I resolved some conflicts that were in the PR, but the travis build is still failing. Can you have a look at this?

**Comment by teolemon** [comment]
Can you rebase on latest trunk ? It should fix the build.

**Comment by Karljoones** [comment]
Hi @amanjeetsingh150 there has not been much activity on this, I'm going to close this for now but feel free to reopen it when you have a chance to have a look into it.

**Pull request closed without merging**
