### PR TITLE
Feature/650 category browser - PART 1

### PR DESCRIPTION
**Pull request by alikyo**
The first part contains the network call to categories endpoint, parsing and displaying the categories list.
Some improvement and new libraries are added within this PR:
RxJava : Reactive programming
Dagger : Dependency injection
Enabling data binding to migrate to MVVM
Upgrading dependencies.

demo

### CODE REVIEW

**Comment by alikyo** [comment]
I guess we should update Travis to follow up with android upgrade, no ?

**Comment by teolemon** [comment]
Requesting reviews from @herau @itchix and @jinqian who have experience with the codebase, and/or with Android good practises.

**Comment by itchix** [comment]
Wow big update :+1: 
I'll try to review it this week

**Comment by itchix** [comment]
There is some conflicts to resolve but it's ok for me :)

**Comment by teolemon** [comment]
@alikyo Can you change the SDK version in  .travis.yml in your branch so that the build can run ?

**Comment by alikyo** [comment]
Done

**Comment by teolemon** [comment]
@itchix have you built it on your device ?

**Comment by teolemon** [comment]
You will probably close #643

**Comment by alikyo** [comment]
Yes exactly

**Pull request merged**
