### PR TITLE
Fixes #565 Analyse lint errors 

### LINKED ISSUE #565: Analyse Linting Results
```
Ran lint on variant offRelease: 1179 issues found
Ran lint on variant obfDebug: 1178 issues found
Ran lint on variant opffRelease: 1184 issues found
Ran lint on variant obfRelease: 1178 issues found
Ran lint on variant offDebug: 1179 issues found
Ran lint on variant opffDebug: 1184 issues found
Wrote HTML report to file:///home/travis/build/openfoodfacts/openfoodfacts-androidapp/app/build/reports/lint-results.html
Wrote XML report to file:///home/travis/build/openfoodfacts/openfoodfacts-androidapp/app/build/reports/lint-results.xml```

### PR DESCRIPTION
**Pull request by samagra14**
## Description

This PR aims at solving linting errors.

## Related issues and discussion
#565

### CODE REVIEW

**Comment by teolemon** [comment]
@samagra14 Can you rebase it on latest trunk ? There's this error from previous trunk that makes it fail (the serbian folder)

**Comment by samagra14** [comment]
@teolemon I have rebased the branch.

**Comment by teolemon** [comment]
@policorn @ross-holloway94 @Karljoones up for review

**Comment by teolemon** [comment]
small conflict to solve before merging

**Comment by Karljoones** [comment]
Conflicts resolved and merged :)

**Pull request merged**
