### PR TITLE
states tag translation in contribution tab

### LINKED ISSUE #1497: Use the JSON states taxonomy to translate States
We now have a JSON export of the states for the contributor tab:
https://static.openfoodfacts.org/data/taxonomies/states.json
You can enable the contributor tab in the app settings.

### PR DESCRIPTION
**Pull request by kartikaysharma01**
####  Description
Used the JSON states taxonomy to translate States tags in contribution tab.
 ~~⚠Need to clear storage and restart the app because Taxonomy are loaded only at first start.~~ - Fixed.

#### Related issues

Fixes #1497 

#### Screenshots

For french,

image

For Estonian (translation not available in API)
image

### CODE REVIEW

**Comment by kartikaysharma01** [comment]
I have tried adding the create table and db version to ```OFFDatabaseHelper``` , but that doesn't seem to help with the SQLite Exception for table does not exist. 
@VaiTon can you please look into where the config for db version is maintained, I was unable to find that

**Comment by VaiTon** [comment]
> 
> 
> I have tried adding the create table and db version to `OFFDatabaseHelper` , but that doesn't seem to help with the SQLite Exception for table does not exist.
> @VaiTon can you please look into where the config for db version is maintained, I was unable to find that

It is in build.gradle.kts 🚀 

https://github.com/openfoodfacts/openfoodfacts-androidapp/blob/1bcc4b7d7fd77bb550aedc54a6360b1828e99fbd/app/build.gradle.kts#L347

**Comment by kartikaysharma01** [comment]
> > I have tried adding the create table and db version to `OFFDatabaseHelper` , but that doesn't seem to help with the SQLite Exception for table does not exist.
> > @VaiTon can you please look into where the config for db version is maintained, I was unable to find that
> 
> It is in build.gradle.kts 🚀
> 
> https://github.com/openfoodfacts/openfoodfacts-androidapp/blob/1bcc4b7d7fd77bb550aedc54a6360b1828e99fbd/app/build.gradle.kts#L347

Thanks @VaiTon . I have pushed the changes.

**Comment by VaiTon** [comment]
Thank you! 🎉

**Pull request merged**
