### PR TITLE
Add icons to Product Upload buttons (closes #387, #388, #389)

### LINKED ISSUE #387: Add this icon to the upload all button
https://material.io/icons/#ic_done_all

### PR DESCRIPTION
**Pull request by naofum**

### CODE REVIEW

**Comment by itchix** [comment]
Can I merge?

**Comment by herau** [comment]
@itchix do you test it ? if don't maybe ask a screenshot to @naofum to see the result

**Comment by naofum** [comment]
screenshot_2017-01-08-22-17-58
screenshot_2017-01-08-22-17-07

**Comment by teolemon** [comment]
@naofum There seems to be a padding issue.
The upload view would need to be fully reworked. The dropdown is counter intuitive.
A temporary solution could look like this, but @herau wants a more ambitious approach.

image

**Comment by teolemon** [comment]
More like this one:
image

**Pull request merged**
