### PR TITLE
Reenable a test that was failing in OpenFoodAPIServiceTest.java

### PR DESCRIPTION
**Pull request by teolemon**

### CODE REVIEW

**Comment by policorn** [comment]
Hi @teolemon, can you close this one? 😬

**Comment by teolemon** [comment]
@policorn This is a test that was failing. I don't know why. I disabled it but I feel guilty about disabling it.

**Comment by policorn** [comment]
Can I convert this into an issue instead?

**Comment by Karljoones** [comment]
I'm going to close this for now, can be reopened if it needs to be continued :)

**Pull request closed without merging**
