### PR TITLE
deleted new daosession

### LINKED ISSUE #1068: making getDaoSession() in OffApplicaiton static
**Checklist**
- [x] Bug Report - The issue you are reporting might be there already. Please search on the [issues tracker](https://github.com/openfoodfacts/openfoodfacts-androidapp/issues) before creating or reporting an issue.
- [x] Before reporting, please ensure (if you can) that you have tested it with the latest (dev) version of the software.
- [x] Don't forget to tag your issue, it makes it easier to discover.

**Summary:** 

`getDaoSession()` is not static .DaoSession is currently accessed from Utils which requires a Activity argument, so it cannot be accessed in several cases like when scheduling a job.

### PR DESCRIPTION
**Pull request by jaztriumph**
## Description

Made daoSession a singleton so that database deadlock does not occur.

## Related issues and discussion
closes #1068 #1072

### CODE REVIEW

**Comment by jaztriumph** [comment]
@Karljoones can you review this PR

**Comment by policorn** [comment]
@itchix @Karljoones; Ok with you to merge?

**Comment by Karljoones** [comment]
Good with me @policorn!

**Comment by policorn** [comment]
Merged! Thanks @jaztriumph!

**Pull request merged**
