### PR TITLE
fix: overlapping icon in LoginActivity

### LINKED ISSUE #4545: [UI] Login: overlapping icons in the password field
### What
If a password is incorrect, the field shows an error saying "This field is required".
However, this error produces two icons to overlap, as you can see here:

Screenshot_20220319_175307

### PR DESCRIPTION
**Pull request by FlorentRousselle**
fix : issue #4545

* changed id in LoginActivity.kt
* id added in activity_login.xml for textInputLayout

### CODE REVIEW

**Review by g123k — APPROVED** [review]
(The error is now displayed in the layout instead of the EditText like before)

LGTM!

**Comment by teolemon** [comment]
Small merge conflicts @FlorentRousselle @g123k

**Comment by FlorentRousselle** [comment]
fix : issue #4545
fix: merge conflicts for overlapping icon

Screenshot_20220324-095509

**Comment by teolemon** [comment]
Thank you @FlorentRousselle 👍  for the fix.
Merging.

**Pull request merged**
