### PR TITLE
Fixes #1264 exits the intro slides when swipe

### LINKED ISSUE #1264: It should be possible to slide out the intro slides
It should be possible to slide out the intro slides, from the last slide. Currently you have to move your finger to Okay.

### PR DESCRIPTION
**Pull request by PO15ON**
## Description

Describe the changes made and why they were made instead of how they were made.

## Related issues and discussion
Fixes #1264 exits the intro slides when swipe
 
 ## Screen-shots, if any
 
 ## Checklist
 
Make sure you've done all the following (You can delete the checklist before submitting)
 
 - [ ] Apply the `AndroidStyle.xml` style template to your code in Android Studio.
 - [ ] Code is well documented
 - [ ] Include unit tests for new functionality
 - [ ] All user-visible strings are made translatable
 - [ ] Code passes Travis builds in your branch
 - [ ] Read and understood the contribution guidelines .
- [ ] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Comment by Karljoones** [comment]
Hi @PO15ON would you like us to review this one of #1281? If it is this one, we will go ahead with closure of #1281

**Comment by Karljoones** [comment]
Also, can you have a look at why the build is failing?

**Comment by PO15ON** [comment]
#1281 is the same as this, sorry for making two PRs.
I don't know why it's failing in Travis, I haven't delt with travis before but the app is working well.

**Comment by Karljoones** [comment]
Thanks for confirming @PO15ON, the other PR is closed for now and we can concentrate on this one. I just had a look at the travis build and it's not failing due to something you done, just bear with us for the time being while we look into it

**Comment by PO15ON** [comment]
Take your time. Thanks.

**Comment by teolemon** [comment]
@Karljoones Can we merge this one, given it's not at fault ?

**Comment by Karljoones** [comment]
@PO15ON @teolemon merged :)

**Pull request merged**
