### PR TITLE
Fixes #519 Share icon is grey and of different size

### LINKED ISSUE #519: Share icon is grey while edit icon is black
On product view, the Share icon is grey while edit icon is black. They should both be black and the same size.

### PR DESCRIPTION
**Pull request by ManavPoddar**
## Description

The share action provider was causing problem. Because of it the size of share button was bigger. So used Intent.create chooser instead of the share action provider. Also changed the styles.xml file to make the share button black by defining rules for the toolbar secondry text color.

Now both the share button and edit icon are of same color and same size.
 
 ## Screen-shots, if any
 
screenshot_20180218-164338
screenshot_20180218-164346

### CODE REVIEW

**Comment by Karljoones** [comment]
Hi, this has already been resolved in PR #779, we are just waiting to merge it :)

**Comment by Karljoones** [comment]
@teolemon @ManavPoddar shall we close this as this was fixed in a recent merge?

**Comment by teolemon** [comment]
Yup, closing. 
Please ensure to look for opened bugs and PRs. It's a bit sad to have to discard duplicate work :-(

**Comment by Karljoones** [comment]
Sorry, @ManavPoddar but thank you for your work! Looking forward to seeing more pull requests from you.

**Pull request closed without merging**
