### PR TITLE
fix #2403, #2374 Nutrient name should always be visible in edit mode (even if we have a value)

### LINKED ISSUE #2403: Use TextInputLayout in all fields of the edit form
https://developer.android.com/reference/android/support/design/widget/TextInputLayout

### PR DESCRIPTION
**Pull request by deniger**
+ Use TextInputLayout to always display field name
+ Clean the fragment used to edit nutrient values by removing duplicate code
+ fix issues with value validation for nutrient

## Description

Describe the changes made and why they were made instead of how they were made.

## Related issues and discussion
#fixes 2403, 2374
 
 ## Screen-shots, if any
 
 ## Checklist
 
Make sure you've done all the following (You can delete the checklist before submitting)
 
 - [ ] Apply the `AndroidStyle.xml` style template to your code in Android Studio.
 - [ ] Code is well documented
 - [ ] Include unit tests for new functionality
 - [ ] All user-visible strings are made translatable
 - [ ] Code passes Travis builds in your branch
 - [ ] If you have multiple commits please combine them into one commit by squashing them.
 - [ ] Read and understood the contribution guidelines .

### CODE REVIEW

**Comment by teolemon** [comment]
- There are leftovers from the URL field in simplified mode (barcode and magnifying glass)
- The fields are not the same height
- A bit too much left margin for the field names, and perhaps not enough top margin as compared to the field

image

**Comment by deniger** [comment]
I will have a look tomorrow.
For the left margin of the field name: it s aligned with the text field edit zone ( the cursor). I can modify it but will have to modify the left padding of the edit text.



---- On Thu, 21 Mar 2019 17:06:53 +0100 notifications@github.com wrote ----


There are leftovers from the URL field in simplified mode (barcode and magnifying glass)
The fields are not the same height
A bit too much left margin for the field names, and perhaps not enough top margin as compared to the field

**Comment by deniger** [comment]
I review the points:

image

Note: I move the 2 images (scan and search) at the bottom of the link textfield. Is it ok for you ?

**Comment by teolemon** [comment]
I would have hidden completely the link field rather than showing it. The minimal mode aims at letting you compute the Nutri-Score and NOVA groups.

**Comment by deniger** [comment]
I'm not sure I get it all:)
How do you activate the minimal mode? Are we ok that in normal mode the link field should be visible ?
I only made tests in normal mode but in the code or seems that link field is hidden in minimal mode.


---- On Sat, 23 Mar 2019 17:02:30 +0100 notifications@github.com wrote ----



I would have hidden completely the link field rather than showing it. The minimal mode aims at letting you compute the Nutri-Score and NOVA groups.

**Comment by teolemon** [comment]
It's now the default mode, and the link should not be visible.

**Pull request merged**
