### PR TITLE
#fixes 1005 Product name as per the user language

### PR DESCRIPTION
**Pull request by shiv07tiwari**
## Description

Describe the changes made and why they were made instead of how they were made.

## Related issues and discussion
#fixes 1005
 Right now, added the feature only for product name, i need some help if this method is okay or should we do some changes in the api call only.
 ## Screen-shots, if any
 
 ## Checklist
 
Make sure you've done all the following (You can delete the checklist before submitting)
 
 - [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.
 - [x] Code is well documented
 - [x] Include unit tests for new functionality
 - [x] All user-visible strings are made translatable
 - [x] Code passes Travis builds in your branch
 - [x] If you have multiple commits please combine them into one commit by squashing them.
 - [x] Read and understood the contribution guidelines .

### CODE REVIEW

**Comment by teolemon** [comment]
@shiv07tiwari See the above screenshots: it doesn't display anything.

**Comment by shiv07tiwari** [comment]
I guess then we will have to modify the API @teolemon

**Comment by jinqian** [comment]
So what you are trying to do is currently not working, since the `getProductName` with language code method looks like this:
```
    public String getProductName(String languageCode) {
        if (additionalProperties.get("product_name_" + languageCode) != null) {
            return additionalProperties.get("product_name_" + languageCode)
                    .toString()
                    .replace("\\'", "'")
                    .replace("&quot", "'");
        }
        return null;
    }
```
While the API currently doesn't send any information in additional properties.

**Comment by shiv07tiwari** [comment]
@teolemon Kindly review and merge this PR.

**Comment by brandenfung** [comment]
Closed this PR as #1005 is fixed via #2163.

**Pull request closed without merging**
