### PR TITLE
Put more emphasis on NutriScore in ContinuousScanActivity

### LINKED ISSUE #2410: Put more emphasis on the Scores
image
Put more emphasis on the Scores, less on products details (brands and quantity)

### PR DESCRIPTION
**Pull request by VaiTon**
## Description

Describe the changes made and why they were made instead of how they were made.

## Related issues and discussion
Fixes #2410
 
### Before

Before

### After

After

### CODE REVIEW

**Comment by deniger** [comment]
while testing this PR, I notice a bug in the product fragment that is more visible with the bottom navigation bar.
Will fix it in other PR than go back to this one

**Comment by deniger** [comment]
@VaiTon  please could you fix the conflicts ? I tried via the web view but it's too complicate :(
we merged a pull fixing an issue with the bottom view in the scan activity.
Thanks

**Comment by VaiTon** [comment]
Sure

**Comment by VaiTon** [comment]
Done @deniger

**Comment by deniger** [comment]
**Before:**
image
**After**
image

It seems we lost some info ( wight, subtitle) and we have additives info

**Comment by deniger** [comment]
**Before**
image

**After**
image

**Comment by deniger** [comment]
**Before**
image

**After**
image

**Comment by deniger** [comment]
other point: nova icon is missing.
If you try [26033068](https://world.openfoodfacts.org/product/26033068/petit-pot-de-creme-au-caramel-milsa) we should see nova4. 
I didn't manage to find a product with co2 icon....

**Comment by deniger** [comment]
with 3560070573998  the CO2 icon is there 👍

image

but not he nova icon

**Comment by deniger** [comment]
@stephanegigandet  @teolemon 
for https://world.openfoodfacts.org/product/3175681116863/biscuit-sesame-saveur-vanille-gerble
What should be displayed ?  "no additives" ? Currently "Unknown additives" is displayed.

**Comment by teolemon** [comment]
If ingredient list is completed: no additives. 
If ingredient list is not completed: additives unknown

**Comment by deniger** [comment]
@VaiTon 
Ok so for product 3302749508029 we should see no additives
image

but fot product 3175681116863 we should see additives unknown

**Comment by VaiTon** [comment]
@deniger all done

**Comment by VaiTon** [comment]
@stephanegigandet @deniger is there any problem with the build?

**Comment by deniger** [comment]
@VaiTon  could you fix the conflicts ?

**Comment by deniger** [comment]
Results are ok for me  :

image

image
image

image
image

**Comment by deniger** [comment]
@VaiTon  is it possible to make the nova/co2 aligned:

image

**Comment by deniger** [comment]
Warning: there is an issue with the CO2 ( reported by @teolemon in https://github.com/openfoodfacts/openfoodfacts-androidapp/issues/2695):
if no ingredient no co2 icon should be displayed.

Try with the product 20211394
image

**Comment by VaiTon** [comment]
> @VaiTon is it possible to make the nova/co2 aligned ( horizontally and vertically):
> 
> image

I'm sorry but I can't seem to understand

Also found that when nova is present but nutriscore is not additives will be displayed in a wrong position
image
AndroidStudio screenshot

**Comment by deniger** [comment]
the nova icon seems not to be aligned horizontally:

image

**Comment by teolemon** [comment]
No additives should be below NOVA. Nutri-Score is only about nutrition, not additives. NOVA is about additives.

**Comment by VaiTon** [comment]
> No additives should be below NOVA. Nutri-Score is only about nutrition, not additives. NOVA is about additives.

Ok

**Comment by VaiTon** [comment]
image
@teolemon @deniger comments?

**Comment by teolemon** [comment]
Can you center 3 additives under NOVA ? Otherwise, that's 👌

**Comment by VaiTon** [comment]
Actually the

> Can you center 3 additives under NOVA ? Otherwise, that's 👌

It would be like this
image

**Comment by teolemon** [comment]
perfect. @stephanegigandet what do you think ?

**Comment by stephanegigandet** [comment]
Perfect, thank you!

**Comment by VaiTon** [comment]
@deniger

**Comment by deniger** [comment]
@teolemon  we can merge this one I suppose

**Pull request merged**
