### PR TITLE
Fixed #1118: App crashes on translation fixed completely 

### LINKED ISSUE #1118: App crashes on selecting Preference after translating to new language
**Checklist**
- [x] Bug Report - The issue you are reporting might be there already. Please search on the [issues tracker](https://github.com/openfoodfacts/openfoodfacts-androidapp/issues) before creating or reporting an issue.
- [x] Before reporting, please ensure (if you can) that you have tested it with the latest (dev) version of the software.
- [x] Don't forget to tag your issue, it makes it easier to discover.
**Summary:** 

When we select new language and again try open Preference then it crashes .

**Steps to reproduce:** 

1. select Hindi language from Select language 
2. Now again Select Preference  from drawer 

**Add system logs:**

Add log files here (if you are able to add).

**Expected behavior:** 

It should open Prefrence fragmenst 

**Observed behavior:** 

App crashes 

**Device and Android version:** 

Android 7.0 API 24

**Screenshots:** 

video2gif_20180305_035705 1

I am working on this .

### PR DESCRIPTION
**Pull request by iml-v**
## Description

#1118  App crashes on translation fixed completely 

## Related issues and discussion
#1118 
 
 ## Screen-shots, if any
 
 ## Checklist
 
Make sure you've done all the following (You can delete the checklist before submitting)
 
 - [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.
 - [x] Code is well documented
 - [x] Include unit tests for new functionality
 - [x] All user-visible strings are made translatable
 - [x] Code passes Travis builds in your branch
 - [x] If you have multiple commits please combine them into one commit by squashing them.
 - [x] Read and understood the contribution guidelines .

### CODE REVIEW

**Comment by iml-v** [comment]
@Karljoones  Please review this PR #1126  i have done changes for all cases

**Comment by teolemon** [comment]
@Karljoones this one looks simple enough

**Comment by teolemon** [comment]
Poke @iml-v

**Comment by iml-v** [comment]
@teolemon i am not able to reproduce this error again ,it seems this error was because of  those Preferences for which we were using "R.string.id" instead of their "key" & "value " so i think it can be closed

**Comment by iml-v** [comment]
@teolemon i am not able to reproduce this error again ,it seems this error was because of those Preferences for which we were using "R.string.id" instead of their "key" & "value "

**Comment by Karljoones** [comment]
@iml-v am I right in saying that this issue is now resolved and that we can close this PR and the associated issue?

**Comment by iml-v** [comment]
@Karljoones  yes we can close ,it is resolved , I was busy since last two days in Proposal writing  from now i am continuing to contribute 😄

**Comment by Karljoones** [comment]
Thanks @iml-v!

**Pull request closed without merging**
