### PR TITLE
Crash at Advanced Search Resolved

### LINKED ISSUE #3610: Trying to open advanced search crashes the app
**Describe the bug**
Trying to open advanced search crashes the app

**To Reproduce**
1. Go to the sidemenu
2. Click on 'Advanced Search'
3. Click on 'Open with Open Food Facts'

### PR DESCRIPTION
**Pull request by mrudultora**
####  Description
Fixed the issue of app crashing on trying to open Advanced Search from sidebar (then open with  OpenFoodFacts). There was a NullPointerException causing the crash. I fixed that by moving a line to else block.

#### Related issues
Fixes the issue #3610 

#### Related PRs
None of the PR are related to this one.

#### Screenshots
After Resolving

Resolved

### CODE REVIEW

**Comment by mrudultora** [comment]
@teolemon  Will you please tell me why the Screenshot android test failed.

**Comment by teolemon** [comment]
@mrudultora probably related to the Kotlin refactoring, not your fault ;-)

**Review by VaiTon — APPROVED** [review]

**Comment by VaiTon** [comment]
@mrudultora could you rebase please?

**Comment by mrudultora** [comment]
@VaiTon  Its stating that the branch is up to date.  Unable to rebase. I tried rebasing this branch on  #3615

**Comment by VaiTon** [comment]
Closing in favor of #3615. Thank you!

**Pull request closed without merging**
