### PR TITLE
chore: GSOC'18 folder delete

### PR DESCRIPTION
**Pull request by utkarsh006**
####  Description
- Deleted GSOC'18 folder which contained docs in it.
- It's already been there in the app.

### CODE REVIEW

**Comment by utkarsh006** [comment]
@VaiTon Kindly Review

**Comment by utkarsh006** [comment]
@VaiTon Any Updates?

**Comment by utkarsh006** [comment]
@teolemon Kindly Review

**Comment by VaiTon** [comment]
I don't really understand why should we remove the files. Any reasoning?

**Comment by utkarsh006** [comment]
@VaiTon Deletion of files, would make the repo look cleaner. I think there's no use of collecting unnecessary data which can come along with the fork.

**Comment by VaiTon** [comment]
Sorry, but I don't think we really want to delete those files. Thanks for the contribution though!

**Pull request closed without merging**
