### PR TITLE
Fix pixelated red cross for missing image in history

### LINKED ISSUE #802: The red cross for missing image is pixelated in History
**Summary:** 

The red cross for missing image is blurry and pixelated in History. We should have something crisper.

**Device and Android version:** 

Android Oreo on a Google Pixel

**Screen-shots:** 

image

### PR DESCRIPTION
**Pull request by huzaifaiftikhar**
## Description

Fix pixelated red cross by using vector drawable. Also converted an image used in OfflineEditFragment to vector drawable.

## Related issues and discussion
Fixes #802 
 
 ## Checklist
 
 Please make sure these boxes are checked before submitting your pull request - thanks!
 
 
 
 - [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.
 
 - [x] If you have multiple commits please combine them into one commit by squashing them.
 
 - [x] Read and understood the contribution guidelines .

### CODE REVIEW

**Comment by huzaifaiftikhar** [comment]
@teolemon Please review the PR.

**Comment by policorn** [comment]
Hi @teolemon, this one can be merged. Thanks @huzaifaiftikhar!

**Comment by teolemon** [comment]
Before merging, do we have a PNG fallback for older versions of Android ? 
@policorn @huzaifaiftikhar

**Comment by huzaifaiftikhar** [comment]
@teolemon vector drawables do have a backward compatibility solution and we have already implemented that in our application's *build.gradle* (`vectorDrawables.useSupportLibrary = true`)
https://developer.android.com/guide/topics/graphics/vector-drawable-resources.html#vector-drawables-backward-solution
You can merge this without any worries xD

**Comment by teolemon** [comment]
@policorn @huzaifaiftikhar merging

**Comment by policorn** [comment]
Hi @huzaifaiftikhar; Would this work in onder devices?

**Comment by huzaifaiftikhar** [comment]
Yes @policorn this would work on APIs greater than 7. Ours minimum is set to 16 and I have tested it on API 17 today and it worked perfectly.

**Pull request merged**
