### PR TITLE
imageurl made nullable (NPE fixed)

### LINKED ISSUE #3843: NPE (onBookmarkProductButtonClick(SummaryProductFragment.kt:754)
Sentry Issue: [OPENFOODFACTS-ANDROID-1SP](https://sentry.io/organizations/openfoodfacts/issues/2140969955/?referrer=github_integration)

```
NullPointerException: None
    at openfoodfacts.github.scrachx.openfood.features.product.view.summary.SummaryProductFragment.onBookmarkProductButtonClick(SummaryProductFragment.kt:754)
    at openfoodfacts.github.scrachx.openfood.features.product.view.summary.SummaryProductFragment.access$processInsight(SummaryProductFragment.kt:78)
    at openfoodfacts.github.scrachx.openfood.features.product.view.summary.SummaryProductFragment.access$onBookmarkProductButtonClick(SummaryProductFragment.kt:78)
    at openfoodfacts.github.scrachx.openfood.features.product.view.summary.SummaryProductFragment$onViewCreated$4.onClick(SummaryProductFragment.kt:147)
    at android.view.View.performClick(View.java:7862)
...
(10 additional frame(s) were not displayed)
```

### LINKED ISSUE #3852: NPE SummaryProductFragment.onBookmarkProductButtonClick( line 754)
Sentry Issue: [OPENFOODFACTS-ANDROID-1XS](https://sentry.io/organizations/openfoodfacts/issues/2149458804/?referrer=github_integration)

```
NullPointerException: None
    at openfoodfacts.github.scrachx.openfood.features.product.view.summary.SummaryProductFragment.onBookmarkProductButtonClick(SummaryProductFragment.kt:754)
    at openfoodfacts.github.scrachx.openfood.features.product.view.summary.SummaryProductFragment.access$processInsight(SummaryProductFragment.kt:78)
    at openfoodfacts.github.scrachx.openfood.features.product.view.summary.SummaryProductFragment.access$onBookmarkProductButtonClick(SummaryProductFragment.kt:78)
    at openfoodfacts.github.scrachx.openfood.features.product.view.summary.SummaryProductFragment$onViewCreated$4.onClick(SummaryProductFragment.kt:147)
    at android.view.View.performClick(View.java:6897)
...
(8 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by kartikaysharma01**
####  Description
imageurl made nullable

#### Related issues

Fixes #3852 
Fixes #3843

### CODE REVIEW

**Comment by VaiTon** [comment]
I don't like how we're fixing this. I'd like to keep nullable values out of the DB so let's so as on line
https://github.com/openfoodfacts/openfoodfacts-androidapp/blob/17a4c4679109f0c9f1e36e603defe7d3729a31b3/app/src/main/java/openfoodfacts/github/scrachx/openfood/features/product/view/summary/SummaryProductFragment.kt#L812
and just pass an empty value there.

**Comment by kartikaysharma01** [comment]
> I don't like how we're fixing this. I'd like to keep nullable values out of the DB so let's so as on line
> and just pass an empty value there.

@VaiTon That was my first instinct too. But the Picasso library we are using does not allow empty or blank strings while loading image url.

**Comment by VaiTon** [comment]
> 
> 
> > I don't like how we're fixing this. I'd like to keep nullable values out of the DB so let's so as on line
> > and just pass an empty value there.
> 
> @VaiTon That was my first instinct too. But the Picasso library we are using does not allow empty or blank strings while loading image url.

And does it allow null values? We could check if the string is empty where we need to use it.

**Comment by kartikaysharma01** [comment]
> And does it allow null values? 

@VaiTon  Yes, it handles null values gracefully ( skips loading and sets image as placeholder )

> We could check if the string is empty where we need to use it.

Yes that can be done

**Comment by kartikaysharma01** [comment]
@VaiTon comments resolved

**Review by VaiTon — APPROVED** [review]

**Comment by VaiTon** [comment]
Thanks a lot! 🎉

**Pull request merged**
