### PR TITLE
Fix editing in allergens alert screen (closes #4133)

### LINKED ISSUE #4133: I shouldn't be able to select none as an allergen (Regression)
I shouldn't be able to select none as an allergen (This is a Regression of an issue that was fixed by @VaiTon )
https://github.com/openfoodfacts/openfoodfacts-androidapp/issues/3672

image
image

### PR DESCRIPTION
**Pull request by naivekook**
Fix editing in allergens alert screen

#### Related issues
- #4133 

#### Screenshots
https://drive.google.com/file/d/1lw_1sepfjiuCkEbCzXrZ8ewablqjOZCS/view?usp=sharing

### CODE REVIEW

**Comment by teolemon** [comment]
- @naivekook any chance it might solve #4120 ?

**Comment by naivekook** [comment]
@teolemon don't think so, looks like 4120 is about database migration

**Comment by VaiTon** [comment]
@naivekook what do you think about moving data to a new ViewModel?

**Comment by naivekook** [comment]
@VaiTon my intention was just to fix the issue in this PR
But I'm all for moving the logic to viewmodel

**Comment by VaiTon** [comment]
@naivekook would you prefer that we first merge this or that we merge the viewmodel version?

**Comment by naivekook** [comment]
@VaiTon sounds good, let's merge this one and next PR will be with refactoring

**Review by VaiTon — APPROVED** [review]

**Pull request merged**
