### PR TITLE
Change image in Barcode search for Open Beauty Facts

### PR DESCRIPTION
**Pull request by teolemon**

### CODE REVIEW

**Comment by VaiTon** [comment]
What is this for?

**Comment by teolemon** [comment]
This is the image for search by barcode for open beauty facts

**Comment by VaiTon** [comment]
Was it intended to put it in `off` res folder?

**Comment by teolemon** [comment]
nope, obf as she is holding a shampoo bottle

**Comment by VaiTon** [comment]
immagine

**Pull request merged**
