### PR TITLE
Fixes #2309: Add Error Message for empty Password in Sign-in Screen

### LINKED ISSUE #2309: Add Error message for empty Password in Sign-in Screen
**Summary:** 

With empty credentials, on clicking Sign in button, error message pops up only for Username and not for password.

**Steps to reproduce:** 

Step 1. Navigate to Login Screen.
Step 2. Leave the credentials empty.
Step 3. Click the Sign In button.
Step 4. Observer the error

**Expected behavior:** 

An error message should have popped up for password as well.

**Observed behavior:** 

Error message popped up only for username field.

**Device and Android version:** 

Device: Lenovo Vibe K5 Note
Android version: Android 6.0 Marshmallow

**Screenshots:** 

screenshot_2019-02-26-01-25-44-144

### PR DESCRIPTION
**Pull request by rohap97**
## Description

Changes made to LoginScreen.java so that error message pops up for empty password

## Related issues and discussion
#fixes 2309

### CODE REVIEW

**Comment by teolemon** [comment]
@rohap97 Can you rebase your branch ? There are 4171 changed files 😱

**Comment by mustaqmustu** [comment]
@teolemon can I make a new PR on this as this issue is inactive far a long time

**Comment by teolemon** [comment]
Yes, you may @mustaqmustu

**Comment by deniger** [comment]
@teolemon this PR could be closed as it has been fixed by #2379. Correct ?

**Comment by teolemon** [comment]
@deniger @rohap97 closing then

**Pull request closed without merging**
