### PR TITLE
Fixes #735: Showing toast warning on pressing back in home activity.

### LINKED ISSUE #735: No warning on pressing back in home activity and app closes
**Summary:** 

when user press back button in app it takes out from app but there is no warning message "Please press back again to exit" .

**Steps to reproduce:** 

Start the app ---> press back button on home screen .

**Add System logs:**

**Expected behavior:** 

It should show warn message to user like "Please press back again to exit " to come out from app.

**Observed behavior:** 

on pressing back it takes out from app .

**Device and Android version:** 

Android 7.0 ,API 24

**Screen-shots:** 

video2gif_20180214_031555 1

### PR DESCRIPTION
**Pull request by AbsolutelySaurabh**
## Description
Now showing warning as on pressing back in home activity. Double tap will exit the app.

## Related issues and discussion
#735 
 
 ## Screen-shots, if any
screenshot_20180216-014621

### CODE REVIEW

**Comment by ross-holloway94** [comment]
Personally against this as a feature, but I understand it wouldn't have been easy to do. So thank you, I'll let others decide if they want to merge this.

**Comment by PrajwalM2212** [comment]
It can be irritating to a lot of users . Our utmost priority must be user satisfaction .

**Comment by policorn** [comment]
Hi @teolemon, we need your feedback here

**Comment by iml-v** [comment]
@AbsolutelySaurabh This issue is duplicate of #735 .Before opening new issues check if there is have any issue already . Don't be that negligent

**Comment by Karljoones** [comment]
@iml-v this is not an issue report, this is a pull request to **fix** the issue reported

**Comment by Karljoones** [comment]
Hey guys, I think that the majority of people are against this feature so I am going to close off this pull request and close the issue without the feature being implemented. Thank you for your work @AbsolutelySaurabh, looking forward to seeing more pull requests from you :)

**Pull request closed without merging**
