### PR TITLE
Revert "gitflow: merge release/3.4.2 into master (#3534)"

### PR DESCRIPTION
**Pull request by VaiTon**
This reverts commit 2f5dffe9c3ccb38699d283df78e99f73fc3f953f.

### CODE REVIEW

**Comment by VaiTon** [comment]
@teolemon we need to merge not squash

**Comment by teolemon** [comment]
Really sorry about this. I took the plunge without waiting

**Comment by VaiTon** [comment]
@teolemon no problem! could you approve?

**Review by teolemon — APPROVED** [review]

**Comment by teolemon** [comment]
done

**Pull request merged**
