### PR TITLE
Updated History and Product search UI

### PR DESCRIPTION
**Pull request by l-o-b-s-t-e-r**
- created small icons for nutri score
 - changed UI of History Product
 - changed Entity of History Product
 - implemented Database migration
 - REMOVED loading of FULL size images, instead of this I added loading via Picasso (this small fix 
speeded up displaying of products several times)

### CODE REVIEW

**Comment by l-o-b-s-t-e-r** [comment]
#925

**Comment by l-o-b-s-t-e-r** [comment]
I've spent like an hour to understand why history screen is loading so looong. It was really strange, because we just get data from the local DB. Finally, I've found that we were loading the full-size image of the each product...only after loading, history products were shown.
I even cannot imagine how long users are waiting if they have more than 100 products...

**Comment by l-o-b-s-t-e-r** [comment]
@teolemon 
@Karljoones 
@policorn

**Comment by l-o-b-s-t-e-r** [comment]
alt text

**Comment by PrajwalM2212** [comment]
Looks Awesome !
And great work identifying the cause of delayed load .

**Comment by itchix** [comment]
You can put the nutriscore grade on search view too, like this PR : https://github.com/openfoodfacts/openfoodfacts-androidapp/pull/979

I'll will close mine if you do it :smiley:

**Comment by l-o-b-s-t-e-r** [comment]
@itchix no problem :)

**Comment by itchix** [comment]
Please fix travis issue : 
```
Caused by: java.lang.RuntimeException: Constructor (see HistoryProduct:35) has been changed after generation.
Please either mark it with @Keep annotation instead of @Generated to keep it untouched,
or use @Generated (without hash) to allow to replace it.
```

**Comment by l-o-b-s-t-e-r** [comment]
@itchix 
Fixed)

**Comment by policorn** [comment]
Let's wait for quorum and merge : )

**Comment by l-o-b-s-t-e-r** [comment]
@Karljoones I hope no, but I'm ready to protect my code 😎🔫😂

**Comment by itchix** [comment]
Ahaha it's OK for me!
I'll close my PR

**Comment by jaztriumph** [comment]
@l-o-b-s-t-e-r I think putting a progress bar on the history image holder so that user knows when image is loading will be nice. It will be just 2 lines of code to do with picasso callback function.
progress

**Comment by teolemon** [comment]
Ok, merging .Thanks  @l-o-b-s-t-e-r 
The loader thing would indeed be nice to have @jaztriumph

**Comment by jaztriumph** [comment]
@teolemon then I will make a issue and implement it.

**Pull request merged**
