### PR TITLE
Added icons to fragment summary product.

### LINKED ISSUE #2970: Add icons to summary fields and reduce their length
image

### PR DESCRIPTION
**Pull request by VaiTon**
Fixes #2970.
image

### CODE REVIEW

**Comment by teolemon** [comment]
https://github.com/openfoodfacts/openfoodfacts-androidapp/issues/1464 
label icon by Seanau under CC-BY
Award icon by samuel nudds under CC-BY
Map is standard material, right @VaiTon ?

**Comment by stephanegigandet** [comment]
Just curious: where do we list the CC-BY authors of the icons?

**Comment by teolemon** [comment]
in #1464

**Comment by stephanegigandet** [comment]
It looks weird to have icons for some tags but not others, like in the screen capture above where additives are more to the left because they don't have icons. Which fields can be displayed here, besides additives, categories, labels and packaging codes?

**Comment by stephanegigandet** [comment]
I think there's a choice to be made: either display the field name, or display icons, but not both, as it makes things very crowded.

If we do display icons only, then we need to make sure the icons can be easily understood. The "tag" icon does not really work well for categories of products, as "tags" are used on actual products. But I can't think of any icon that really works for categories. Maybe the "list" icon.

**Comment by teolemon** [comment]
Usability surveys in general (remember seeing that for LibreOffice) show that text+icon provide the maximum ease of use for users.

**Comment by stephanegigandet** [comment]
Agreed, icons + text is better  than icons only. The issue I have is that here the text is not "part" of the icon (it's not centered below it, it's not the only text next to it), and it feels weird to have both like that.

**Comment by stephanegigandet** [comment]
I guess a better question might be: why do we need icons here? Many people will understand icons as being buttons that they can click and do an action. Here the icons are used as labels for the clicable links that are next to them. That could be very confusing.

**Comment by teolemon** [comment]
To give a soul to the app. Those are illustrations

**Comment by VaiTon** [comment]
We need to create an issue for the attribution.
cc @teolemon

**Comment by teolemon** [comment]
It already exists (#1464 ) @VaiTon

**Pull request merged**
