### PR TITLE
Clean up and simplify files + gradles

### PR DESCRIPTION
**Pull request by TacoTheDank**
- Deleted generated files
- Compile, build, and target Android Pie
- Update Android Studio 3.1.3 -> 3.2.1
- Update Gradle 4.4 -> 4.10.3
- Reorganize the build.gradles to be less cluttered (there's no point in using ext to define things that are only used once)
- Replace ```'javax.annotation:jsr250-api:1.0'``` with ```'javax.annotation:javax.annotation-api:1.3.2'``` (the library had moved)
- Update RxJava 2.1.7 -> 2.2.5
- Update RxAndroid 2.0.1 -> 2.1.0
- Update OkHttp3 3.9.0 -> 3.9.1
- Update Jackson 2.8.9 -> 2.8.11
- Update Espresso 3.0.1 -> 3.0.2
- Update Opencsv 4.1 -> 4.4
- Update GreenDao 3.2.0 -> 3.2.2
- Update Jsoup 1.11.2 -> 1.11.3
- Update commons-collections4 4.1 -> 4.2
- Update PhotoView 2.1.3 -> 2.1.4
- Update iconics-core 3.0.0 -> 3.0.4
- Update google-material-typeface 3.0.1.2.original -> 3.0.1.3.original
- Update material-design-iconic-typeface 2.2.0.4 -> 2.2.0.5
- Update android-image-cropper 2.6.0 -> 2.7.0
- Update Nachos 1.1.1 -> 1.2.0
- Update Junit 4.12 -> 4.13-beta-1 because why not
- Update Mockito 2.13.0 -> 2.23.4
- Update json-unit-fluent 1.27.0 -> 1.31.1

### CODE REVIEW

**Comment by teolemon** [comment]
@jinqian does that have some impact in terms of supported versions ?

**Comment by TacoTheDank** [comment]
@jinqian Not that I'm aware of. It just increases support to Pie. I tried to update to update any libraries that had newer versions that I was sure didn't have breaking changes.

**Comment by TacoTheDank** [comment]
merged upstream

**Comment by teolemon** [comment]
``` 
2019-02-15 01:08:49.504 1754-1754/openfoodfacts.github.scrachx.openfood E/AndroidRuntime: FATAL EXCEPTION: main
    Process: openfoodfacts.github.scrachx.openfood, PID: 1754
    java.lang.IllegalArgumentException: Invalid Layer Save Flag - only ALL_SAVE_FLAGS is allowed
        at android.graphics.Canvas.checkValidSaveFlags(Canvas.java:378)
        at android.graphics.Canvas.saveLayer(Canvas.java:455)
        at com.mikepenz.materialdrawer.view.BezelImageView.onDraw(BezelImageView.java:213)
        at android.view.View.draw(View.java:20207)
        at android.view.View.updateDisplayListIfDirty(View.java:19082)
        at android.view.View.draw(View.java:19935)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4333)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4112)
        at android.view.View.updateDisplayListIfDirty(View.java:19073)
        at android.view.View.draw(View.java:19935)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4333)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4112)
        at android.view.View.draw(View.java:20210)
        at android.view.View.updateDisplayListIfDirty(View.java:19082)
        at android.view.View.draw(View.java:19935)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4333)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4112)
        at android.view.View.updateDisplayListIfDirty(View.java:19073)
        at android.view.View.draw(View.java:19935)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4333)
        at android.support.v7.widget.RecyclerView.drawChild(RecyclerView.java:4820)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4112)
        at android.view.View.draw(View.java:20210)
        at android.support.v7.widget.RecyclerView.draw(RecyclerView.java:4219)
        at android.view.View.updateDisplayListIfDirty(View.java:19082)
        at android.view.View.draw(View.java:19935)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4333)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4112)
        at android.view.View.draw(View.java:20210)
        at com.mikepenz.materialize.view.ScrimInsetsRelativeLayout.draw(ScrimInsetsRelativeLayout.java:77)
        at android.view.View.updateDisplayListIfDirty(View.java:19082)
        at android.view.View.draw(View.java:19935)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4333)
        at android.support.v4.widget.DrawerLayout.drawChild(DrawerLayout.java:1426)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4112)
        at android.view.View.draw(View.java:20210)
        at android.view.View.updateDisplayListIfDirty(View.java:19082)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4317)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4290)
        at android.view.View.updateDisplayListIfDirty(View.java:19042)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4317)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4290)
        at android.view.View.updateDisplayListIfDirty(View.java:19042)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4317)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4290)
        at android.view.View.updateDisplayListIfDirty(View.java:19042)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4317)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4290)
        at android.view.View.updateDisplayListIfDirty(View.java:19042)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4317)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4290)
        at android.view.View.updateDisplayListIfDirty(View.java:19042)
        at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:686)
        at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:692)
        at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:801)
        at android.view.ViewRootImpl.draw(ViewRootImpl.java:3311)
        at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3115)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2484)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1460)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7183)
2019-02-15 01:08:49.505 1754-1754/openfoodfacts.github.scrachx.openfood E/AndroidRuntime:     at android.view.Choreographer$CallbackRecord.run(Choreographer.java:949)
        at android.view.Choreographer.doCallbacks(Choreographer.java:761)
        at android.view.Choreographer.doFrame(Choreographer.java:696)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6718)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

```

**Comment by teolemon** [comment]
Getting this when attempting to run the built version.

**Comment by brandenfung** [comment]
> ```
> 2019-02-15 01:08:49.504 1754-1754/openfoodfacts.github.scrachx.openfood E/AndroidRuntime: FATAL EXCEPTION: main
>     Process: openfoodfacts.github.scrachx.openfood, PID: 1754
>     java.lang.IllegalArgumentException: Invalid Layer Save Flag - only ALL_SAVE_FLAGS is allowed
>         at android.graphics.Canvas.checkValidSaveFlags(Canvas.java:378)
>         at android.graphics.Canvas.saveLayer(Canvas.java:455)
>         at com.mikepenz.materialdrawer.view.BezelImageView.onDraw(BezelImageView.java:213)
>         at android.view.View.draw(View.java:20207)
>         at android.view.View.updateDisplayListIfDirty(View.java:19082)
>         at android.view.View.draw(View.java:19935)
>         at android.view.ViewGroup.drawChild(ViewGroup.java:4333)
>         at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4112)
>         at android.view.View.updateDisplayListIfDirty(View.java:19073)
>         at android.view.View.draw(View.java:19935)
>         at android.view.ViewGroup.drawChild(ViewGroup.java:4333)
>         at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4112)
>         at android.view.View.draw(View.java:20210)
>         at android.view.View.updateDisplayListIfDirty(View.java:19082)
>         at android.view.View.draw(View.java:19935)
>         at android.view.ViewGroup.drawChild(ViewGroup.java:4333)
>         at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4112)
>         at android.view.View.updateDisplayListIfDirty(View.java:19073)
>         at android.view.View.draw(View.java:19935)
>         at android.view.ViewGroup.drawChild(ViewGroup.java:4333)
>         at android.support.v7.widget.RecyclerView.drawChild(RecyclerView.java:4820)
>         at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4112)
>         at android.view.View.draw(View.java:20210)
>         at android.support.v7.widget.RecyclerView.draw(RecyclerView.java:4219)
>         at android.view.View.updateDisplayListIfDirty(View.java:19082)
>         at android.view.View.draw(View.java:19935)
>         at android.view.ViewGroup.drawChild(ViewGroup.java:4333)
>         at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4112)
>         at android.view.View.draw(View.java:20210)
>         at com.mikepenz.materialize.view.ScrimInsetsRelativeLayout.draw(ScrimInsetsRelativeLayout.java:77)
>         at android.view.View.updateDisplayListIfDirty(View.java:19082)
>         at android.view.View.draw(View.java:19935)
>         at android.view.ViewGroup.drawChild(ViewGroup.java:4333)
>         at android.support.v4.widget.DrawerLayout.drawChild(DrawerLayout.java:1426)
>         at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4112)
>         at android.view.View.draw(View.java:20210)
>         at android.view.View.updateDisplayListIfDirty(View.java:19082)
>         at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4317)
>         at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4290)
>         at android.view.View.updateDisplayListIfDirty(View.java:19042)
>         at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4317)
>         at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4290)
>         at android.view.View.updateDisplayListIfDirty(View.java:19042)
>         at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4317)
>         at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4290)
>         at android.view.View.updateDisplayListIfDirty(View.java:19042)
>         at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4317)
>         at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4290)
>         at android.view.View.updateDisplayListIfDirty(View.java:19042)
>         at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4317)
>         at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4290)
>         at android.view.View.updateDisplayListIfDirty(View.java:19042)
>         at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:686)
>         at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:692)
>         at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:801)
>         at android.view.ViewRootImpl.draw(ViewRootImpl.java:3311)
>         at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3115)
>         at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2484)
>         at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1460)
>         at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7183)
> 2019-02-15 01:08:49.505 1754-1754/openfoodfacts.github.scrachx.openfood E/AndroidRuntime:     at android.view.Choreographer$CallbackRecord.run(Choreographer.java:949)
>         at android.view.Choreographer.doCallbacks(Choreographer.java:761)
>         at android.view.Choreographer.doFrame(Choreographer.java:696)
>         at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935)
>         at android.os.Handler.handleCallback(Handler.java:873)
>         at android.os.Handler.dispatchMessage(Handler.java:99)
>         at android.os.Looper.loop(Looper.java:193)
>         at android.app.ActivityThread.main(ActivityThread.java:6718)
>         at java.lang.reflect.Method.invoke(Native Method)
>         at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
>         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
> ```

This issue occurs when pressing the drawer button and is referenced here: https://github.com/mikepenz/MaterialDrawer/issues/2307

You will need to update MaterialDrawer to a newer version to fix this crash.

**Comment by Karljoones** [comment]
@TacoTheDank can you take another look at this?

**Comment by TacoTheDank** [comment]
Yeah, I'll clean up the fork and origin differences

**Comment by teolemon** [comment]
@TacoTheDank tiny merge conflicts to fix

**Comment by VaiTon** [comment]
@TacoTheDank can you merge so that the PR can be reviewed?

**Pull request closed without merging**
