### PR TITLE
Closes #1040: Multi supports barcode enabled

### LINKED ISSUE #1040: Multi-format barcode does not supports
**Summary:** 

App does not supports multi-barcode formats like UPC_EAN_EXTENSION ,MAXICODE ,DATA_MATRIX, RSS_EXPANDED ,CODABAR etc.

**Expected behavior:** 

App should be multi-formats barcode supported 

**Observed behavior:** 

It does not supports above mentioned formtats

**Screenshots:** 

Can be created by pressing the Volume Down and Power Button at the same time on Android 4.0 and higher.

I am working on this .

### PR DESCRIPTION
**Pull request by iml-v**
## Description

#1040 Multi format bar code supported enabled 
## Related issues and discussion
#1040
 
 ## Screen-shots, if any
 
 ## Checklist
 
Make sure you've done all the following (You can delete the checklist before submitting)
 
 - [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.
 - [x] Code is well documented
 - [x] Include unit tests for new functionality
 - [x] All user-visible strings are made translatable
 - [x] Code passes Travis builds in your branch
 - [x] If you have multiple commits please combine them into one commit by squashing them.
 - [] Read and understood the contribution guidelines .

### CODE REVIEW

**Comment by iml-v** [comment]
@teolemon Please review this PR.

**Comment by teolemon** [comment]
Do you have real life examples we can test on ?

**Comment by iml-v** [comment]
You mean products that are  existing in market and using these  barcode types  ,you can check this [here](https://www.scandit.com/types-barcodes-choosing-right-barcode/)

**Comment by iml-v** [comment]
Also check  [here 1](https://www.cils-international.com/us/information-centre/blog/articles/barcode-labelling-the-basics/) , [here 2 ](https://www.idautomation.com/barcode-faq/gs1-databar/) ,[here for RSS_EXPANDED](http://www.foodconnex.com/news-archive/232-issue-131-control-mistakes-in-order-entry)

**Comment by iml-v** [comment]
@Karljoones @policorn take a look at this PR.

**Comment by policorn** [comment]
Hi @teolemon, do you know if all these are server-side supported? Could we implement some test/API call to verify it?

**Comment by teolemon** [comment]
If we're sure if will yield a number, that should be ok.
@stephanegigandet

**Comment by policorn** [comment]
Hi @iml-v, could you add some tests on the new barcodes to check they indeed only return a number?

**Comment by iml-v** [comment]
@policorn Sure I will add test for it

**Comment by Karljoones** [comment]
@iml-v @policorn how is this PR coming along?

**Comment by iml-v** [comment]
@Karljoones  i am working on this and will update PR along with  test till next morning.

**Comment by Karljoones** [comment]
@iml-v any update on this?

**Comment by iml-v** [comment]
@Karljoones i will do it very soon , going through semester exams so i am busy there

**Comment by Karljoones** [comment]
@iml-v hope your exams went well, is there any update on this?

**Comment by iml-v** [comment]
@Karljoones sorry for not making changes , i am going to make update now on this

**Pull request closed without merging**
