### PR TITLE
Major code cleanup.

### PR DESCRIPTION
**Pull request by VaiTon**

### CODE REVIEW

**Comment by teolemon** [comment]
@VaiTon conflicts to solve. Also, can you provide a summary of the refactoring to the reviewer ?

**Comment by VaiTon** [comment]
Major changes:
 * Renamed layout ids so that they follow the snake_case convention;
 * Renamed some method to follow the camelCase convention;
 * Removed method `isUserNotLoggedIn()`;
 * Created private method `showCameraPermissionDialog()` in BaseFragment;
 * `canTakePhotos` -> `checkCameraPermissions()` in BaseFragment;
 * `requestPermissionTakePhotos()` -> `requestCameraPermissions()` in BaseFragment;
 * Inlined method `updateProductCount()` in HomeFragment;
 * Formatting issues;
 * Formatted JavaDoc;
 * Created private void `setupImagesFromAPI()` in ProductPhotosFragment;
 * Added try-with-resources statements (FileDownloader);
 * Moved methods from Utils to ProductUtils;
 * Moved methods to Utils.

Don't know if I'm missing something, i'll review it again.

**Comment by teolemon** [comment]
tiny conflict to solve @VaiTon

**Comment by teolemon** [comment]
Conflicts @VaiTon

**Pull request closed without merging**
