### PR TITLE
Remove unused resources

### LINKED ISSUE #836: Remove unused resources
**Summary:** 
We can remove the unused resources. This would help in reduction of overall apk size. 
Following is the list of unused resources : 

**Drawables**
barcode_black_24dp.xml
circle_view.xml
edittext_bottom.xml
edittext_middle.xml
edittext_top.xml
ic_add_black_24dp.xml
ic_camera_black.xml
ic_crowdsourcing_icon.xml
ic_decode_labels_icon.xml
ic_food_database_icon.xml
ic_home_black_24dp.xml
ic_keyboard_arrow_down_black_24dp.xml
ic_nutriscore_a.xml
ic_nutriscore_b.xml
ic_nutriscore_c.xml
ic_nutriscore_d.xml
ic_nutriscore_e.xml
ic_opendata_crowd_icon.xml
rounded_rectangle.xml
selector.xml
ic_openfacts_logo_no_tagline_vector.xml

**PNGs**
ic_error_outline_black.png
ic_palm.png
ic_plus_white_18dp.png
ic_plus_white_24dp.png
ic_plus_white_36dp.png
ic_plus_white_48dp.png
ic_user.png
img_default_product.png
img_nutrition.png
ic_action.png
ic_barcode_black_18dp.png
ic_barcode_black_24dp.png
ic_barcode_black_36dp.png
ic_barcode_black_48dp.png
ic_barcode_grey600_18dp.png
ic_barcode_grey600_24dp.png
ic_barcode_grey600_36dp.png
ic_barcode_grey600_48dp.png
ic_barcode_white_18dp.png
ic_barcode_white_24dp.png
ic_barcode_white_36dp.png
ic_barcode_white_48dp.png
ic_error_outline_black.png
ic_palm.png
ic_plus_black_18dp.png
ic_plus_black_24dp.png
ic_plus_black_36dp.png
ic_plus_black_48dp.png
ic_plus_grey600_18dp.png
ic_plus_grey600_24dp.png
ic_plus_grey600_36dp.png
ic_plus_grey600_48dp.png
ic_plus_white_18dp.png
ic_plus_white_24dp.png
ic_plus_white_36dp.png
ic_plus_white_48dp.png
ic_user.png
ic_action.png
ic_barcode_black_18dp.png
ic_barcode_black_24dp.png
ic_barcode_black_36dp.png
ic_barcode_black_48dp.png
ic_barcode_grey600_18dp.png
ic_barcode_grey600_24dp.png
ic_barcode_grey600_36dp.png
ic_barcode_grey600_48dp.png
ic_barcode_white_18dp.png
ic_barcode_white_24dp.png
ic_barcode_white_36dp.png
ic_barcode_white_48dp.png
ic_error_outline_black.png
ic_palm.png
ic_plus_black_18dp.png
ic_plus_black_24dp.png
ic_plus_black_36dp.png
ic_plus_black_48dp.png
ic_plus_grey600_18dp.png
ic_plus_grey600_24dp.png
ic_plus_grey600_36dp.png
ic_plus_grey600_48dp.png
ic_plus_white_18dp.png
ic_plus_white_24dp.png
ic_plus_white_36dp.png
ic_plus_white_48dp.png
ic_user.png
ic_action.png
ic_barcode_black_18dp.png
ic_barcode_black_24dp.png
ic_barcode_black_36dp.png
ic_barcode_black_48dp.png
ic_barcode_grey600_18dp.png
ic_barcode_grey600_24dp.png
ic_barcode_grey600_36dp.png
ic_barcode_grey600_48dp.png
ic_barcode_white_18dp.png
ic_barcode_white_24dp.png
ic_barcode_white_36dp.png
ic_barcode_white_48dp.png
ic_palm.png
ic_plus_black_18dp.png
ic_plus_black_24dp.png
ic_plus_black_36dp.png
ic_plus_black_48dp.png
ic_plus_grey600_18dp.png
ic_plus_grey600_24dp.png
ic_plus_grey600_36dp.png
ic_plus_grey600_48dp.png
ic_plus_white_18dp.png
ic_plus_white_24dp.png
ic_plus_white_36dp.png
ic_plus_white_48dp.png
ic_user.png
ic_barcode_black_18dp.png
ic_barcode_black_24dp.png
ic_barcode_black_36dp.png
ic_barcode_black_48dp.png
ic_barcode_grey600_18dp.png
ic_barcode_grey600_24dp.png
ic_barcode_grey600_36dp.png
ic_barcode_grey600_48dp.png
ic_barcode_white_18dp.png
ic_barcode_white_24dp.png
ic_barcode_white_36dp.png
ic_barcode_white_48dp.png
ic_plus_black_18dp.png
ic_plus_black_24dp.png
ic_plus_black_36dp.png
ic_plus_black_48dp.png
ic_plus_grey600_18dp.png
ic_plus_grey600_24dp.png
ic_plus_grey600_36dp.png
ic_plus_grey600_48dp.png
ic_plus_white_18dp.png
ic_plus_white_24dp.png
ic_plus_white_36dp.png
ic_plus_white_48dp.png
ic_error_outline_black.png

**Layout**
gauge_nutrition_fact.xml

**All app flavors must build successfully after removal of these resources.**

### PR DESCRIPTION
**Pull request by huzaifaiftikhar**
## Description

Removed the unused resources. Helps in the reduction of apk size.
**I was able to build all the flavors successfully even after the removal of these resources.**

## Related issues and discussion
Fixes #836 
 
 ## Checklist
 
 Please make sure these boxes are checked before submitting your pull request - thanks!
 
 
 
 - [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.
 
 - [x] If you have multiple commits please combine them into one commit by squashing them.
 
 - [x] Read and understood the contribution guidelines .

### CODE REVIEW

**Comment by policorn** [comment]
It is ok with me. Thanks again @huzaifaiftikhar! AKA _Lord of Vector Drawables_ 😄

**Comment by teolemon** [comment]
@policorn I'm wondering many icons, including the Nutriscore and Contributing xml disappearing. That is kind of a scary change :)

**Comment by policorn** [comment]
Ok @teolemon; going to re-test it

**Comment by huzaifaiftikhar** [comment]
@policorn Thanks for that title :smile: 

@teolemon We are not using those Nutriscore in our code anywhere. We use the following drawables to show the nutriscore :
- nnc_a.png
- nnc_b.png
- nnc_c.png
- nnc_d.png
- nnc_e.png

These are bieng used in `Utils.java` *starting from line number 198*. I have not deleted any of these. 
@policorn I guess when you built this you were sucessfully able to view the nutriscores, weren't you ?

**Comment by policorn** [comment]
Hi @teolemon, @huzaifaiftikhar; I haven't perceived any issue nor missed any pic. Nutriscores are properly rendered. Can we ask someone to build+test it just in case?

**Comment by Karljoones** [comment]
This is a terriflying PR! I feel that every single aspect of the app would need to be tested with this, Android does not always throw errors with missing resources, it waits for it to try display the layout before crashing..

**Comment by policorn** [comment]
@Karljoones going to run a Lint/unused assets check in master

**Comment by policorn** [comment]
The gradle lint report shows some issues with resources (enclosed report: [lint.tar.gz](https://github.com/openfoodfacts/openfoodfacts-androidapp/files/1749823/lint.tar.gz)) but does not mark all the deleted assets I were expecting. Anyhow, in Android Studio, if I search usages of each resource (icons and such) the deleted ones are not in use. @huzaifaiftikhar Did you use some specific gradle plugin to automatically find/delete unused assets?

**Comment by huzaifaiftikhar** [comment]
@policorn Yes if you go to 'Refactor' menu there is an option 'Remove Unused Resources'. This option is inbuilt in Android Studio. It helps in removing unused resources such as these. I have personally never faced any issues after removing the unused resources by this method.

**Comment by policorn** [comment]
@teolemon @Karljoones; the decision is all yours : )

**Comment by huzaifaiftikhar** [comment]
> Android does not always throw errors with missing resources, it waits for it to try display the layout before crashing..

@Karljoones If a resource is not found, Android Studio throws a compile-time error. The crashing you are talking about happens only when we change PNGs to vectors, in this case, the Android waits for the layout to be displayed and then the crash takes place. 
But we have removed the unused resources, if any of the above resources were actually in use then a compile-time error would have been thrown.

**Comment by policorn** [comment]
Thanks @huzaifaiftikhar and @Karljoones! Merged

**Pull request merged**
