### PR TITLE
fix: set fragment from code in CategoryActivity

### PR DESCRIPTION
**Pull request by VaiTon**

### CODE REVIEW

**Comment by teolemon** [comment]
The things moved around (sensor) is the shake to scan feature. It has stopped to work a while ago, and can probably be removed.

**Comment by teolemon** [comment]
Just tested the branch, it works (Android 11)

**Comment by VaiTon** [comment]
> 
> 
> The things moved around (sensor) is the shake to scan feature. It has stopped to work a while ago, and can probably be removed.

Could you open an issue so we keep track? I'm merging.

**Comment by teolemon** [comment]
#1799

**Pull request merged**
