### PR TITLE
changed logo size #912

### PR DESCRIPTION
**Pull request by shivanshsoni**
fixed logo size #912

### CODE REVIEW

**Comment by shivanshsoni** [comment]
@policorn I have answered @Karljoones comment :-)

**Comment by Karljoones** [comment]
Hi @shivanshsoni, code looks good, but before merging, can we have a screenshot of the updated icon? :)

**Comment by policorn** [comment]
screenshot_1519604208

**Comment by Karljoones** [comment]
Merged, thanks @shivanshsoni !

**Pull request merged**
