### PR TITLE
Closes: #633: WIP Multi-user allergen experience

### LINKED ISSUE #633: Suggestion: Add allergens for specific individuals
I would like to know people's opinions on this.
I believe that adding allergens for individuals, and therefore showing who is safe to eat a product and who is not, would improve the user experience.

### PR DESCRIPTION
**Pull request by ross-holloway94**
## Description

Adds functionality for detecting allergens for multiple users.

## Related issues and discussion
Closes #633 
 
 ## Screen-shots, if any
TBD 

 ## Checklist
 
Make sure you've done all the following (You can delete the checklist before submitting)
 
 - [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.
 - [ ] Code is well documented
 - [x] Include unit tests for new functionality
 - [x] All user-visible strings are made translatable
 - [ ] Code passes Travis builds in your branch
 - [ ] If you have multiple commits please combine them into one commit by squashing them.
 - [x] Read and understood the contribution guidelines .

### CODE REVIEW

**Comment by ross-holloway94** [comment]
Class diagram as of 8 July 2018 
consumers0807

**Comment by teolemon** [comment]
@ross-holloway94 Please fix the conflicts before they become to resolve on the web :)

**Comment by ross-holloway94** [comment]
@teolemon I'll rebase when I get time to do so :)

**Comment by ross-holloway94** [comment]
Going to close this as I'm spending far less time on it than I was before. Sorry.

**Pull request closed without merging**
