### PR TITLE
Closes #270: Shake phone to go back to scan mode 

### LINKED ISSUE #270: Shake phone to go back to scan mode
Shaking the phone would bring back the app to scan mode. Perhaps make this optional

### PR DESCRIPTION
**Pull request by PrajwalM2212**
## Description

Just shake the phone and you are ready to scan the products

## Related issues and discussion
#270

### CODE REVIEW

**Comment by PrajwalM2212** [comment]
@teolemon  I will fix the conflicts once "opff" is completely fixed otherwise travis will not pass.

**Comment by Karljoones** [comment]
Does this work from anywhere within the app?

**Comment by PrajwalM2212** [comment]
@Karljoones Yes , it works in all activities .

**Comment by Karljoones** [comment]
Fantastic, can you have a quick look at the conflicts and then we can merge?

**Comment by PrajwalM2212** [comment]
@Karljoones Conflicts resolved .

**Comment by teolemon** [comment]
@Karljoones good to merge ?

**Comment by Karljoones** [comment]
Merged, thanks @PrajwalM2212

**Pull request merged**
