### PR TITLE
Fix keyboard issues (#314 #74 #78)

### PR DESCRIPTION
**Pull request by naofum**

### CODE REVIEW

**Comment by teolemon** [comment]
(This includes commits from #360 and #370)

**Comment by itchix** [comment]
Can I merge?

**Comment by herau** [comment]
@itchix i'm waiting code review from @naofum

**Comment by teolemon** [comment]
Just renamed the PR to give sense of the topic

**Comment by Karljoones** [comment]
Would it be best to close this issue at this stage?

**Pull request closed without merging**
