### PR TITLE
Disabled dragging up in offline mode

### LINKED ISSUE #2679: Disable dragging up in offline mode
image

### PR DESCRIPTION
**Pull request by vanshikaarora**
## Description
Fixes #2679 Disable dragging up in offline mode

### Changes made
- Disabled bottom sheet behavior on dragging in offline mode

### CODE REVIEW

**Comment by vanshikaarora** [comment]
> @vanshikaarora Please remove the conflicts and make commit message informative rather than "first commit"

@RajaVamsi11 I have made the changes. Kindly review:)

**Comment by RajaVamsi11** [comment]
@vanshikaarora LGTM. If possible, please squash your commits to make your commit history clean.

**Comment by RajaVamsi11** [comment]
@vanshikaarora would you please rebase on latest commits to see if it pass the checks?

**Comment by vanshikaarora** [comment]
> @vanshikaarora would you please rebase on latest commits to see if it pass the checks?

Ok I'll do that

**Pull request closed without merging**
