### PR TITLE
Upload toast is hiding the "Upload All" button #830

### PR DESCRIPTION
**Pull request by shivanshsoni**
Solved issue #830

### CODE REVIEW

**Comment by Karljoones** [comment]
Hi @shivanshsoni, this issue is already being looked at in #830. Can we close this off?

**Comment by shivanshsoni** [comment]
OK Sir, I thought he backed out as his last commit was 2 days ago... Anyways I am closing this PR.

**Comment by Karljoones** [comment]
@shivanshsoni before working on something, I would always recommend getting into contact with the original poster to ensure that they are still working on it or not, reach out to them in the PR itself, or slack if they are on it. Just to ensure that duplicate work is not done, sometimes people just get busy :)

**Comment by shivanshsoni** [comment]
Ok Sir, I will take care of it now onwards :-)

**Comment by Karljoones** [comment]
@shivanshsoni what is happening with this PR? There seems to be a lot of conflicts and it hasn't been worked on in a few days? :)

**Comment by shivanshsoni** [comment]
@Karljoones Resolved all the conflicts. Please review :)

**Comment by Karljoones** [comment]
Merged, thanks @shivanshsoni

**Pull request merged**
