### PR TITLE
Closes #194 : Create a list of products added by the user

### LINKED ISSUE #194: Create a list of products added by the user
This allows the user to find products he has contributed to, and finish completing them.

### PR DESCRIPTION
**Pull request by PrajwalM2212**
## Description

The search can be done by 
1.Products you added or edited
2.Products you added that need to be completed
3.Products you took pictures for
4.Products you took pictures for that need to be completed
5.Products you added information for
6.Products you added information for that need to be completed

## Related issues and discussion
#194

### CODE REVIEW

**Comment by Karljoones** [comment]
Can we have some screenshots for this?

**Comment by PrajwalM2212** [comment]
image
@Karljoones  It will display the contributions based on the choice

**Comment by teolemon** [comment]
perhaps rewording a little:
"Show" instead of "Contributions by"

**Comment by PrajwalM2212** [comment]
@Karljoones I will resolve the conflicts by today night.

**Comment by Karljoones** [comment]
@PrajwalM2212 can you look into the failing build?

**Comment by Karljoones** [comment]
Merged, thanks @PrajwalM2212

**Pull request merged**
