### PR TITLE
Closes #205: Added RateUs feature

### LINKED ISSUE #205: Add a "Show your support" link in settings
Add a "Show your support" link in settings to enable users to rate the app the Play Store (hide if Play Store not installed)

### PR DESCRIPTION
**Pull request by ManognaMutyala**
## Description

Added RateUs feature

## Related issues and discussion
#205
 
 ## Screen-shots, if any
screenshot_20180318-114253
screenshot_20180318-114257

 
 ## Checklist
 
Make sure you've done all the following (You can delete the checklist before submitting)
 
 - [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.
 - [x] Code is well documented
 - [x] Include unit tests for new functionality
 - [x] All user-visible strings are made translatable
 - [x] Code passes Travis builds in your branch
 - [x] If you have multiple commits please combine them into one commit by squashing them.
 - [x] Read and understood the contribution guidelines .

### CODE REVIEW

**Comment by Karljoones** [comment]
Please bear in mind that there are multiple sources that the app could be installed from. There would be no point in sending the user to Google Play if they installed from Amazon, or F-Droid

**Comment by Karljoones** [comment]
Hey @ManognaMutyala, I think we should close this for now as there is no easy way or sending the user to the right store since there are so many different sources that the app can be installed from :)

**Comment by ManognaMutyala** [comment]
Ok @Karljoones Give me one more day,I will figure it out if there is any possibility!!

**Comment by Karljoones** [comment]
@ManognaMutyala No problem :)

**Comment by Karljoones** [comment]
https://stackoverflow.com/questions/10809438/how-to-know-an-application-is-installed-from-google-play-or-side-load :)

**Comment by Karljoones** [comment]
@ManognaMutyala What is happening with this PR?

**Comment by ManognaMutyala** [comment]
I am sorry @Karljoones, I was busy with national level hackathon,I will submit PR on this by tomorrow!!

**Comment by teolemon** [comment]
Can you rebase on latest trunk ? It should fix the build.

**Comment by Karljoones** [comment]
Just restarted this build due to `The job exceeded the maximum time limit for jobs, and has been terminated`.

**Comment by Karljoones** [comment]
Merged, thanks @ManognaMutyala!

**Pull request merged**
