### PR TITLE
fix #2374, #2454 Nutrition units incorrectly managed

### LINKED ISSUE #2374: Nutrition units incorrectly managed
While entering nutrition info, it forces the input for 100g even if we indicate a portion. The conversion bet, even kilojoules and kilo calories are incorrect. Units in milligrammes for example vitamins are recorded but incorrectly displayed divided by 1000, as if they were in grams, but displayed still as milligrams...

The results is completely unreliable. Does not match the actual input. 

Notations are then incorrectly computed!!

Please fix the measurement units in the Android app!!!

### PR DESCRIPTION
**Pull request by deniger**
+ fix conversion issues

## Related issues and discussion
#fixes #2374, #2454

### CODE REVIEW

**Comment by deniger** [comment]
There is an issue with travis:
https://travis-ci.org/openfoodfacts/openfoodfacts-androidapp/jobs/509975888
it seems that oracle jdk can't be installed...

**Comment by teolemon** [comment]
```Caused by: com.android.builder.errors.EvalIssueException: Failed to install the following Android SDK packages as some licences have not been accepted.
   build-tools;28.0.3 Android SDK Build-Tools 28.0.3
To build this project, accept the SDK license agreements and install the missing components using the Android Studio SDK Manager.
Alternatively, to transfer the license agreements from one workstation to another, see http://d.android.com/r/studio-ui/export-licenses.html```

**Comment by teolemon** [comment]
mmmh…
https://github.com/openfoodfacts/openfoodfacts-androidapp/blob/master/.travis.yml

**Comment by deniger** [comment]
A problem occurred configuring project ':app'.
> Failed to install the following Android SDK packages as some licences have not been accepted.
     build-tools;28.0.3 Android SDK

**Comment by deniger** [comment]
In Travis I suppose we should change 28.0.2 to 28.0.3 or maybe there is a way to not specify this version

**Comment by teolemon** [comment]
yes indeed

**Comment by teolemon** [comment]
@deniger small conflict to solve

**Comment by teolemon** [comment]
image
image

**Comment by teolemon** [comment]
image
image

**Comment by deniger** [comment]
Currently these 2 results are normal (without the taxonomy). On the Android app, we use the unit entered by the user to display nutrient values. For fat, mg has been used. for vitamin K,  % DV has been used but in the api gram are returned and so we display the result in gram....this PR will only solve the mismatches in unit display ( gram as milligramme) and we should load the taxonomy to have a correct display

**Comment by deniger** [comment]
This PR is just to fix this kind of issue :). On the current app, unit are mixed and for Golden Viginia, the value "3.5 mg" is displayed instead of 3.5 g ( or 3.500 mg in this PR)
image

**Comment by teolemon** [comment]
Ok, it doesn't match the website, but it's factually correct. Merging. Thanks @deniger

**Pull request merged**
