### PR TITLE
Closes #1342: Add Fastlane support (WIP)

### LINKED ISSUE #1342: Generate screenshots of the app automatically using Fastlane, Screengrab and Espresso
https://docs.fastlane.tools/getting-started/android/screenshots/

### PR DESCRIPTION
**Pull request by Ekt0s**
Hello :) 

This pull request contains changes allowing the usage of Fastlane to generate screenshots and possibly to deploy the applications in the future. 

This PR is related to the issues #1342

The PR is still in **work in progress**

### CODE REVIEW

**Comment by teolemon** [comment]
👍

**Comment by teolemon** [comment]
Can you rebase on latest trunk ? It should fix the build.

**Comment by Karljoones** [comment]
@Ekt0s would you be able to have a look at this PR if you have time?

**Comment by teolemon** [comment]
- Can you rebase ?
- We can also start work on publishing Play Store texts with Open Product Facts

**Comment by Ekt0s** [comment]
I did the rebase.

**Comment by teolemon** [comment]
```
Starting 5 tests on test(AVD) - 5.0.2
openfoodfacts.github.scrachx.openfood.views.JUnit4StyleTests > testTakeScreenshot[test(AVD) - 5.0.2] FAILED 
	java.lang.RuntimeException: Unable to capture screenshot.
	at tools.fastlane.screengrab.FileWritingScreenshotCallback.screenshotCaptured(FileWritingScreenshotCallback.java:56)
:app:connectedObfDebugAndroidTest FAILED
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':app:connectedObfDebugAndroidTest'.
> There were failing tests. See the report at: file:///home/travis/build/openfoodfacts/openfoodfacts-androidapp/app/build/reports/androidTests/connected/flavors/OBF/index.html

```

**Comment by Karljoones** [comment]
@Ekt0s can you have a look at this again? The travis failed with the message above.

**Comment by teolemon** [comment]
Just opened #1570

**Comment by teolemon** [comment]
```
fr:3073780591591
nl:tel:8710496977718
rs:8600043001198
ro:5941341022526
```

**Comment by teolemon** [comment]
I just rebased the branch after a merge conflict @Ekt0s

**Comment by Karljoones** [comment]
I'm closing this for now due to inactivity. Feel free to reopen if you want to work on it again :)

**Pull request closed without merging**
