### PR TITLE
Fixed #1192, fixed #903: new API in Category browser + new light API for categories

### LINKED ISSUE #903: Use the new lite API to delve into categories in the category browser
https://world.openfoodfacts.org/category/pizzas.json?fields=product_name,categories_tags,ingredients_text,image_front_small_url,nutrition_grades_tags

Beware: ensure you pass all the fields necessary to the URL

### LINKED ISSUE #1192: Use the new categories.json file in the Category browser
Now that we download and use the categories.json file (https://static.openfoodfacts.org/data/taxonomies/categories.json) in the Product View, we can reuse it the category browser to increase performance.

### PR DESCRIPTION
**Pull request by l-o-b-s-t-e-r**
#1192
 - implemented loading of translated categories from the local database (or using new API taxonomies/categories.json) in the Category browser.
 - implemented opening of Categories list by click on category in the Category browser.
 
#903
- implemented new light API to load products by category.

### CODE REVIEW

**Comment by teolemon** [comment]
@Karljoones @l-o-b-s-t-e-r Going to merge that one without a second review, because the API calls are stressing the server needlessly.

**Comment by teolemon** [comment]
just a little conflict to solve.

**Comment by l-o-b-s-t-e-r** [comment]
fixed

**Comment by teolemon** [comment]
merged, thanks @l-o-b-s-t-e-r

**Comment by teolemon** [comment]
Error:(81, 17) error: cannot find symbol variable key
/Users/pierre/StudioProjects/openfoodfacts-androidapp/app/src/main/java/openfoodfacts/github/scrachx/openfood/views/ProductBrowsingListActivity.java

**Comment by teolemon** [comment]
I shouldn't have been that hasty.

**Comment by l-o-b-s-t-e-r** [comment]
Sorry 😢 
I'll fix asap

**Pull request merged**
