### PR TITLE
Fix product photos tab from not loading

### LINKED ISSUE #4440: The "product photos" optional tab does not work anymore
### What
- The "product photos" optional tab does not work anymore

### Screen recording

https://user-images.githubusercontent.com/1689815/150647535-d1507eea-984c-4d9a-a616-7bb6c83c6992.mp4

### Part of
- #4170

### PR DESCRIPTION
**Pull request by R4md4c**
####  Description
This PR fixes the product photos tab from not getting shown.

The reason for the issue was that MutableSharedFlow was used, and it wasn't configured to replay the value for late subscribers so when the flow is collected after onStart, the collection didn't receive the product that was set earlier in the onViewCreated.

The PR now lets the ViewModel receive the product through the SavedStateHandle, and once the collection happens the chain gets invoked the product state gets emitted.

#### Related issues
- Fixes #4440

### CODE REVIEW

**Comment by teolemon** [comment]
Oh that's really great @R4md4c , and tested 👌

**Review by teolemon — APPROVED** [review]
Thank you for this PR. Ideally, I'd love to have @VaiTon or @naivekook 's input.

**Comment by teolemon** [comment]
Merging and going to deploy to internal for testing by users :-)  Thank you @R4md4c 💯

**Comment by R4md4c** [comment]
Thanks @teolemon! Please let me know if users face any problems

**Comment by teolemon** [comment]
It works fine again on my device 👌 
Including: 
- on sliding up from scan
- On a product with a lot of existing images

**Comment by teolemon** [comment]
image

**Pull request merged**
