### PR TITLE
Upgrade typography of simple characters

### PR DESCRIPTION
**Pull request by hangy**
Resolves an issue hinted at by Android's linter

### CODE REVIEW

**Comment by VaiTon** [comment]
Unfortunately, as @teolemon said, this is useless as crowdin overwrite changes made via git.

**Comment by teolemon** [comment]
@hangy do you still have the branch ?

**Comment by hangy** [comment]
> @hangy do you still have the branch ?

No, but I can do it again.

**Comment by teolemon** [comment]
I'm fixing it directly in Crowdin. Let's see how it goes.

**Pull request closed without merging**
