### PR TITLE
Fixed #1233: Performance issues on the Product Page.

### LINKED ISSUE #1233: Performance issues on the Product Page (at first load ?)
**Summary:** 

Performance issues on the Product Page (at first load ?)
No logs so far. Possibly had spotty network when it occured. Also, first load after fresh compile.

**Expected behavior:** 

Load the product fast, even on a budget phone

**Observed behavior:** 

Open Food Facts isn't responding, even on a premium phone.

**Device and Android version:** 

Android Oreo, Google Pixel

**Screenshots:** 

image

### PR DESCRIPTION
**Pull request by l-o-b-s-t-e-r**
#1233 
I moved translations loading from the UI thread to the background thread. 
It should improve performance.

### CODE REVIEW

**Comment by l-o-b-s-t-e-r** [comment]
@teolemon @Karljoones any progress here?

**Comment by teolemon** [comment]
Can you rebase on freshest trunk ? We need to untie all the things from the main thread 😨

**Comment by l-o-b-s-t-e-r** [comment]
"rebase on freshest trunk" - do you mean create new PR with the same changes? (move translations loading to the background thread) 😭😭😭

**Comment by ross-holloway94** [comment]
@l-o-b-s-t-e-r https://github.com/edx/edx-platform/wiki/How-to-Rebase-a-Pull-Request

**Comment by l-o-b-s-t-e-r** [comment]
fuh, thanks a lot @ross-holloway94

**Comment by l-o-b-s-t-e-r** [comment]
@teolemon 
@ross-holloway94
I've done rebase)

**Comment by l-o-b-s-t-e-r** [comment]
Can I expect any progress here?

**Comment by teolemon** [comment]
Yes, you can. We're back from the General Assembly :-) 

Can you rebase on latest trunk ?
@ross-holloway94 What do you think of this one ?

**Comment by teolemon** [comment]
@l-o-b-s-t-e-r The timeouts were fixed in trunk. Can you rebase on latest trunk ? It should fix the build and the merge conflict at the same time.

**Comment by ross-holloway94** [comment]
@l-o-b-s-t-e-r sorry for the delay. Could you please re-base and solve the conflicts one last time?

**Comment by ross-holloway94** [comment]
Merged, many thanks @l-o-b-s-t-e-r . I think @teolemon will be happy to see this :)

**Pull request merged**
