### PR TITLE
Fix 2134

### PR DESCRIPTION
**Pull request by jaindiv26**
## Description
Changed the energy value from "kj" to "kJ".

#fixes {#2134}

### CODE REVIEW

**Comment by teolemon** [comment]
@jaindiv26 this has to be changed in
app/src/main/res/values/strings.xml

**Comment by jaindiv26** [comment]
@teolemon Then this issue has already been resolved. As in app/src/main/res/values/strings.xml value is already corrected.
screenshot 2019-02-20 at 12 37 32 am

**Comment by teolemon** [comment]
perfect, I'm merging the Hebrew fix then.

**Comment by teolemon** [comment]
@jaindiv26 can you reopen it ?

**Comment by jaindiv26** [comment]
Already did.

**Comment by teolemon** [comment]
thanks a lot :-)

**Comment by jaindiv26** [comment]
:-)

**Pull request merged**
